### ISSUE TITLE
Add firewall exception to access the IVPN API server (when FW enabled and  VPN disconnected)

### ISSUE THREAD

**Issue by sith-on-mars** [ivpn/desktop-app#10]
# Bug report

## Describe your environment

* Device: _____
* OS name and version: OpenSUSE Tumbleweed Gnome
* IVPN app version: 3.3.10

## Describe the problem

I have always-on firewall enabled. It just happened in the recent days that the app cannot regenerate Wireguard keys on reboot and I had to manually disable always-on firewall to regenerate keys.

![VPN](https://user-images.githubusercontent.com/37974764/117243263-6a479b00-ae26-11eb-86a9-0f444b7f9756.png)

![VPN2](https://user-images.githubusercontent.com/37974764/117243268-6e73b880-ae26-11eb-9645-722054e963eb.png)

**Comment by gorkapernas** [comment]
Verified on version 3.3.13, all platforms, the exception has been implemented and can be found as a customisable option in the Firewall Settings screen, now it is possible to allow IVPN calls when the firewall is enabled (either when enabled manually or using "Always-on"). The option is enabled by default upon a clear installation, but it might be disabled in certain clients after upgrading from the older version.

See screenshot below for reference:
<img width="515" alt="firewall option" src="https://user-images.githubusercontent.com/16647612/119647714-e418e600-be20-11eb-97cf-75561749bdbc.png">

@sith-on-mars please feel free to provide us more feedback regarding this feature once we release the new version of the app.

**Comment by stenya** [comment]
v3.3.20 is released.
[Changelog](https://github.com/ivpn/desktop-app/blob/master/CHANGELOG.md)
