### ISSUE TITLE
(Linux) The Antitracker toggle in the UI doesn't change when enabling/disabling it on the CLI

### ISSUE THREAD

**Issue by gorkapernas** [ivpn/desktop-app#105]
### Description:
The AntiTracker toggle in the UI doesn't change immediately when enabling/disabling it on the CLI, only the toggle changes when connecting to the VPN.

### Expected result:
AntiTracker toggle should change immediately when enabling/disabling it on the CLI.

### Steps to reproduce:
1. Open the IVPN UI.
2. Open CLI.
3. Login with the CLI.
4. Run `ivpn antitracker -on`
5. Observe that the AntiTracker toggle in the CLI doesn't change.
6. Same occurs when running `ivpn antitracker -off`

### Environment:
OS: Ubuntu 20.04
IVPN: 3.4.20

**Comment by stenya** [comment]
@gorkapernas  v3.10.2 is ready for testing

Now, all the default CLI parameters are consistent with UI/daemon

**Comment by gorkapernas** [comment]
Verified fixed on v3.10.2, tested the issue reported regarding the AntiTracker parameter and all other CLI parameters, the changes done in the CLI are also immediately reflected in the UI. This is good to go.

**Comment by stenya** [comment]
v3.10.14 released
