### ISSUE TITLE
Linux: Wifi Control in CLI

### ISSUE THREAD

**Issue by lsm5** [ivpn/desktop-app#107]
# Feature request

## Description

As a CLI user, I'd like to be able to set wifi networks as trusted / untrusted and configure rules for them via CLI itself. I can't yet find any subcommand that will let me do this.

## Describe alternatives you've considered

It's possible in the GUI.

**Comment by gorkapernas** [comment]
This new feature has been tested internally and it should be available in the next desktop apps release.

**Comment by stenya** [comment]
Released in [v3.10.0 Beta](https://github.com/ivpn/desktop-app/releases/tag/v3.10.0)
