### ISSUE TITLE
Homebrew Cask shows error connecting to daemon on launch

### ISSUE THREAD

**Issue by nnothstine** [ivpn/desktop-app#108]
# Bug report

## Describe your environment

Occurs on any version of macOS (tested Big Sur and Monterey).

## Describe the problem

When I install IVPN via the Homebrew Cask, launching it for the first time shows an error connecting to the daemon.

I thought it might be because the application had been quarantined, but `sudo xattr -rd com.apple.quarantine /Applications/IVPN.app/` and attempting to reconnect to the daemon produced the same result. Installing the application manually from the site over the cask *does* work, but `brew install --cask ivpn --no-quarantine` produces no change in results.  

The daemon is definitely loaded (verified `sudo launchctl load /Library/LaunchDaemons/net.ivpn.client.Helper.plist`), so I'm not sure why this is occurring.

![Screen Shot 2021-12-27 at 3 04 07 PM](https://user-images.githubusercontent.com/41174591/147507384-33ae23ca-66e4-4b47-bef2-e065c4c8e38f.jpg)

### Steps to reproduce:

1. Run "brew install --cask ivpn"
2. Launch app

### Observed Results:

The app never works or gets past the initial error screen

### Expected Results:

Expect to be able to use the app normally.

**Comment by ph0ngp** [comment]
I have the same error

**Comment by nnothstine** [comment]
launchctl shows a status of 1, which means it can't access a file:

[2022-01-11 12:10:05.903] [error] DAEMON CONNECTION ERROR: Unable to obtain IVPN daemon connection parameters: Error: ENOENT: no such file or directory, open '/Library/Application Support/IVPN/port.txt'

the logs indicated it couldn't find a given file, but after creating it manually, I'm getting this:

[2022-01-11 12:14:59.367] [error] DAEMON CONNECTION ERROR: Unable to obtain IVPN daemon connection parameters: Error: Failed to parse port-info file

**Comment by nnothstine** [comment]
That traces back to https://github.com/ivpn/desktop-app/blob/070ccdd6f4f7908f9a23ddde3ff6fe2299aec846/ui/src/daemon-client/index.js

What port information should that have by default?

**Comment by ph0ngp** [comment]
Here seems to be the code responsible for creating the port file. Its content has the format of `port_number:some_secret`. Looks like this code is not executed correctly because in this case the `port.txt` file is not created
https://github.com/ivpn/desktop-app/blob/5be864b428ccfdf5af52ddfdb96c7139ed2578d4/daemon/launcher.go#L133-L141

**Comment by gfvcastro** [comment]
I have the same error, too.

macOS OS version:

```bash
% sw_vers
ProductName:	macOS
ProductVersion:	11.6.3
BuildVersion:	20G415
```

**Comment by stenya** [comment]
Hello, 
At the current moment, the only official way to install IVPN on macOS - is to download it from our website (https://www.ivpn.net/apps-macos/).
I will investigate the Homebrew Cask issue. Unfortunately, I cannot provide any estimates yet.

But for now, please, use our website to get the latest IVPN software.

**Comment by stenya** [comment]
I did a quick look into the issue.

It looks like there is a wrong owner (and access rights) for binary files installed by Homebrew Cask.
Here is some info:
```
$ /Applications/IVPN.app/Contents/MacOS/IVPN\ Agent --logging
Sep 22 16:48:37.714 [log   ] Logging enabled
Sep 22 16:48:37.716  Logging enabled (forced by command line argument)
Sep 22 16:48:37.716  version:3.9.32 (date:2022-09-14 commit:4e82eb683213461ebc0f43ed991ab04adc5c9d37)
Sep 22 16:48:37.716  WARNING launcher.go:114: OpenVPN functionality not accessible: (openVpnBinaryPath) /Applications/IVPN.app/Contents/MacOS/openvpn: wrong owner for a file (UID:0). Expected a privilaged user as owner (UID:501)
Sep 22 16:48:37.716  WARNING launcher.go:114: obfsproxy functionality not accessible: (obfsproxyStartScript) /Applications/IVPN.app/Contents/Resources/obfsproxy/obfs4proxy: wrong owner for a file (UID:0). Expected a privilaged user as owner (UID:501)
Sep 22 16:48:37.717  WARNING launcher.go:114: WireGuard functionality not accessible: (wgBinaryPath) /Applications/IVPN.app/Contents/MacOS/WireGuard/wireguard-go: wrong owner for a file (UID:0). Expected a privilaged user as owner (UID:501)
Sep 22 16:48:37.717  WARNING launcher.go:114: WireGuard functionality not accessible: (wgToolBinaryPath) /Applications/IVPN.app/Contents/MacOS/WireGuard/wg: wrong owner for a file (UID:0). Expected a privilaged user as owner (UID:501)
Sep 22 16:48:37.717  WARNING launcher.go:114: route binary error: (routeCommand) /sbin/route: wrong owner for a file (UID:0). Expected a privilaged user as owner (UID:501)
Sep 22 16:48:37.717  ERROR launcher.go:119:(in main.Launch): (firewallScript) /Applications/IVPN.app/Contents/Resources/etc/firewall.sh: wrong owner for a file (UID:0). Expected a privilaged user as owner (UID:501)
Sep 22 16:48:37.717  ERROR launcher.go:119:(in main.Launch): (dnsScript) /Applications/IVPN.app/Contents/Resources/etc/dns.sh: wrong owner for a file (UID:0). Expected a privilaged user as owner (UID:501)
Sep 22 16:48:37.717  ERROR launcher.go:119:(in main.Launch): (openvpnCaKeyFile) /Applications/IVPN.app/Contents/Resources/etc/ca.crt: wrong owner for a file (UID:0). Expected a privilaged user as owner (UID:501)
Sep 22 16:48:37.717  ERROR launcher.go:119:(in main.Launch): (openvpnTaKeyFile) /Applications/IVPN.app/Contents/Resources/etc/ta.key: wrong owner for a file (UID:0). Expected a privilaged user as owner (UID:501)
Sep 22 16:48:37.717  ERROR launcher.go:119:(in main.Launch): (openvpnUpScript) /Applications/IVPN.app/Contents/Resources/etc/dns.sh: wrong owner for a file (UID:0). Expected a privilaged user as owner (UID:501)
Sep 22 16:48:37.717  ERROR launcher.go:119:(in main.Launch): (openvpnDownScript) /Applications/IVPN.app/Contents/Resources/etc/dns.sh: wrong owner for a file (UID:0). Expected a privilaged user as owner (UID:501)
Sep 22 16:48:37.717  ERROR launcher.go:119:(in main.Launch): (dnscryptproxyBinPath) /Applications/IVPN.app/Contents/MacOS/dnscrypt-proxy/dnscrypt-proxy: wrong owner for a file (UID:0). Expected a privilaged user as owner (UID:501)
Sep 22 16:48:37.717  ERROR launcher.go:119:(in main.Launch): (dnscryptproxyConfigTemplate) /Applications/IVPN.app/Contents/Resources/etc/dnscrypt-proxy-template.toml: wrong owner for a file (UID:0). Expected a privilaged user as owner (UID:501)
Sep 22 16:48:37.717  Daemon failed to start due to initialization errors
``` 

```
$ /Applications/IVPN.app/Contents/MacOS/IVPN\ Agent --logging
Sep 22 17:12:07.964 [log   ] Logging enabled
Sep 22 17:12:07.965  Logging enabled (forced by command line argument)
Sep 22 17:12:07.965  version:3.9.32 (date:2022-09-14 commit:4e82eb683213461ebc0f43ed991ab04adc5c9d37)
Sep 22 17:12:07.965  WARNING launcher.go:114: route binary error: (routeCommand) /sbin/route: wrong owner for a file (UID:0). Expected a privilaged user as owner (UID:501)
Sep 22 17:12:07.965  ERROR launcher.go:119:(in main.Launch): (openvpnCaKeyFile) file '/Applications/IVPN.app/Contents/Resources/etc/ca.crt' has wrong access permissions (600 but expected 400)
Sep 22 17:12:07.965  ERROR launcher.go:119:(in main.Launch): (openvpnTaKeyFile) file '/Applications/IVPN.app/Contents/Resources/etc/ta.key' has wrong access permissions (600 but expected 400)
Sep 22 17:12:07.965  ERROR launcher.go:119:(in main.Launch): (dnscryptproxyConfigTemplate) file '/Applications/IVPN.app/Contents/Resources/etc/dnscrypt-proxy-template.toml' has wrong access permissions (600 but expected 400)
Sep 22 17:12:07.965  Daemon failed to start due to initialization errors
```

I will try to investigate what we can do to mitigate/resolve these issues.
But, again, I want to repeat:  there is only one official method to install the IVPN app (at the current moment) - download the DMG file from the [official website](https://www.ivpn.net/apps-macos/).

**Comment by stenya** [comment]
(I have removed my last comment)

**Comment by stenya** [comment]
We are working on this problem and plan to fix the issue in the next official release.

Anyway, the **temporary** solution to make it work is to change access permissions for a few files: 
```
$ sudo chmod 400 /Applications/IVPN.app/Contents/Resources/etc/ca.crt
$ sudo chmod 400 /Applications/IVPN.app/Contents/Resources/etc/ta.key
$ sudo chmod 400 /Applications/IVPN.app/Contents/Resources/etc/dnscrypt-proxy-template.toml
```

**Comment by Clos3y** [comment]
Just to note, this issue has resurfaced for me.

**Comment by dachlu** [comment]
I am also having this issue now
