### ISSUE TITLE
Cannot connect on any remote MySQL server.

### ISSUE THREAD

**Issue by cyberrrr** [ivpn/desktop-app#110]
# Bug report

## Describe your environment

* Device: macOS
* OS name and version: macOS 12.1 Monterey
* IVPN app version: v3.4.0

### Steps to reproduce:

1. Connect to any remote MySQL server on port 3306
2. It fails.

### Observed Results:

Connection timed out. When I disconnect from IVPN, all working fine.

### Expected Results:

Successful connection.

### Relevant Code:

n/a

**Comment by stenya** [comment]
The integrated "Firewall" is blocking all communications except connections going through a VPN tunnel.
If your server is located in a local network you will not be able to communicate with it.

To exclude a specific IP address from firewall blocking rules, please, use "Exceptions" in the Firewall tab settings of the IVPN app.
 
Or, alternatively, there is the option "Allow LAN traffic when IVPN Firewall is enabled"
