### ISSUE TITLE
ivpn 3.5.1 rpm not published to fedora repos

### ISSUE THREAD

**Issue by Enteee** [ivpn/desktop-app#117]
# Bug report

The fedora repos under repo.ivpn.net are missing the 3.5.1 artifact.

## Side note

can you maybe also enable index of pages on the webserver under repo.ivpn.net. Finding issues like this is a major pain without index of pages.

**Comment by stenya** [comment]
@Enteee There is no issue with the Fedora repo. The v3.5.1 is already there.
Please, try to update the local metadata of the repositories on your machine. 

For example, use `--refresh` parameter with `dnf` command:
`sudo dnf upgrade --refresh ivpn-ui`
or
`sudo dnf install --refresh ivpn-ui`

**Comment by Enteee** [comment]
Sorry for reporting this in error. An internal mirror was not properly replicating.
Still enabling directory listing (index of) on your web server would make debugging such issues much easier.
