### ISSUE TITLE
Favorite apps for Split Tunneling 

### ISSUE THREAD

**Issue by stenya** [ivpn/desktop-app#118]
# Feature request

## Description

A Linux customer request:
`I would love to have a way to "favorite" apps in the spit tunnel menu so that I don't have to scroll and search every time.`
A similar requirement can be applied for all platforms where ST is implemented.

**Comment by stenya** [comment]
v3.5.4 is ready for tests

**Comment by stenya** [comment]
```Now, apps in the "installed apps list" are sorted by the last used date. The first element in the list is the application that was used recently. The rest of the elements are sorted by name.```
The change is released in v3.6.4 for Windows already.
It will be available also in the next official release for Linux.

**Comment by stenya** [comment]
Keep ticket open until the update will be released for Linux.

**Comment by gorkapernas** [comment]
Verified on v3.6.11 on different Linux distributions, favourite apps logic has been implemented as described by @stenya in the previous comment.  
>Now, apps in the "installed apps list" are sorted by the last used date. The first element in the list is the application that was used recently. The rest of the elements are sorted by name.
