### ISSUE TITLE
All per-app opt-out of VPN connect

### ISSUE THREAD

**Issue by nschonni** [ivpn/desktop-app#12]
# Feature request

## Description

This is a really nice feature on the Android version, that allows specific applications to not use the VPN tunnel, while pushing the remaining traffic through iVPN

## Describe the solution you'd like

A UI to opt-in at the app or executable level

## Describe alternatives you've considered

Desktop OS network routing might be less flexible at the app level 😦

**Comment by stenya** [comment]
Duplicate https://github.com/ivpn/desktop-app/issues/4
