### ISSUE TITLE
Bug in AUR package install script

### ISSUE THREAD

**Issue by theanonymousexyz** [ivpn/desktop-app#120]
I've discovered a bug in the `ivpn.install` script in the AUR repo at `https://aur.archlinux.org/ivpn.git`, that causes it to throw an error message on systems without `systemd`, complaining about the non-existant `systemctl` command. I've provided a fix below, because I couldn't figure out how to submit it directly to the AUR repo

```diff
diff --git a/ivpn.install b/ivpn.install
index 948d78a..1f9aa8e 100644
--- a/ivpn.install
+++ b/ivpn.install
@@ -72,15 +72,25 @@ pre_remove() {
 }
 
 post_install () {
-  echo "Enabling ivpn-service.service..."
-  systemctl enable --now ivpn-service
+  if has_systemd ; then
+    echo "Enabling ivpn-service.service..."
+    systemctl enable --now ivpn-service
+  else
+    echo "systemd not detected. Please start ivpn-service manually."
+    return 1
+  fi
 }
 
 
 post_upgrade () {
-  echo "Restarting ivpn-service.service..."
-  systemctl daemon-reload
-  systemctl restart ivpn-service
+  if has_systemd ; then
+    echo "Restarting ivpn-service.service..."
+    systemctl daemon-reload
+    systemctl restart ivpn-service
+  else
+    echo "systemd not detected. Please restart ivpn-service manually."
+    return 1
+  fi
 }
 
 post_remove() {
```

**Comment by stenya** [comment]
Hi @theanonymousexyz 
Thank you for the suggested change.

Currently, I am not sure if it good solution to have a package that requires additional steps from users.
Not all users read the build log. They can be confused why the application not working after being successfully installed.
Failing the installation into error is more clear.

I have to think about this change a little.

**Comment by theanonymousexyz** [comment]
> Hi @theanonymousexyz Thank you for the suggested change.
> 
> Currently, I am not sure if it good solution to have a package that requires additional steps from users.

IVPN already requires additional steps to start `ivpn-service` on `systemd`-free distros.

> Not all users read the build log. They can be confused why the application not working after being successfully installed. Failing the installation into error is more clear.

I think most users would be more confused from an error message, because the installation doesn't actually fail, it just fails to start the `systemd` service. Also, I think users of `systemd`-free distros are probably aware that they don't have the `systemctl` command. That's something that confused me, before reading through the error message.

Obviously the best solution would be for the install script to be able to detect the init system and have a service script for it (#1), but until that's implemented I think the best approach would be to display a clear warning/message after installation telling the user that `ivpn-service` wasn't started due to lack of `systemd`, maybe using a `pacman`-hook.

**Comment by stenya** [comment]
You are right.
Changes are integrated into the package v3.5.1-3 
https://aur.archlinux.org/cgit/aur.git/commit/?h=ivpn&id=59b855ac1fef30d2852c8c68285c8b775b5c1f66

**Comment by theanonymousexyz** [comment]
@stenya actually, maybe the `return 1` statements should be removed, as they still cause `pacman` to throw an error message:
```
error: command failed to execute correctly
```

**Comment by stenya** [comment]
@theanonymousexyz  fixed
