### ISSUE TITLE
(Windows) DoH and DoT support

### ISSUE THREAD

**Issue by stenya** [ivpn/desktop-app#122]

**Comment by stenya** [comment]
v3.5.4 is ready for tests

**Comment by gorkapernas** [comment]
Verified on latest version 3.6.4, Windows 11, all the issues reported internally have been fixed and currently the DNS over HTTPs works as expected.
Also tested the upgrade process from 3.5.2 and regular custom DNS on Windows 8 and 10, no new issues found.
This should be good to go.

**Comment by stenya** [comment]
v3.6.4 (Windows)
