### ISSUE TITLE
switching should be much easier

### ISSUE THREAD

**Issue by ajay-gh** [ivpn/desktop-app#125]
# Feature request

## Description

Switching to another city (server), from single to multi-hop, from openvpn to wireguard or back, this all takes far to many mouse clicks, and time in between. When the client is connected, and request to change the connection makes one go through unnecessary hoops. Example: you are on single / Milano / wireguard and you click on "protocol" in the main window - then obviously you want to change that protocol. 
No need to take you to the settings window, let you click on the only other protocol available and THEN tell you that the change is not allowed while you are connected.

## Describe the solution you'd like

When the user tries to make a change which requires to be disconnected then "disconnect", allow the change and reconnect - all in one go. No further clicks, confirmations, etc. needed. Just do it. I cannot see any scenario where a user needs to be protected from silly mistakes by extra confirmation windows (like accidental file deletion or the like).

## Describe alternatives you've considered

n/a

In brief : Please minimize the number of steps the user has to go through for routine tasks.

**Comment by ajay-gh** [comment]
Anybody considering this request ? I know you cannot respond to all requests, but then again, the list of feature requests for iVPN is relatively short compared to other projects ;)

**Comment by stenya** [comment]
@ajay-gh Hello.
We are considering all requests. 
Your request will be added to our Todo list with some priority. But, for now, I can not promisee you any time estimates.

**Comment by stenya** [comment]
@gorkapernas  v3.10.2 is ready for testing

**Comment by stenya** [comment]
@gorkapernas @jurajhilje Info: The firewall keeps unchanged during reconnection. So, no potential leaks are expected.

**Comment by ajay-gh** [comment]
Good morning, very much appreciate that I see that this request has been considered !! Really do. 
On iOS and Android it does already work, and I can't wait to see it implemented for macos.
Thanks again !

**Comment by gorkapernas** [comment]
This has been implemented and tested in the last beta 3.10.11, all platforms. Currently the app automatically connects when switching protocols or when changing any settings from the UI without any confirmation dialogs.

@ajay-gh please let us know if you find any issues with new logic once we officially release the new version.

**Comment by gorkapernas** [comment]
Potential issue found on macOS, needs further investigation.

**Comment by gorkapernas** [comment]
There was an issue where the app was not able to switch protocols while connected.
It happened with the fastest server and after updating from an old IVPN version. This issue has been fixed in all platforms, verified on the latest beta version 3.10.12.

**Comment by stenya** [comment]
v3.10.14 released
