### ISSUE TITLE
Add column with (WireGuard) public keys of available servers

### ISSUE THREAD

**Issue by KaoriRinaFujimoto** [ivpn/desktop-app#126]
# Feature request

## Description

Since it's not possible to download pre configured configuration files when setting up a WireGuard connection, it would be great to at least have the possibility to quickly gather all the necessary information via CLI (endpoint address + public key of each server) to build custom config files with a simple script.   
Currently one has to click through the server list on the website to get the public keys (at least according to my knowledge, correct me if I'm wrong).

## Describe the solution you'd like

Using `ivpn servers -p WireGuard -hosts` already displays all the WireGuard servers with their endpoint address, an additional column displaying the WireGuard public key would help tremendously in building more dynamic configuration setups.

## Describe alternatives you've considered

Currently I have to go to the website and click on each server, which is a little tedious. Alternatively I've considered setting up a simple crawler, but initially I haven't planned on investing too much time into that...

Thanks in advance!

**Comment by stenya** [comment]
Hi @KaoriRinaFujimoto 
the possibility to download pre-configured configuration files for WireGuard is in the final stages of testing.
It will be available on the website soon.

**Comment by stenya** [comment]
There is the possibility to download a pre-configured WireGuard configuration from the client area on the website:
https://www.ivpn.net/account/wireguard-config
Please, note: you have to be logged into the client area.
