### ISSUE TITLE
(Windows) Reversed Split Tunneling

### ISSUE THREAD

**Issue by Treeniks** [ivpn/desktop-app#128]
# Feature request

## Description

The opposite of the current Split Tunneling feature. Every app bypasses the VPN, instead of the ones selected.
I.e., while currently one can "Whitelist" applications to bypass IVPN, I would like to "Blacklist" applications that **shouldn't** bypass IVPN, while everything else uses a direct connection.

## Reasoning

I have seen some comments for this on reddit before and the main reason I found for why this is not a priority (or even planned) is that this feature incentivises non-privacy conscious behaviour, i.e. VPN as an exception not as a rule. However let me lay out some reasons for why this would be useful anyway:

1. Some middleware software doesn't go well with the current Split Tunneling. In particular, I am currently trying to get [this Java-built Discord Bot](https://github.com/BinkanSalaryman/Discord-Audio-Stream-Bot) to bypass the VPN but can't get it to work. Adding `java.exe` or `javaw.exe` to the list of apps in Split Tunneling doesn't do anything. (If somebody knows a solution to this, I would be very thankful. I even tried wrapping it up with Launch4j or similar, but it didn't help.)
2. UWP/Windows Store apps are rather strange to get in the list. One needs to add `C:\Windows\System32\WWAHost.exe` because UWP apps don't have their own executable which is quite unintuitive for non-techy people. This is particularly problematic when using the Netflix/Amazon Prime/... applications.
3. Being someone who plays games, many of them being competitive i.e. low ping is of highest importance, having to add something to the list every single time I play something new is inconvenient and makes the list very confusing. I have already lost overview of my list because of this.
4. Applications with launchers are also unintuitive. This is also often the case for games. For example, when playing Valorant (not a very privacy conscious game I know, but what can I say, I enjoy it), one needs to add the rather hidden `C:\Riot Games\VALORANT\live\ShooterGame\Binaries\Win64\VALORANT-Win64-Shipping.exe` instead of the more obvious `C:\Riot Games\VALORANT\live\VALORANT.exe` because the latter is just a launcher to download updates, which, again, is confusing for non-techy people.

I'm aware IVPN is not exactly made for non-techy people, but I believe those reasons are enough for many to outright disable the VPN completely when these applications are needed, which also incentivises non-privacy conscious behaviour. Not to mention, there **is** no other solution for case 1 to begin with. Instead, having the option to at least route the most privacy critical programs of a system, i.e. the browser, through the VPN would be better than disabling it globally, even if still imperfect. It is certainly a feature I am desperately missing.

**Comment by jonathonf** [comment]
Definitely not a Windows-specific request. Being able to push only certain applications through the VPN would be a very nice feature.

**Comment by v4u6h4n** [comment]
> Definitely not a Windows-specific request. Being able to push only certain applications through the VPN would be a very nice feature.

Agreed, at the moment I'm launching most processes through split tunnel.

**Comment by stenya** [comment]
Similar request: https://github.com/ivpn/desktop-app/issues/272

The Inverse Split Tunnel functionality is currently in the testing stage, and we plan to release it soon.

**Comment by stenya** [comment]
Inverse Split Tunnel mode is now available in the IVPN app v3.13.1 for Windows and Linux. 
Please note that this functionality is still in beta.
