### ISSUE TITLE
Fedora .build-id collisions

### ISSUE THREAD

**Issue by ryanolton** [ivpn/desktop-app#13]
# Bug report

## Describe your environment

* Device: desktop
* OS name and version: Fedora 34
* IVPN app version: v3.3.7 (ivpn-ui)

## Describe the problem

ivpn-ui has `.build-id` collisions with [1Password](https://support.1password.com/getting-started-linux/).

I was able to find a number of other projects in a similar situation:

- https://github.com/jordansissel/fpm/issues/1503
- https://github.com/atom/atom/issues/19692
- https://github.com/bitwarden/desktop/issues/277
- https://github.com/taw00/element-rpm/issues/11

I do not fully understand whether .build-id files are used by the IVPN team, but if they're not, would it be possible to have these files excluded from the build process?

### Steps to reproduce:

1. Install 1Password using the steps noted here for Fedora: https://support.1password.com/getting-started-linux/#centos-fedora-or-red-hat-enterprise-linux
2. Follow the IVPN installation steps here for Fedora: https://www.ivpn.net/apps-linux/#fedora

### Observed Results:

`  file /usr/lib/.build-id/13/070cd6d4401903dee7a42e402d150de4362b18 from install of ivpn-ui-3.3.7-1.x86_64 conflicts with file from package 1password-8.0.33_39.BETA-1.x86_64
  file /usr/lib/.build-id/3e/d503d7be965ab698b328fe3a69162a4efb5351 from install of ivpn-ui-3.3.7-1.x86_64 conflicts with file from package 1password-8.0.33_39.BETA-1.x86_64
  file /usr/lib/.build-id/50/300d22dcba520f8681cbf4f8bd71ff9320371c from install of ivpn-ui-3.3.7-1.x86_64 conflicts with file from package 1password-8.0.33_39.BETA-1.x86_64
  file /usr/lib/.build-id/5b/8864b69ddfe3bd034d5dbef9b814a8f9b59cbd from install of ivpn-ui-3.3.7-1.x86_64 conflicts with file from package 1password-8.0.33_39.BETA-1.x86_64
  file /usr/lib/.build-id/ae/f8abf3f50b39abd59d73628e8cd89cceee8f54 from install of ivpn-ui-3.3.7-1.x86_64 conflicts with file from package 1password-8.0.33_39.BETA-1.x86_64
  file /usr/lib/.build-id/af/4374e54497edac9a84703037832fafb0d99308 from install of ivpn-ui-3.3.7-1.x86_64 conflicts with file from package 1password-8.0.33_39.BETA-1.x86_64
  file /usr/lib/.build-id/b4/fe1769dc0dbcd634d93f5ffd826d0354016f9e from install of ivpn-ui-3.3.7-1.x86_64 conflicts with file from package 1password-8.0.33_39.BETA-1.x86_64
  file /usr/lib/.build-id/f0/d8c634c19103e2e50b980cc1fb5cbacdc8d07c from install of ivpn-ui-3.3.7-1.x86_64 conflicts with file from package 1password-8.0.33_39.BETA-1.x86_64
  file /usr/lib/.build-id/f3/13677b4c4d959f49800be71689dc788f06ae94 from install of ivpn-ui-3.3.7-1.x86_64 conflicts with file from package 1password-8.0.33_39.BETA-1.x86_64
`

### Expected Results:

I expected ivpn-ui to install properly.

### Relevant Code:

https://github.com/ivpn/desktop-app-ui2/blob/master/References/Linux/build.sh

Include `--rpm-rpmbuild-define "_build_id_links none"` in `fpm` command ([link](https://github.com/jordansissel/fpm/issues/1503))

**Comment by stenya** [comment]
Fixed in v3.3.30
