### ISSUE TITLE
Add new ports

### ISSUE THREAD

**Issue by jurajhilje** [ivpn/desktop-app#131]
Add new ports for VPN tunnel settings.

**WireGuard:**
- UDP 80
- UDP 443

**OpenVPN:**
- UDP 80
- UDP 443

**Comment by stenya** [comment]
@gorkapernas  Linux beta for testing: v3.6.9

**Comment by gorkapernas** [comment]
Verified on v3.6.9, Ubuntu 20.04, Fedora 33, the new ports have been added to WireGuard and OpenVPN, the VPN connects as expected with all ports on both protocols.

**Comment by gorkapernas** [comment]
Verified on 3.6.11, Windows and macOS, both ports have been implemented for OpenVPN and WireGuard, the VPN connects successfully with them. This is good to go.
