### ISSUE TITLE
(WireGuard) Desktop app creating multiple adapters

### ISSUE THREAD

**Issue by JomSpoons** [ivpn/desktop-app#133]
# Bug report

* Device: Desktop PC using WiFi
* OS name and version: Windows 10 Pro 21H2
* IVPN app version: v3.6.4

## Describe the problem
When using the WireGuard protocol in the Windows desktop app, it creates a new network adapter every time you change servers, even if you're changing back to a server you've connected to before. This makes integration with some other applications more tedious. (ie: If you set qBittorrent to function only when using a specific network adapter, you'll need to manually change the network adapter it uses each time you change servers.)

### Steps to reproduce:

1. Change the protocol to WireGuard.
2. Connect to a server.
3. Change to a different server.

### Observed Results:
The network adapter will be changed to another each time. (ie: "IVPN" will become "IVPN 2".) The official WireGuard Windows application (v0.5.3) only ever uses one network adapter even when changing servers, so I'm unsure as to why the IVPN app keeps creating new ones.

**Comment by stenya** [comment]
@tlc-at-home 

The official WireGuard client uses unique interface names when connecting to different servers. More precisely, each unique server's public key corresponds to a unique interface name.

> The official WireGuard Windows application (v0.5.3) only ever uses one network adapter even when changing servers, so I'm unsure as to why the IVPN app keeps creating new ones.  

I suppose this could only occur if you're using the same public key for your servers, which is not a recommended approach.

At present, I don't see a possibility to alter this behavior, as it is the expected functionality for the combination of WireGuard and Windows.

For additional information, you can refer to the following links:
https://lists.zx2c4.com/pipermail/wireguard/2019-June/004259.html
https://superuser.com/questions/1733949/how-to-correctly-set-the-interface-name-in-wireguard-in-windows

**Comment by stenya** [comment]
I am closing the ticket now. However, please feel free to reopen it if you believe further discussion or action is warranted.

**Comment by tlc-at-home** [comment]
As I'm up to 200 unique interface names, is it possible to delete them so
forcing IVPN to start at number 1 again?

**Comment by stenya** [comment]
> As I'm up to 200 unique interface names, is it possible to delete them so
forcing IVPN to start at number 1 again?

I believe you can manually remove profiles from the registry at
`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\NetworkList\Profiles\` where the `ProfileName=IVPN XXX`. 

However, please be aware that modifying the registry is not a recommended method for users to adjust their OS. If you choose to proceed, you do so at your own risk. Also, note that this registry branch contains a list of all interfaces on your system.
