### ISSUE TITLE
Cannot connect with Wireguard with "Failed to connect" message.

### ISSUE THREAD

**Issue by maltabeeffishrelish** [ivpn/desktop-app#137]
# Bug report

## Describe your environment

* Device: Desktop  
* OS name and version: Arch Linux
* IVPN app version: 3.7.0  
  

### Steps to reproduce:

1. Install [ivpn](https://aur.archlinux.org/packages/ivpn) and [ivpn-ui](https://aur.archlinux.org/packages/ivpn-ui) from AUR.
2. Start and login.

### Observed Results:
When I try to connect with Wireguard, I get a message "Failed to connect connection error: failed to start Wireguard: exit status 1" and cannot connect. OpenVPN does not have this problem.

### Expected Results:

Successful connection using Wireguard

### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by theanonymousexyz** [comment]
I have a similar problem, but only on Android. It does say it has connected via WireGuard, but it fails to acquire an IP address. PC works fine though. OpenVPN on Android works too.

**Comment by theanonymousexyz** [comment]
@maltabeeffishrelish I've managed to fix it be regenerating my WireGuard keys. Could you try that?

**Comment by maltabeeffishrelish** [comment]
@theanonymousexyz 
I regenerated the key, but it did not change. However, I reinstalled the software with pacman and it solved the problem.

Still, the problem is that it just installed but does not work properly.

**Comment by theanonymousexyz** [comment]
Could you try to enable logging, attempt to connect, and then paste the logs in here?
You can enable logs from terminal like this: `ivpn logs -on`
I don't know about UI.

**Comment by theanonymousexyz** [comment]
@maltabeeffishrelish
Could you try to enable logging, attempt to connect, and then paste the logs in here?
You can enable logs from terminal like this: `ivpn logs -on`
I don't know about UI.

**Comment by maltabeeffishrelish** [comment]
I reinstalled ivpn and the bug no longer reproduces. Close
