### ISSUE TITLE
Unable to connect via OpenVPN/UDP 53

### ISSUE THREAD

**Issue by maltabeeffishrelish** [ivpn/desktop-app#138]
# Bug report

## Describe your environment

* Device: Desktop
* OS name and version: Windows Embedded 8.1 
* IVPN app version: 3.7.0

### Steps to reproduce:

1. Launch the app
2. Set protocol to OpenVPN/UDP 53
3. Connect. Loading icons rotate forever.

### Observed Results:
Unable to connect via OpenVPN/UDP 53. It is possible to connect with other ports and Wireguard.

### Expected Results:

I would like the connection to be completed successfully.

### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by stenya** [comment]
BUG: IVPN Firewall blocks communication to UDP:53 on Windows (all protocols: OpenVPN/WireGuard)

**Comment by gorkapernas** [comment]
Verified on v3.7.6, Windows 8, 10 and 11, both protocols OpenVPN and WireGuard, the app connects successfully with UDP 53. This should be good to go.

**Comment by stenya** [comment]
fixed in v3.8.7
