### ISSUE TITLE
IPv6 is not preferred

### ISSUE THREAD

**Issue by ghost** [ivpn/desktop-app#140]
# Bug report

## Describe your environment

* Device: Desktop
* OS name and version: Windows Embedded 8.1/Arch Linux
* IVPN app version: 3.7.0

### Steps to reproduce:

1. Connect
2. Accessing [IPv6 test](https://ipv6-test.com/) with Firefox

### Observed Results:
IPv4 is preferred over IPv6

### Expected Results:
I want IPv6 to be preferred over IPv4.

### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by maltabeeffishrelish** [comment]
PS: In the OS settings, IPv6 has priority. Also, if you connect without IVPN (using your usual ISP), IPv6 is preferred.

**Comment by jeifour** [comment]
As far as I know (I'm **not** connected to IVPN in any shape or form except being a customer), your OS is still determining which IP to use in most cases, except when an application does it by itself. If conditions on your own network and on IVPN's network are slightly different, that could make your OS prefer IPv4 over IPv6 then. The only way that IVPN can really help here is by implemention #141 which I would also be interested in myself.

**Comment by stenya** [comment]
@ghost Hi.
@jeifour is right. Only the app (browser, OS, ... etc.) is responsible for choosing which protocol to use.
It may depend on different factors which are out of our control (connectivity speel, latency... etc.).
For example, you may get different test results by using different types of browsers or when connecting to different servers.

I am closing the ticket.

**Comment by elvis-hrvat** [comment]
This is the same problem as mullvad/mullvadvpn-app#3608.
IVPN is in the business of networking and has no knowledge of these basic RFCs about IPv6.
Can we trust IVPN to be run by engineers who do not have the proper knowledge?
