### ISSUE TITLE
[bug] UI: App does not reconnect when changing ports while connected

### ISSUE THREAD

**Issue by gorkapernas** [ivpn/desktop-app#142]
### Description:
On version 3.7.0, all platforms, with OpenVPN and WireGuard, when changing ports while connected, the app does not reconnect automatically. 
Actually two different behaviours are observed, if users split the settings from the main panel, the app reconnects after changing ports, but if users go to settings without splitting the app and change ports, then comeback to the main UI, the app doesn't  reconnect.

### Expected result:
The app should reconnect automatically when changing ports while connected.

### Environment:
IVPN: 3.7.0
OS: All platforms

**Comment by stenya** [comment]
@gorkapernas  v3.8.10 is ready for testing

**Comment by gorkapernas** [comment]
Verified fixed on v3.8.10, all platforms, the app reconnects automatically when changing ports while connected.

**Comment by stenya** [comment]
v3.8.20 released

**Comment by stenya** [comment]
Requires new sanity tests after fixing: https://github.com/ivpn/desktop-app/issues/200

**Comment by stenya** [comment]
v3.9.32

**Comment by gorkapernas** [comment]
Verified on v3.9.32, all platforms, it works as expected, the app reconnects automatically when changing ports while connected.
Tested with both protocols OpenVPN and WireGuard.

**Comment by stenya** [comment]
Released in v3.9.32
