### ISSUE TITLE
Cannot compile IVPN-UI in Linux (Raspberry Pi)

### ISSUE THREAD

**Issue by superunknowndude** [ivpn/desktop-app#146]
# Bug report

UI won't compile.

## Describe your environment

* Device: Raspberry Pi 4B 8GB  
* OS name and version: Ubuntu 21.04 64 Bit 
* IVPN app version: 3.7.0

## Describe the problem

I install all the prerequisite programs and compile the CLI without issue. Then I compile the UI with NPM and it nearly finishes, but as it near completion the log file states:

 INFO  Building app with electron-builder:
  • electron-builder  version=22.14.5 os=5.13.0-1025-raspi
  • writing effective config  file=dist_electron/builder-effective-config.yaml
  • packaging       platform=linux arch=arm64 electron=14.2.9 appOutDir=dist_electron/linux-arm64-unpacked
 DONE  Build complete!
**[!] Folder not exists: '/home/pi/desktop-app/ui/References/Linux/../../dist_electron/linux-unpacked'**
    Build IVPN UI project (do not forget to set correct version for it in 'package.json')

### Steps to reproduce:

./build.sh -v 3.7.0
in the /desktop-app/ui/Reference/Linux folder.

### Observed Results:

It goes through the entire build process then fails at the part when it supposed to spit out the .deb file for the UI.

### Expected Results:

* A deb file for the IVPN-UI

### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by stenya** [comment]
@superunknowndude can you please, update, local file `desktop-app/ui/References/Linux/build.sh` (line 54)? :

old line: `APP_UNPACKED_DIR="$SCRIPT_DIR/../../dist_electron/linux-unpacked"`
new line: `APP_UNPACKED_DIR="$SCRIPT_DIR/../../dist_electron/linux-arm64-unpacked"`

![Image 2022-04-25 at 12 31 28 PM](https://user-images.githubusercontent.com/7881006/165062031-644e0c49-2c75-499f-844f-a78047167d38.jpg)

Please, let me know if it helped. So, I will update the build script then.

**Comment by stenya** [comment]
@superunknowndude I have updated the build script.
Feel free to reopen the ticket in case you still have build issues.
