### ISSUE TITLE
Pacstall

### ISSUE THREAD

**Issue by trymeouteh** [ivpn/desktop-app#148]
Please add this app into the pacstall repository. Pacstall is the AUR for Ubuntu which will allow Ubuntu users to easily install the app and receive updates very shortly after an update is released.

https://pacstall.dev/

**Comment by stenya** [comment]
Hi @trymeouteh 

Currently, we do not have plans to support Pacstall.

But we have added the app to the official Snapcrapt repository. https://snapcraft.io/ivpn
All Ubuntu users can easily install the IVPN app from it.
