### ISSUE TITLE
Possibility to manually add network masks which will be used with "Allow LAN" settings

### ISSUE THREAD

**Issue by stenya** [ivpn/desktop-app#15]
# Feature request

## Description

For example:

* subnetworks that have to be processed as 'LAN': 192.168.1.0/24, 192.168.2.0/24, 192.168.3.0/24
* the real (to which the computer belongs to) LAN network 192.168.1.5/24

The current implementation of 'Allow LAN' functionality permits the communication only with the network to which the computer belongs (192.168.1.5/24).
It could be a nice feature to have to be able manually to define additional 'LAN' networks which can be processed by  'Allow LAN' functionality

## Describe the solution you'd like

So we would need some way for the user to specify which networks he considers local and for which he wants a static route added and for the FW to allow. The best UI would probably be a comma separated list of networks e.g. `192.168.20.0/24, 192.168.30/24, 192.168.40/24`
or if the customer is lazy (could have some security consequences) `192.168.0.0/16`

## Describe alternatives you've considered

Have you considered any alternative solutions or workarounds?

**Comment by jacktheripper19** [comment]
I have this issue as well: My laptop is connected to a nested LAN 192.168.42.x in another LAN 192.168.0.x . I have a Server on the outer network that I can't access when I'm connected to VPN even when disabling IVPN firewall or enabling the option to allow LAN connections.

**Comment by btilford** [comment]
+1 on this I've got several VLANs configured and am unable to connect to resources on the other networks. Being able to explicitly configure CIDRs to allow access to would be really nice.

**Comment by Phally** [comment]
+1 on this as well as it adds the ability to use local VMs running on a host-only adapter.

**Comment by paradonym** [comment]
I'd like to expand it a bit. Next to specifying which masks to allow a checkbox to allow all private address ranges would be nice. 
Like having one checkbox for entire 10.0.0.0/8, 172.16.0.0/12 and 192.168.0.0/16...

**Comment by stenya** [comment]
@gorkapernas v3.6.11 is ready for testing on all platforms

**Comment by stenya** [comment]
@gorkapernas v3.6.11 is ready for testing on all platforms

**Comment by stenya** [comment]
@gorkapernas  beta v3.7.6 is ready for tests

**Comment by gorkapernas** [comment]
Verified on latest beta versions, it is possible now to add subnet masks to bypass the IVPN firewall when connected to the VPN. Please note when attempting to connect to certain devices e.g. printer, a static route needs to be added in order to make the connection successful.
We'll be monitoring this for potential issues that may raised after the feature is officially released.

**Comment by Phally** [comment]
Nice! Thank you, thank you ❤️ 

Seems to be working well!
