### ISSUE TITLE
(Linux) Allow LAN: monitor changes in local network interfaces

### ISSUE THREAD

**Issue by stenya** [ivpn/desktop-app#150]
# Feature request

## Description

Currently, the daemon not monitoring any changes in local network interfaces.
Due to this, the "Allow LAN" functionality does not allow communication to local interfaces which were registered dynamically.

When "Allow LAN" is enabled, the firewall rules (to allow LAN interfaces) are applied at the moment of enabling this functionality or at the moment of daemon start. 
So, the rules would be applied only for interfaces that are available at that moment.
If a new LAN interface will appear later - it will be blocked by the firewall by default.

## Describe the solution you'd like

IVPN daemon has to monitor changes in local interface configuration and update "Allow LAN" rules accordingly.

**Comment by stenya** [comment]
@gorkapernas  v3.8.10 is ready for testing

**Comment by gorkapernas** [comment]
Verified on v3.8.10, different Linux distributions, the IVPN firewall does not block new LAN interfaces added after the option "Allow LAN" is enabled, the LAN connection is possible. 
Currently the app detects the new local interface configuration and updates the firewall rules (add or remove LAN interfaces).
