### ISSUE TITLE
Examples of inappropriate IP addresses

### ISSUE THREAD

**Issue by ghost** [ivpn/desktop-app#154]
Firewall Settings→Exceptions lists two IP addresses, 1.2.3.0 and 11.22.33.44.
However, these are real IP addresses and are causing trouble for M247 Ltd and DoD Network Information Center.
It needs to be changed to the correct example IP address such as 192.0.2.0/24 or 198.51.100.0/24.

**Comment by maltabeeffishrelish** [comment]
See also: https://datatracker.ietf.org/doc/html/rfc5737

**Comment by stenya** [comment]
@gorkapernas v3.9.26

**Comment by gorkapernas** [comment]
Verified on 3.9.26/3.9.27, all platforms, the example IP addresses have been updated as follows:
192.0.2.0/24, 198.51.100.1

**Comment by stenya** [comment]
Released in v3.9.32
