### ISSUE TITLE
App always auto-connects to Vienna at launch when "fastest server" is selected

### ISSUE THREAD

**Issue by gorkapernas** [ivpn/desktop-app#156]
### Description:
All platforms, when "autoconnect at launch" is enabled and "fastest server" is selected, the app will always connect to `Vienna, AT` at launch.

### Steps to reproduce:
1. Install 3.8.7 or a previous version.
2. Login.
3. Select "Fastest server".
4. Enable "Autoconnect:  At launch" in General Settings.
5. Close the app.
6. Re-launch the app.
7. Observe that the app connects to Vienna, AT.

### Environment:
IVPN: 3.8.7
OS: All platforms

**Comment by stenya** [comment]
@gorkapernas  v3.8.10 is ready for testing

**Comment by gorkapernas** [comment]
Verified fixed on v3.8.10, all platforms, the app no longer connects to Vienna, but it always attempts to connect to the fastest server instead.

**Comment by stenya** [comment]
v3.8.20 released
