### ISSUE TITLE
MTU too high on Windows

### ISSUE THREAD

**Issue by ferrari** [ivpn/desktop-app#157]
# Bug report

## Describe your environment

* Device: PC
* OS name and version: Windows 10 Pro  
* IVPN app version: 3.8.7

## Describe the problem

For some reason, the MTU is set at 65000, way above anything that can be processed, leading to 10 minute waits for a request to Google. I have to set it to 1420 everytime to be able to access the internet. 

### Steps to reproduce:

1. Open iVPN Client
2. Connect to any server.

### Observed Results:

Since the MTU is so high, requests go into a limbo where they take infinitely long to process anything.

**Comment by stenya** [comment]
The next official version (we plan to release soon) will have the possibility to configure MTU for WireGuatd connection in app settings.

**Comment by gorkapernas** [comment]
Verified in all platforms, latest beta 3.9.29, it is possible to manually configure the `mtu` in the IVPN connection settings or through the IVPN CLI.
Valid range 1280-65535.

See screenshot below for reference:
<img width="563" alt="mtu value" src="https://user-images.githubusercontent.com/16647612/189152931-ae52c73a-6732-4c73-9d84-8b6511743fd7.png">

**Comment by stenya** [comment]
Released in v3.9.32
