### ISSUE TITLE
(Linux) GUI build script does not handle aarch64 correctly

### ISSUE THREAD

**Issue by Kartikeya-IYER** [ivpn/desktop-app#158]
# Bug report

## Describe your environment

* Device: Odroid N2 (an arm64 SoC device)  
* OS name and version: Armbian 11 "bullseye" (arm64 derivative of Debian 11 "bullseye")  
* IVPN app version: 3.8.7

## Describe the problem

On an arm64 SoC device running Armbian 11 "bullseye", when `uname -m` returns `aarch64`, the iVPN GUI build fails because the Electron build artifacts are created at `dist_electron/linux-arm64-unpacked`, but the GUI build script at `desktop-app/ui/References/Linux/build.sh` expects these artifacts to be at a different location.

If the `desktop-app/ui/References/Linux/build.sh` script is modified to set the `ARCH` variable to `arm64` when `uname -m` returns `aarch64`, the GUI build proceeds to a successful completion.

### Steps to reproduce:

1. Install Armbian 11 "bullseye" on an arm64 device. Likely, you can install any other distro which returns `aarch64` for `uname -m` and the problem will be repro'd.
2. Install all prerequisites to build the iVPN source code. I installed:
    - Go v1.18
    - nodejs 16 and npm v8.9.0
    - fpm v1.14.2
    - Other deps as listed in main readme
3. Clone this repo.
4. `cd desktop-app/ui/References/Linux && ./build.sh -v 3.8.7`

### Observed Results:

* What happened? This could be a description, log output, etc.  
The GUI build fails with the following message:
```
Architecture: aarch64
======================================================
============ Building UI binary ======================
======================================================
  "version": "3.8.7",
*** Installing NPM molules ... ***

<SNIP>

INFO  Building app with electron-builder:
  • electron-builder  version=22.14.5 os=5.10.106-meson64
  • writing effective config  file=dist_electron/builder-effective-config.yaml
  • packaging       platform=linux arch=arm64 electron=14.2.9 appOutDir=dist_electron/linux-arm64-unpacked
 DONE  Build complete!
[!] Folder not exists: '/root/IVPN_SOURCE_CODE/desktop-app/ui/References/Linux/../../dist_electron/linux-unpacked'
    Build IVPN UI project (do not forget to set correct version for it in 'package.json')

```

### Expected Results:

* What did you expect to happen? 
I expected that the GUI build would complete successfully.

If the `desktop-app/ui/References/Linux/build.sh` script is modified to set the `ARCH` variable to `arm64` when `uname -m` returns `aarch64`, the GUI build does indeed proceed to a successful completion. In the section below, I have attached a patch file which, when applied to the source code, fixes this problem.

### Relevant Code:

To **fix** this issue, apply the attached patch file at the root of the source code using `patch -p1 < ui_build_fix_for_aarch64.patch.txt` and then perform the GUI build on aarch64.

[ui_build_fix_for_aarch64.patch.txt](https://github.com/ivpn/desktop-app/files/8648331/ui_build_fix_for_aarch64.patch.txt)

**Comment by Kartikeya-IYER** [comment]
@stenya I have created a fix branch for this (using Git Workflow, and a `bugfix` branch from `development`) but I am unable to push my bugfix branch so I can create a PR.

**Comment by stenya** [comment]
@Kartikeya-IYER Thank you.
I am going to review the build script and will implement the fix in a different way.
I want to find a solution how to avoid hard coded values like this:
```
if [ "${TARCH}" = "aarch64" ];then
    ARCH="arm64"
```

**Comment by stenya** [comment]
Related issue: https://github.com/ivpn/desktop-app/issues/146

**Comment by Kartikeya-IYER** [comment]
@stenya Ah! Good point. I was uncomfortable about the hardcoded values too, but at the time I couldn't think of a quick offhand way to fix this so I could get the GUI up and running on my SoC box.

I don't know anything at all about nodejs, but with some quick googling I was able to come up with a way to get the arch from node's `process.arch` (see below) and avoid hardcodes entirely. This works fine on my arm64/aarch64 SoC but I have not yet tested it on any other Linux arch.

```
diff --git a/ui/References/Linux/build.sh b/ui/References/Linux/build.sh
index bf4617a..11c9b81 100755
--- a/ui/References/Linux/build.sh
+++ b/ui/References/Linux/build.sh
@@ -49,7 +49,7 @@ CheckLastResult()
   fi
 }
 
-ARCH="$( uname -m )"
+ARCH="$( node -e 'console.log(process.arch)' )"
 SCRIPT_DIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
 OUT_DIR="$SCRIPT_DIR/_out_bin"
 APP_UNPACKED_DIR="$SCRIPT_DIR/../../dist_electron/linux-unpacked"

```

**Comment by stenya** [comment]
@Kartikeya-IYER Thanks! I like this solution.
I will check it later.

**Comment by Kartikeya-IYER** [comment]
@stenya I just tested the above patch (which uses `node -e`) on a standard x64 Ubuntu 22.04 machine, and it works beautifully :) 

```
$ uname -a
Linux hal9000 5.15.0-27-generic #28-Ubuntu SMP Thu Apr 14 04:55:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/issue
Ubuntu 22.04 LTS \n \l

$ ./build.sh -v 3.8.7
Architecture: x64
======================================================
============ Building UI binary ======================
======================================================
  "version": "3.8.7",
*** Installing NPM molules ... ***

<SNIP>


 INFO  Building app with electron-builder:
  • electron-builder  version=22.14.5 os=5.15.0-27-generic
  • writing effective config  file=dist_electron/builder-effective-config.yaml
  • packaging       platform=linux arch=x64 electron=14.2.9 appOutDir=dist_electron/linux-unpacked
  • downloading     url=https://github.com/electron/electron/releases/download/v14.2.9/electron-v14.2.9-linux-x64.zip size=79 MB parts=8
  • downloaded      url=https://github.com/electron/electron/releases/download/v14.2.9/electron-v14.2.9-linux-x64.zip duration=58.262s
 DONE  Build complete!
[ ] Exist: /home/kartik/DEVTEMP/IVPN_SOURCE_CODE/desktop-app/ui/References/Linux/../../dist_electron/linux-unpacked
[ ] Exist: /home/kartik/DEVTEMP/IVPN_SOURCE_CODE/desktop-app/ui/References/Linux/../../dist_electron/linux-unpacked/ivpn-ui
[ ] Renaming: '/home/kartik/DEVTEMP/IVPN_SOURCE_CODE/desktop-app/ui/References/Linux/../../dist_electron/linux-unpacked' -> '/home/kartik/DEVTEMP/IVPN_SOURCE_CODE/desktop-app/ui/References/Linux/../../dist_electron/bin'
======================================================
============== Building packages =====================
======================================================
---------------------------
DEB package...
Created package {:path=>"ivpn-ui_3.8.7_amd64.deb"}
---------------------------
RPM package...
Created package {:path=>"ivpn-ui-3.8.7-1.x86_64.rpm"}
---------------------------
Copying compiled pachages to '/home/kartik/DEVTEMP/IVPN_SOURCE_CODE/desktop-app/ui/References/Linux/_out_bin'...

```

**Comment by stenya** [comment]
@Kartikeya-IYER Ok great.
Can you, please, create a pull request into the `development` branch?

**Comment by Kartikeya-IYER** [comment]
@stenya I would be happy, but did you give me rights to create a fix branch and create a PR? When I tried to do this earlier I did not have rights to push a fix branch or create a PR in this repo :(

**Comment by stenya** [comment]
merged. 
The change will be moved to the master branch on the next official release.
