### ISSUE TITLE
[bug] App resumes connection automatically when manually generating a WG key

### ISSUE THREAD

**Issue by gorkapernas** [ivpn/desktop-app#163]
### Description:
When pausing the connection, if the user rotates a new WG key manually, the app will resume the connection.

### Expected result:
The app should remain paused when generating a new WG key.

### Steps to reproduce:
1. Install 3.8.7 or beta 3.8.9 on e.g. macOS.
2. Login.
3. Connect.
4. Pause the connection.
5. Proceed to "Connection" settings.
6. Generate a new WG key.
7. Observe that the app resumes the connection.

### Environment:
IVPN: 3.8.7
OS: All platforms

**Comment by stenya** [comment]
@gorkapernas  v3.8.10 is ready for testing

**Comment by gorkapernas** [comment]
Verified fixed on version 3.8.10, all platforms, the app remains paused after manually regenerating the WG key.

**Comment by stenya** [comment]
v3.8.20 released
