### ISSUE TITLE
[bug] UI: mixed favorite servers in tray menu

### ISSUE THREAD

**Issue by stenya** [ivpn/desktop-app#164]
# Bug report
The favorite servers list in the tray menu shows all fav. servers for both protocols (WireGuard and OpenVPN).

There should be shown only favorite servers for the currently selected protocol

**Comment by stenya** [comment]
@gorkapernas  v3.8.10 is ready for testing

**Comment by gorkapernas** [comment]
Verified fixed on v3.8.10, all platforms, tested with protocols, the favourite servers are no longer mixed in the system tray menu, the menu only shows the servers from each protocol.

**Comment by stenya** [comment]
v3.8.20 released
