### ISSUE TITLE
Warning about existing VPN connections when downgrading subscription plan

### ISSUE THREAD

**Issue by jurajhilje** [ivpn/desktop-app#168]
When IVPN apps detect a plan downgrade (from Pro to Standard), an active VPN connection that uses Pro features (MultiHop or Port forwarding) should be disconnected or reconnected with Standard plan features.

Before the active VPN connection is disconnected by the app, a UI alert should be presented with the option to reconnect without pro features (e.g. SingleHop instead of MultiHop).

UI alert:
Title: "_Subscription is changed to IVPN Standard_"
Message: "_Active VPN connection is using Pro plan features (MultiHop or Port forwarding) and will be disconnected._"
Actions:
* OK
* Reconnect with SingleHop VPN

**Comment by stenya** [comment]
v.3.8.26

**Comment by stenya** [comment]
Fixed in [commit](https://github.com/ivpn/desktop-app/commit/7260268388bedfb7f085a18ec4de8f0a16c8c254)

**Comment by stenya** [comment]
@gorkapernas v3.8.28

**Comment by gorkapernas** [comment]
Verified on 3.8.30, all platforms, the issue reported above has been fixed, tested other scenarios and the app behaves as expected. This is good to go.

**Comment by stenya** [comment]
v3.9.0
