### ISSUE TITLE
Fetch session status periodically

### ISSUE THREAD

**Issue by jurajhilje** [ivpn/desktop-app#170]
Fetch session status `/v4/session/status` every 60 minutes.

**Comment by stenya** [comment]
v3.8.26

**Comment by gorkapernas** [comment]
Verified on v3.8.26, now the app calls session status every 1 hours, tested along with https://github.com/ivpn/desktop-app/issues/168 -> I connected with MultiHop, downgraded the plan and waited for the app to show the warning an hour later.

The check on `/v4/session/status` every 60 minutes is an addition to the existing ones i.e.:
- When booting the machine (daemon starts)
- After disconnecting from VPN
- When IVPN UI starts

**Comment by stenya** [comment]
v3.9.0
