### ISSUE TITLE
UI: Ability to connect to a concrete host

### ISSUE THREAD

**Issue by stenya** [ivpn/desktop-app#171]
# Feature request

## Description

Currently, there is the possibility to connect to a location.
IVPN client chooses a random server from this location (if there is more than one server).

Necessary to implement the possibility to connect to the concrete server from the UI (CLI already has such functionality).

**Comment by stenya** [comment]
v3.8.26

**Comment by stenya** [comment]
fixed in v3.8.29

**Comment by gorkapernas** [comment]
Verified on v3.8.30, all platforms, the issues reported above have been fixed, there are no more lags in the UI and the request to remove the favourite star for locations which only have host has been implemented, so when adding the location as favourite, the host will be shown in the favourite list.

Also tested connectivity to different hosts with both OpenVPN and WireGuard, SingleHop and MultiHop, UI and CLI.
This looks good to go.
