### ISSUE TITLE
Split-Tunnel Improvements

### ISSUE THREAD

**Issue by candroid-man** [ivpn/desktop-app#172]
# Feature request

## Description

The main use I would have for this personally is with Steam and other game launchers. Every time I need to open Steam, either for the first time or after restarting it because Steam likes to freeze, I have to go into IVPN > Settings > Split Tunnel > Launch Application > Steam.

## Describe the solution you'd like

I'm not knowledgeable enough to know the limitations of the current version of Split Tunnel as it is in Beta, but I have a few possible solutions:

1. Instead of launching the app from the list of apps in the settings, simply add checkboxes next to each app. Once the app is checked, it will always be excluded from the network
2. Perhaps you could find a way to utilize your CLI tools on Linux to allow users to use the `ivpn exclude` command to automatically be entered before a certain app is launched

**Comment by stenya** [comment]
Unfortunately, there isn't a robust solution to monitor and manage all applications starting on Linux. This capability is necessary to ensure no leaks occur for the configured applications to be executed in split-tunnel mode.

Therefore, it's not feasible to implement a split tunneling feature similar to that in Windows (where configured applications are automatically added to the split tunnel).

As an alternative solution to reduce the number of clicks required to run frequently used apps in a split-tunnel environment, I suggest using manual shell scripts.

Here is an example:
```
#!/bin/bash

ivpn exclude <your_app_binary>
```
