### ISSUE TITLE
Ability to take part in Beta testing for users

### ISSUE THREAD

**Issue by stenya** [ivpn/desktop-app#175]
# Feature request

## Description

The users should have the possibility to take part in testing of latest application features which is not released officially yet.

## Describe the solution you'd like

Settings must be extended by a new parameter to enable/disable the beta testing program.
When it is enabled - a user will receive notifications about available updates to the latest beta versions.

**Comment by stenya** [comment]
The beta for macOS is ready (v3.9.1).

**Comment by stenya** [comment]
... also, reworked the the 'send diagnostic logs' view

**Comment by gorkapernas** [comment]
@stenya the build seems to be working fine, please let me know when the new text has been reviewed and I'll check it again.

**Comment by stenya** [comment]
v.3.9.3

**Comment by gorkapernas** [comment]
Verified on v3.9.6, latest beta, Windows and macOS, beta updates work as expected, also diagnostic logs.
New text has been reviewed and looks good to go.

**Comment by stenya** [comment]
Released in v3.9.8
