### ISSUE TITLE
Implement ability to add specific hosts to the favourite menu of the system tray icon

### ISSUE THREAD

**Issue by gorkapernas** [ivpn/desktop-app#176]
### Description:
Currently when adding a specific host to favorites, the host only shows in the favorite list of the UI, but not in the system tray icon menu "favorite servers", only the locations can be added to this menu.

### Actual result:
![Screenshot 2022-07-21 at 11 10 15](https://user-images.githubusercontent.com/16647612/180176681-8557590a-b8d0-4160-9da2-638d014814a7.png)

### Expected result:
Please add the ability to add specific hosts to the "favorite servers" menu of the system tray icon.

---------------

This issue relates to https://github.com/ivpn/desktop-app/issues/171

**Comment by stenya** [comment]
v.3.9.3

**Comment by gorkapernas** [comment]
Verified on v3.9.3/v3.9.4, all platforms, now it is possible to add specific hosts to the "Favorite" menu of the system tray/dock icon AND connect to those hosts from the same menu.
This is good to go.

**Comment by gorkapernas** [comment]
@stenya I just observed one issue which seems to be related to this ticket.
When adding servers to the favorite servers list, if "fastest server" or "random server" is selected in the UI and the user tries to connect via dock or system tray icon menu to a favourite server, the app always connects to the "fastest server". or "random server" respectively.

The issue does not happen on our live build.
The issue does not happen if any server is selected in the UI, only if "Fastest server" or "Random server" is selected. 

**Steps:**
1. Install latest beta 3.9.5.
2. Login.
3. Select "Fastest Server" in the list of servers (or random server).
4. Add servers (hosts or locations) to the favorite list.
5. From the system tray icon, open the menu and try to connect to any of the favorite servers.
6. App connects to the fastest server instead (or random server if selected in the UI).

**Comment by stenya** [comment]
v3.9.6

**Comment by gorkapernas** [comment]
Verified fixed the issue mentioned in my last comment, the app connects to the favorite server selected in the system tray menu, regardless if "fastest server" or "random server" was selected previously in the UI.

@stenya please note that I experienced an issue the first time I updated the IVPN version to 3.9.6 from 3.9.0, every time I selected "fastest server" in the list of servers of the UI (while connected), the app immediately disconnected me from the VPN, but the FW remained enabled. I reinstalled the IVPN version and unfortunately I can't reproduce the issue anymore.
I'll keep investigating this issue and create a new ticket in case I'm able to reproduce it again.
Maybe you have an idea why this issue could have happened?

**Comment by stenya** [comment]
@gorkapernas FYI: https://github.com/ivpn/desktop-app-shadow/issues/79

**Comment by stenya** [comment]
Released in v3.9.8
