### ISSUE TITLE
Dock menus in macOS app

### ISSUE THREAD

**Issue by rakleed** [ivpn/desktop-app#179]
# Feature request

## Description

Can't manage connection via Dock menus in macOS app.

## Describe the solution you'd like

Could you add [Dock menus](https://developer.apple.com/design/human-interface-guidelines/components/menus-and-actions/dock-menus/) in a macOS app with connection to the fastest sever and recent servers? So that users can quickly connect to a VPN if they are used to using this method in other apps.

**Comment by stenya** [comment]
Added macOS dock menu (similar to tray menu).

A "favorite servers" list can be used instead of  'recent servers'.
The "Fastest server" option will be shown in the menu when the "Fastest server" is selected in the app UI.

**Comment by stenya** [comment]
v3.9.3

**Comment by gorkapernas** [comment]
Verified on v3.9.3, the menus from the system tray icon are now also available in the dock icon.
See screenshot below for reference.
![system dock menus](https://user-images.githubusercontent.com/16647612/182355772-ab2d4a62-396b-4fbf-88d3-b52dba14b266.png)

**Comment by rakleed** [comment]
@stenya is it possible to remove "Account", "Settings" and "Check for Updates" from the Dock menu? Since these actions are usually in the menu bar.

And "Show IVPN" seems redundant, since for this I can simply click on the app icon in the Dock.

**Comment by stenya** [comment]
It has sense. 
I will change it. Thanks.

**Comment by stenya** [comment]
v.3.9.5

**Comment by gorkapernas** [comment]
Verified on version 3.9.5/3.9.6, the new changes have been implemented accordingly, only "connect to" and "favorite servers" are displayed in the IVPN dock menu.

Also note that there was also an issue which is now resolved, the menus were not responsive when the app was trying to establish connecting to the VPN or disconnecting from the VPN, for this reason, now the IVPN dock menus are not displayed during connecting/disconnecting state, only after the VPN connection/disconnection is completed. 

@rakleed please let us know if you have any issues with the IVPN dock menus once we release the new IVPN version. Thanks.

**Comment by stenya** [comment]
Released in v3.9.8
