### ISSUE TITLE
The macOS is restoring the default DNS configuration

### ISSUE THREAD

**Issue by stenya** [ivpn/desktop-app#18]
# Bug report

## Describe your environment

1. Connect VPN (any protocol)
1.1 (not obligatory step) We can also set custom DNS or enable AntiTracker
2. Check OS DNS config - DNS is OK
3. Disable WiFi
4. Enable WIFI (for OpenVPN connection: enable WiFi in less than 30 seconds after wifi was disabled)
5. Check OS DNS

Expected:
OS is using IVPN DNS (or custom DNS, if defined)

Observed:
OS is using the default DNS server (non-IVPN configured).
If the IVPN firewall is enabled -> user is unable to use web browsers because the default DNS is blocked by the firewall.

## Possible solution
The app has to monitor all changes to the  DNS configuration on a computer and fix it (when required)

**Comment by stenya** [comment]
v3.9.35

**Comment by stenya** [comment]
@gorkapernas can you, please, check also https://github.com/ivpn/desktop-app/issues/202 ?
I believe, it is the same issue.

**Comment by gorkapernas** [comment]
Verified fixed on v3.9.35, firstly I reproduced the issue on a previous version by following the steps provided in the ticket, but in the newest beta version, the issue no longer occurs, every time I enable WIFI or switch networks, the OS uses the IVPN DNS as expected.

Regarding #202, there aren't many details, but it looks like it's the same issue, I was able to reproduce the problem by switching networks, but with the fix implemented on this ticket, the issue has been solved.

**Comment by stenya** [comment]
v3.9.43
