### ISSUE TITLE
macOS app won't close with Cmd+Q

### ISSUE THREAD

**Issue by rakleed** [ivpn/desktop-app#182]
# Bug report

## Describe your environment

* Device: 
* OS name and version: macOS 12.4
* IVPN app version: 3.9.0

### Steps to reproduce:

1. Open IVPN
2. Quit IVPN with Cmd+Q

### Observed Results:

* IVPN continues to run in the background. If you expand IVPN and quit again with Cmd+Q, then IVPN will actually quit.

> Logs sent via the app, report ID `25c732d6756a4c0faa81aaec9d58c827`

### Expected Results:

* IVPN quit the first time Cmd+Q is pressed.

**Comment by stenya** [comment]
v3.9.3

**Comment by gorkapernas** [comment]
Verified fixed on 3.9.3, the IVPN app quits the first time Cmd+Q is pressed.

**Comment by stenya** [comment]
Released in v3.9.8
