### ISSUE TITLE
Unnecessary popup when shutting down macOS

### ISSUE THREAD

**Issue by rakleed** [ivpn/desktop-app#183]
# Bug report

## Describe your environment

* Device: 
* OS name and version: macOS 12.4
* IVPN app version: 3.9.0

### Steps to reproduce:

1. Open IVPN
2. Connect to any server
3. Shut down macOS

### Observed Results:

* IVPN does not quit, displaying a popup that the VPN connection will be terminated. But this is a meaningless popup, since naturally when I shut down macOS I understand that the VPN connection will be terminated.

<details><summary>Screenshot</summary>

![Screenshot 2022-07-25 at 05 02 22](https://user-images.githubusercontent.com/19418601/180679369-651fbb19-d5cd-4cce-8e2b-fe783a4be64f.png)

</details>

> Logs sent via the app, report ID `04a69707395e4b18963e646fcd194153`

### Expected Results:

* IVPN quits without a popup.

**Comment by stenya** [comment]
The change is applicable to macOS and Linux.

**Comment by stenya** [comment]
v3.9.3

**Comment by gorkapernas** [comment]
Verified fixed on v3.9.3. macOS and Linux, the popup is not displayed anymore when shutting down the macOS or Linux machine.

**Comment by stenya** [comment]
Released in v3.9.8
