### ISSUE TITLE
Auto reconnect when changing protocol in macOS app

### ISSUE THREAD

**Issue by rakleed** [ivpn/desktop-app#184]
# Feature request

## Description

If I was connected to a VPN, I wanted to be able to change the protocol, and the app would automatically reconnect to the same server, but use a new protocol.

## Describe the solution you'd like

You have this implemented in the iOS app, it would be nice if it could also be done in the macOS app.

**Comment by stenya** [comment]
Similar request: https://github.com/ivpn/desktop-app/issues/125

**Comment by stenya** [comment]
@gorkapernas  v3.10.2 is ready for testing

**Comment by gorkapernas** [comment]
Verified in all platforms, beta version 3.10.11.
See https://github.com/ivpn/desktop-app/issues/125 for further details.

**Comment by stenya** [comment]
v3.10.14 released
