### ISSUE TITLE
Port used in the CLI not updated in the UI

### ISSUE THREAD

**Issue by gorkapernas** [ivpn/desktop-app#188]
### Description:
When connecting to a specific port using the CLI, the UI does not show the same port, it always chooses the same one by default.

Also there seems to be inconsistent information regarding the connection info between the CLI and UI.

### Steps to reproduce:
1. Install version 3.9.0.
2. Login.
3. In the CLI, connect to a specific port e.g. `ivpn connect -port UDP:2050 es.wg.ivpn.net`
4. Observe that the UI shows a different port -> UDP 48574

### Environment:
IVPN: 3.9.0
OS: All platforms

**Comment by gorkapernas** [comment]
Verified fixed on 3.9.3, all platforms, the same port the user connects to is displayed on both the GUI and the CLI.
Tested with different ports and protocols.

**Comment by stenya** [comment]
Released in v3.9.8
