### ISSUE TITLE
(Linux) Docker localhost service refuses to start when connecting with Firewall enabled

### ISSUE THREAD

**Issue by stenya** [ivpn/desktop-app#19]
**Description**
A user has reported that he is unable to start/stop/restart his localhost docker service when connected via our CLI app with Firewall and ‘Allow LAN’ option enabled.

The issue appears to be Firewall related and ‘Allow LAN’ option might not be working as intended. No issue occurs when he connects via NetworkManager using our config files.

VPN : CONNECTED
us-ga.gw.ivpn.net, Atlanta, GA (US), United States
Protocol : OpenVPN
Local IP : 10.48.16.5
Server IP : 107.150.22.74
Connected : 2020-06-03 06:30:29 -0400 AST
AntiTracker : Enabled
Firewall : Enabled
Allow LAN : true

**Environment**
IVPN Client 2.12.2

Fedora Workstation 32 (latest updates)

**Steps To Reproduce**
1. Connect to the OpenVPN (?WireGuard?) server with 'firewall -lan_allow' option
2. Run Start/Stop/Restart docker commands, e.g. "sudo systemctl start docker"
3. Observe the following error:
"Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details."

**Comment by theanonymousexyz** [comment]
@stenya I have a different, but kinda similar issue. I am able start/stop Docker containers, but if I start a container with an exposed port, I am unable to connect to it via localhost. Only after running `ivpn firewall -lan_allow` (which is already enabled) again am I able to connect to my Docker services. This is on Fedora Workstation 35 and Artix Linux.

**Comment by stenya** [comment]
@theanonymousexyz Which IVPN Client version do you use?

**Comment by theanonymousexyz** [comment]
> @theanonymousexyz Which IVPN Client version do you use?

CLI v3.7.0 on both distros. Installed from official channels.

**Comment by stenya** [comment]
Custom Firewall exceptions are implemented in v3.8.7.
Now, there is the possibility to exclude addresses or subnets that will be allowed through the firewall when enabled.

**Example how to allow communication through exposed ports of docker container:**

1) Check the local IP address of the docker interface: 
![image](https://user-images.githubusercontent.com/7881006/166705728-6533cc08-d8ab-4809-8952-2e281b62d7be.png)

2) Add docker interface IP to IVPN Firewall exceptions (the local IP of the default network interface can be added too)
![Image 2022-04-28 at 11 18 09 AM](https://user-images.githubusercontent.com/7881006/166705985-8baf3d58-c7bb-4538-bad5-e9950aabb6be.jpg)

**Comment by theanonymousexyz** [comment]
@stenya thanks for the fix. I which cases would you exclude the default network interface?

**Comment by stenya** [comment]
You can statically exclude the local network interface if you have problems with the "Allow LAN" functionality.
It is not required for solving Docker problems.

**Comment by theanonymousexyz** [comment]
> @stenya I have a different, but kinda similar issue. I am able start/stop Docker containers, but if I start a container with an exposed port, I am unable to connect to it via localhost. Only after running `ivpn firewall -lan_allow` (which is already enabled) again am I able to connect to my Docker services. This is on Fedora Workstation 35 and Artix Linux.

For anyone else having the above problem:
I've managed to fix it by setting a persistent IP range in `/etc/docker/daemon.json` like so:
```json
{
  "default-address-pools": [
    {
      "base": "172.17.0.0/16",
      "size": 24
    }
  ],
  "other_settings": "..."
}
```
And adding `172.17.0.0/16` to IVPN firewall exceptions as described by @stenya above.
