### ISSUE TITLE
Toggle Port Forwarding In Clients

### ISSUE THREAD

**Issue by trymeouteh** [ivpn/desktop-app#193]
# Feature request

## Description

Being able to enable and disable port forwarding in the IVPN client without having to log into the website.

## Describe the solution you'd like

Having a Port Forwarding section in the client settings

## Describe alternatives you've considered

None

**Comment by nschonni** [comment]
This should probably get closed since https://www.ivpn.net/blog/gradual-removal-of-port-forwarding/
