### ISSUE TITLE
Mismatch of servers when changing MultiHop entry and exit servers immediately one after the other

### ISSUE THREAD

**Issue by gorkapernas** [ivpn/desktop-app#197]
### Description:
When connected with OpenVPN MultiHop, if the user changes the entry and exit servers immediately one after the other, a mismatch of servers (selected against connected) will be displayed in the UI.

### Expected result:
The app should always connect to the servers the user selects.

### Steps to reproduce:
1. Install v3.9.8.
2. Login.
3. Select OpenVPN, MultiHop.
4. Connect to any entry and exit servers.
5. Change entry and exit servers immediately one after the other.
6. Observe the issue

### Screenshot:
![mismatch servers MultiHop OpenVPN](https://user-images.githubusercontent.com/16647612/184349582-e6f7c4c4-05f9-4707-99e3-ca1afc46fbd0.png)

### Environment:
IVPN: 3.9.8
OS: All platforms

**Comment by stenya** [comment]
I was not lucky to reproduce the issue.
But it can be already fixed by changes I made for https://github.com/ivpn/desktop-app/issues/210.

v3.9.35 is ready for testing.

**Comment by gorkapernas** [comment]
Verified on v3.9.35, all platforms, the issue doesn't seem to happen anymore, currently the app always connects to the last server selected, so the mismatch between the exit server displayed in the UI and actual server the VPN is connected to does not happen.
The app always connects to the last exit server selected, before the app connected to the previous server, but the UI displayed the server selected, hence the mismatch.
This looks good to go, however I'll run some tests once we create a production build.

**Comment by stenya** [comment]
v3.9.43
