### ISSUE TITLE
Information after subscription renewal doesn't appear in app until it's completely restarted

### ISSUE THREAD

**Issue by rakleed** [ivpn/desktop-app#199]
# Bug report

## Describe your environment

* Device: 
* OS name and version: macOS 12.5
* IVPN app version: 3.9.8

### Steps to reproduce:

1. Sign in to the app using the account on which the subscription has expired
2. Renew the subscription on the site, while the app must remain open
3. After renewal, open the Account settings in the app

### Observed Results:

* The app says the subscription is still expired. Only after a complete restart of the app is it displayed that the subscription is active

### Expected Results:

* A few seconds after the renewal of the subscription on the site, the app automatically updates the information that the subscription is active

**Comment by stenya** [comment]
Fixed in v3.14.2.
The user account information is refreshed each time the ‘Account’ view is opened in ‘Settings’.
