### ISSUE TITLE
DNS not changing

### ISSUE THREAD

**Issue by AndrewVos** [ivpn/desktop-app#2]
# Bug report

## Describe your environment

* Device: PC
* OS name and version: Arch Linux, using systemd-networkd and systemd-resolved.
* IVPN app version: Latest

## Describe the problem

When using the CLI, the DNS being used doesn't appear to change. This is unexpected to me, because the NordVPN client does exactly this somehow.

### Steps to reproduce:

1. Connect to VPN with the CLI
2. Notice that DNS queries are still going to the old DNS provider.

**Comment by stenya** [comment]
The DNS management mechanism was updated since v3.9.0.
Now the app works correctly with systemd-resolved
