### ISSUE TITLE
(Linux) Obfsproxy does not work on Ubuntu 20+

### ISSUE THREAD

**Issue by stenya** [ivpn/desktop-app#20]
# Bug report

**Description**
Users on Ubuntu 20.x+ are unable to connect with Obfsproxy enabled as the system uses obfs4proxy package instead of obfsproxy (obfs3).

obfproxy package is available only for Ubuntu 16 and 18. Ubuntu 20+ has only obfs4proxy available via default repositories.

**Comment by stenya** [comment]
Beta v3.3.47 is ready for testing

**Comment by gorkapernas** [comment]
Verified on Beta v3.3.47, Ubuntu 20.04, the issue described in the ticket no longer occurs, the obfsproxy binary v4 has been integrated into the app, so it works immediately after installing IVPN. 
Tested after upgrading IVPN and on fresh installation, and the app connects successfully with obfsproxy on both cases.

**Comment by stenya** [comment]
Released in v3.4.0
