### ISSUE TITLE
App reconnects when clicking on the protocol section of the main panel

### ISSUE THREAD

**Issue by gorkapernas** [ivpn/desktop-app#200]
### Description:
When the map is closed and VPN connected, the app reconnects after clicking on the protocol section of the main panel.
This issue is not observed when the map is opened.

### Expected result:
The VPN should remain connected all the time.

### Steps to reproduce:
1. Install v3.9.8 macOS / 3.9.9 Windows
2. Login.
3. Select OpenVPN to better observe the issue (also occurs with WireGuard).
4. Close the map.
5. Connect to the VPN.
6. Click on the protocol section section.
7. Observe that the Connection Settings opens, and the VPN reconnects.

### Environment:
IVPN: 3.9.8 / 3.9.9
OS: macOS, Windows

**Comment by stenya** [comment]
Corrected STR:
1. Install v3.9.8 macOS / 3.9.9 Windows
2. Login.
3. Select OpenVPN to better observe the issue (also occurs with WireGuard).
4. Close the map.
5. Connect to the VPN.
6. Click on the protocol section section.
7. Observe that the Connection Settings opens, and the VPN reconnects.

**Comment by stenya** [comment]
v3.9.23

**Comment by gorkapernas** [comment]
Verified fixed on v3.9.23/3.9.24, macOS and Windows, followed the steps provided in one of the previous comment, the app does not reconnect when clicking on the protocol section of the main panel.

**Comment by stenya** [comment]
v3.9.32

**Comment by gorkapernas** [comment]
Verified on v3.9.32, all platforms, the fix still present on this version, the app does not reconnect when clicking on the protocol section of the main panel.

**Comment by stenya** [comment]
Released in v3.9.32
