### ISSUE TITLE
Follow XDG Base directory specification

### ISSUE THREAD

**Issue by ItsDrike** [ivpn/desktop-app#201]
# Feature request

## Description

On Linux system, running `ivpn connect` creates a `.ivpn` folder in users `$HOME` directory. This clutters the home directory for no reason, when there's already a well established and known standard as to where these kinds of files should go instead.

The  [XDG Base Directory spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) specifies that all configuration files belong into `$XDG_CONFIG_HOME`, which if not set, should default to `~/.config`, rather than `$HOME`. Alternatively, there's also `$XDG_CACHE_HOME` (or by default `~/.cache`) and `$XDG_DATA_HOME` (default: `~/.local/share`). 

## Describe the solution you'd like

The ivpn cli application, (and possibly the graphical application too, though I don't use that one) should use these directories instead of cluttering the home directory for absolutely no reason and not following a well established specification.

While I'm not familiar enough with the source code of these applications to suggest which files should go where exactly, however here's the rule of thumb (for more, you can read the above linked full spec):

- `$XDG_CONFIG_HOME` is here to hold static data that isn't expected to change very often. This is usually for user-defined configuration or things like storing credentials. These files may be accessed often, but writing into them should be rare, they're usually set once and not really touched again, unless the user wants to change their config settings.
- `$XDG_DATA_HOME` should hold data that may be changing relatively often, things like databases. 
- `XDG_CACHE_HOME` should only be used for holding files that don't need to be backed up and loosing these files wouldn't cause any significant issues. It is expected that if the files in this location are lost, it wouldn't affect the program in any way and they should simply be regenerated cleanly. While this folder isn't automatically cleaned like temporary files would be, the user may clean them at any time and this shouldn't cause issues.
- There are some other locations too, but they're not used that commonly, they're mentioned in the specification linked above, most notably, these are: `$XDG_STATE_HOME` and `$XDG_RUNTIME_DIR`

### Achieving this without breaking compatibility

If there already are some critical files stored in `~/.ivpn` which should be persisted, breaking backwards compatibility is often not worth this change, for which reason there are several standard and commonly used ways to get around this issue:

- Search in `~` first, if the `.ivpn` directory is found, use it, if not, search the xdg locations. If the directory isn't yet created at all, create it in the xdg locations
- Use an environmental variable for configuring where the application files should live, and default to `~`, without considering XDG locations. As an example, user can export an env variable like `IVPN_HOME="$XDG_CONFIG_HOME/ivpn"` which will get picked up, allowing the user to deal with figuring out where the folder should be, and the project only picking up on it.
- CLI flag passed for each time `ivpn` is ran (might not be ideal with graphical application though). As an example, users could use `ivpn --config-dir=/path/to/ivpn_config`, with `~/.ivpn` being used by default. This is however the most annoying option for the users, and even though these flags can be passed through smart use of aliases like `alias ivpn="ivpn --dir=/x/y/z"`, it's still the least common, and least recommended way to do this, but it's better than not providing a way to change the config at all.

**Comment by sanks64** [comment]
Would like to see this as well.

In my case, there is only `last_connection` in the `.ivpn` directory, which seems to be only needed for `ivpn connect -last`.

If the GUI application doesn't create additional files there, a plan for backwards compatibility might not even be needed, as `last_connection` seems relatively unimportant.

**Comment by sanks64** [comment]
[This](https://wiki.archlinux.org/title/XDG_Base_Directory) might be a great source of documentation. It also links to [the full specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).

**Comment by stenya** [comment]
@gorkapernas  v3.10.2 is ready for testing
ivpn CLI does not create `~/.ivpn` anymore.

**Comment by gorkapernas** [comment]
Verified on v3.10.2, I confirm that the folder `~/.ivpn` is no longer created. This is good to go.

**Comment by stenya** [comment]
v3.10.14 released
