### ISSUE TITLE
App does not connect to the last port selected

### ISSUE THREAD

**Issue by gorkapernas** [ivpn/desktop-app#203]
### Description:
When the app is connected (OpenVPN or WireGuard), if the user changes port multiple times, the app will only try to establish connection to the first port selected, not the last one.

### Expected result:
The app should always establish connection to the last port selected.

### Steps to reproduce:
1. Install version 3.9.14, any platform.
2. Login.
3. Select OpenVPN to better observe the issue.
4. Connect to any server, SingleHop.
5. Proceed to Settings.
6. Change port multiple times.
7. Observe that the app connect to the first port selected, not the last one.

### Environment:
IVPN:  3.9.14
OS: All platforms

**Comment by stenya** [comment]
I was not lucky to reproduce the issue.
But it can be already fixed by changes I made for https://github.com/ivpn/desktop-app/issues/210.

v3.9.35 is ready for testing.

**Comment by gorkapernas** [comment]
Verified on v3.9.35 staging and v3.9.34 production, the issue is no longer reproducible and I figured out why,
It seems that the issue was caused by https://github.com/ivpn/desktop-app/issues/142 which was re-opened recently and fixed, so the problem was not actually that the VPN wasn't connecting to the last port, but it wasn't re-connecting when changing ports.

**Comment by stenya** [comment]
v3.9.43
