### ISSUE TITLE
(Linux) Add "which" as dependency for "ivpn" AUR package

### ISSUE THREAD

**Issue by jordan-ivpn** [ivpn/desktop-app#205]
# Bug report

## Describe your environment

* OS name and version: ___Arch__  
* IVPN app version: __3.9.14___  

## Describe the problem

A customer reported an issue with the split tunnel feature throwing an error on `ivpn splittun -status`.  The `sudo /opt/ivpn/etc/splittun.sh test` command indicated that `iptables` was not installed even though it was.  Further investigation revealed that `zsh` uses a built-in for `which`.  Installing the `which` package resolved the issue.

https://aur.archlinux.org/packages/ivpn

Thanks.

**Comment by stenya** [comment]
Removed usage `which ...` from scripts.
Now, we use `command -v ...` instead (a safer POSIX-compatible way to check binary availability).

@gorkapernas 
Changed scripts:
- splittun.sh - (testing ST functionality availability). Required simple regression tests on different distributives:  the ST functionality must not disappear 
- DEB/RPM installer: after-install.sh, after-remove.sh - (testing accessibility of systemctl command). Required simple regression tests on different distributives: the daemon must be successfully installed after install

**Comment by stenya** [comment]
v3.9.38

**Comment by gorkapernas** [comment]
Verified with v3.9.40, 3.9.41, installed IVPN, run regression tests and tested availability of Split Tunnel on different Linux distributions, no issues found.

**Comment by stenya** [comment]
v3.9.43
