### ISSUE TITLE
Uninstalling app does not remove custom CLI settings

### ISSUE THREAD

**Issue by gorkapernas** [ivpn/desktop-app#206]
### Description:
When uninstalling the app, the custom configuration from the CLI i.e. DNS, AntiTracker etc, are not reset to default, so the next time the app is installed, the previous CLI settings are remembered.

### Expected result:
The CLI settings should be removed when uninstalling the app or when logging out with the option "Reset application settings to default" checked.

### Environment:
IVPN: 3.9.8
OS: All Platforms

**Comment by stenya** [comment]
fix: https://github.com/ivpn/desktop-app/commit/f8e176997a225fcdb46278d383351c7306cd1c5c

**Comment by stenya** [comment]
v3.9.29

**Comment by gorkapernas** [comment]
Verified fixed in v3.9.29, all platforms, the CLI custom settings are removed when uninstalling the app.
This is good to go.

**Comment by stenya** [comment]
Released in v3.9.32
