### ISSUE TITLE
Hi there, I have issue here, when I open on my Windows 11 Pro IVPN client, it shows always: "Error connecting to IVPN daemon

### ISSUE THREAD

**Issue by Endless33** [ivpn/desktop-app#207]
# Bug report

## Hi there, I have issue here, when I open on my Windows 11 Pro IVPN client, it shows always: "Error connecting to IVPN daemon

* Device: PC
* OS name and version: Windows 11 Pro Original
* IVPN app version: Latest 3.9
## Hi there, I have issue here, when I open on my Windows 11 Pro IVPN client, it shows always: "Error connecting to IVPN daemon, not connected to daemon. Please ensure IVPN daemon is running and try to reconnect.

Well I have paid, and on my android phone is working fine, but on the PC began not working. I deleted it, reinstall it, anyway same error, I tried to close with Task Manager, and searched in google, but the issue still there. Please fix it for Windows 11 64 bit, Thanks!

### Steps to reproduce:

1. Before was working fine, I don't know what's happened.
2. _____
3. _____

### Observed Results:

* What happened? This could be a description, log output, etc.  

### Expected Results:

* What did you expect to happen?  

### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by stenya** [comment]
Hi @Endless33
So far, we have not received any feedback on issues related to Windows 11.

Anyway, we released a new IVPN app version (v3.9.32) which contains a potential fix for the issue you described. Can you, please, try it?

I will be gratеаul for any feedback from you. Does the issue still persist after the upgrade?

**Comment by Endless33** [comment]
Still not fixed the problem with program. Waste of $ It works normal only on Android, but not on my pc or laptop with original Windows 11 Pro. So what is the point for using it then? It's okay I paid only for one or two months, what would happened if I would pay them a one year subscription. Liar said they have no problems with Windows 11, but would I lie to them? How could he answer to me like that? What kind of service is that? I can even show a screenshoot if they like. Will look for another multi vpn servers for better service and conditions. Months later after this crash, they released few new versions, where the problem still persist. Shame vpn server ever.. Are you testing it on Windows at all before release? Hm, I guess no.

**Comment by johnnyburnaway** [comment]
@Endless33 Yes, we test our app on all platforms, and have quality assurance processes that include testing on Windows 11. Problems and bugs happen, and it looks like you are unlucky in this regard that you encountered a bug that we were not able to solve promptly. Sorry.

To answer your question "what would happen if you bought a one year subscription" - if customers have unsolvable technical issues that prevent them from using our service, we issue refunds. This does not happen very often, but is offered to you in this situation. Please write to support@ivpn.net and refer to this thread.

Finally, I'd like to ask you to be respectful in this space. Calling us liars, and our service "a shame VPN" is disrespectful, and is no way to get our attention. We have a professional, diligent team who cares about their job and tries to ensure our apps work for all customers without errors. This is not possible in all cases, at all times and mistakes happen. Let's discuss them here without name calling.

**Comment by Endless33** [comment]
> @Endless33 Yes, we test our app on all platforms, and have quality assurance processes that include testing on Windows 11. Problems and bugs happen, and it looks like you are unlucky in this regard that you encountered a bug that we were not able to solve promptly. Sorry.
> 
> To answer your question "what would happen if you bought a one year subscription" - if customers have unsolvable technical issues that prevent them from using our service, we issue refunds. This does not happen very often, but is offered to you in this situation. Please write to support@ivpn.net and refer to this thread.
> 
> Finally, I'd like to ask you to be respectful in this space. Calling us liars, and our service "a shame VPN" is disrespectful, and is no way to get our attention. We have a professional, diligent team who cares about their job and tries to ensure our apps work for all customers without errors. This is not possible in all cases, at all times and mistakes happen. Let's discuss them here without name calling. 

Well, maybe it works for someone, but would you be ok when using app, it works, and after few moments it doesnt work. If I say problem occurs, you as creators better research the error, because Im not the one who gets it. And secondly nobody is using "bad" names about your vpn. I have for example no probpems with hydemyname vpn, why? Maybe because they cool, and your conpany is getting less popular? Yes, it have two layers of security, but its not stable.

**Comment by johnnyburnaway** [comment]
Since you are demonstrating the same type of communication towards us as the OP - or you are the same person, we will never know - I have the same response. If you can address us with respect, we will respond with respect. If you call us thieves and repeat clear lies ("IVPN doesn't want to fix things" with hundreds of fixes pushed out via releases in the past years?), you will be ignored.

For future reference: as we indicated earlier, if a customer faces unsolvable technical issues like the above after signing up for IVPN, we issue refunds promptly.

**Comment by johnnyburnaway** [comment]
Email support at ivpn.net, refer to this thread and you will receive a pro-rated refund. Once you do, please give us an update.

**Comment by benjamasu** [comment]
Maybe it has something to do with Windows 11 Pro security policies (like Smart App Control) or security mitigations that IVPN is incompatible with. I was only able to prevent daemon from running by explicitly enabling some strict mitigations, but they are not enabled by default and need to be enabled on a per-application basis. IVPN is compatible with almost all (if not all) system-wide mitigations out of the box.
