### ISSUE TITLE
`obfsproxy` disabled after changing the protocol to WireGuard and connecting 

### ISSUE THREAD

**Issue by gorkapernas** [ivpn/desktop-app#209]
### Description:
On version 3.9.32, all platforms, when enabling `obfsproxy` with OpenVPN, if the user changes the protocol to WireGuard and connects, and then changes back to OpenVPN, `obfsproxy` will be disabled.

### Expected result:
`obfsproxy` should not be disabled regardless if the user changes the protocol and connects.

### Steps to reproduce:
1. Install 3.9.32 on any platform.
2. Login.
3. Select OpenVPN.
4. Enable `obfsproxy`
5. Select WireGuard.
6. Connect.
7. Disconnect.
8. Select OpenVPN.
9. Observe that `obfsproxy` is disabled.

### Environment:
IVPN: 3.9.32
OS: All platforms

**Comment by stenya** [comment]
This is not an issue anymore starting from beta v3.9.34 (https://github.com/ivpn/desktop-app-shadow/issues/83)

**Comment by gorkapernas** [comment]
Verified fixed on beta v3.9.34, the issue no longer occurs, `obfsproxy` remains enabled.

**Comment by stenya** [comment]
v3.9.43
