### ISSUE TITLE
UI: unable to reconnect to a new server using servers list (in 'connecting' stage)

### ISSUE THREAD

**Issue by stenya** [ivpn/desktop-app#210]
# Bug report

### Steps to reproduce:

1. Choose OpenVPN (because it takes more time to connect)
2. Press the "Connect" button to connect to server X
3. (quickly; until app not established connection to server X) enter server list and choose a new server (Y)

### Observed Results:

App connected to server X

### Expected Results:

App connected to server Y

**Comment by gorkapernas** [comment]
Verified on v3.9.35, all platforms, the issue no longer occurs, the app always connect to the server selected last.

**Comment by stenya** [comment]
v3.9.43
