### ISSUE TITLE
Expired account allows WireGuard to "connect"

### ISSUE THREAD

**Issue by jordan-ivpn** [ivpn/desktop-app#212]
# Bug report

## Describe your environment

* Device: _____  
* OS name and version: _Win10_&_Arch Linux__  
* IVPN app version: __3.9.32___  

## Describe the problem

If WireGuard is selected and the Account ID is **Not Active** (Your subscription has expired), toggling the connect switch results in a "connection".  The app shows connected, but Internet access is blocked.

### Steps to reproduce:

1. Log in to the IVPN with an expired account or let an account expire while it is logged in to the app.
2. Choose WireGuard and connect.
3. Check for Internet connectivity.

### Observed Results:

The app appears to be connected, but there is no Internet access.  Pinging 172.16.0.1 yields no replies.

### Expected Results:

The connection process should not be allowed to proceed if the account is expired.  A WireGuard "connection" is less of a connection and more of an active state, so if there was an account status check to permit or deny the connection attempt to proceed or if an error message with an account status message is presented, this may offer a friendlier experience.

If OpenVPN is selected, there is an **auth** failure.  It would be nice if there was a message about how the account status is the cause of the auth failure.

Thanks.

**Comment by stenya** [comment]
Done.

Before the connection start (_only if the IVPN client knows that account is not active or expired_), the daemon is requesting actual account info from the backend.

If the request failed (_e.g. no connectivity_): everything works as before... daemon is trying to start a VPN connection.

If the request success and the actual account status is 'not active', a user will be informed about the connection error: `Your subscription has expired` (or `Your subscription not active` for users with wrongly configured local time)

**Comment by stenya** [comment]
v3.9.51

**Comment by gorkapernas** [comment]
Verified fixed on version 3.9.51, tested in all platforms, on the CLI and GUI, and with both protocols WireGuard and OpenVPN, when the account is expired, it is not possible to establish any type of connection, as soon as the user attempts to connect the following error appears:
<img width="417" alt="expired account" src="https://user-images.githubusercontent.com/16647612/202427434-58a497de-4df2-4b07-8e1d-aaa7d1e4fd9c.png">
The same error appears if trying to connect via CLI.

**Comment by stenya** [comment]
Released in [v3.10.0 Beta](https://github.com/ivpn/desktop-app/releases/tag/v3.10.0)
