### ISSUE TITLE
Migrate to Electron to v21.x.x

### ISSUE THREAD

**Issue by stenya** [ivpn/desktop-app#213]
# Feature request

Electron 18.x.y has reached end-of-support as per the project's [support policy](https://www.electronjs.org/docs/latest/tutorial/electron-timelines#version-support-policy). Developers and applications are encouraged to upgrade to a newer version of Electron.

**Comment by stenya** [comment]
Changes: 'Show application in system dock' is not applicable anymore on Linux (due to Electron restrictions)
This configuration parameter was removed from the App settings on the Linux platform.

**Comment by stenya** [comment]
v3.9.40

**Comment by gorkapernas** [comment]
Verified on v3.9.40, "show application in system dock" is no longer shown on Linux distributions, tested with clean installation and after an update. 
I have also run a sanity on different platforms without encountering any issues.

**Comment by stenya** [comment]
v3.9.43
