### ISSUE TITLE
VPN killswitch does not work with Qubes OS ProxyVM -> AppVM setup

### ISSUE THREAD

**Issue by tommytran732** [ivpn/desktop-app#217]
# Bug report

## Describe your environment

* OS name and version: Qubes OS 4.1 host, Fedora 36 guests
* IVPN app version: v3.9.32

## Describe the problem

The VPN Killswitch does not work with Qubes OS ProxyVM -> AppVM setup, leading to potential IP Leakage if the VPN tunnel stops working.

### Steps to reproduce:

1. Setup a ProxyVM and AppVM on Qubes OS. Enable the killswitch, connect to the VPN and make sure that both VMs can connect to the internet normally.
2. Disconnect the VPN

### Observed Results:

* The ProxyVM cannot connect to the internet, however the AppVM can connect to the internet directly through the ProxyVM.

### Expected Results:

* Both VMs should not be able to connect to anything but IVPN's servers.

**Comment by stenya** [comment]
Updated rules for the FORWARD firewall chain. 
Now IVPN firewall blocks all routed packets except the packets going to/from the VPN interface.

Note! Do not forget to enable "Always-on firewall" in app settings to keep the firewall enabled when VPN is disconnected.

The update will be included in the next official release.

**Comment by stenya** [comment]
v3.10.5 is ready for testing

**Comment by gorkapernas** [comment]
The issue should be fixed in the last beta version 3.10.11.
I've run a sanity on different Linux distributions to make sure there wasn't any regression issues. This is good to go.

**Comment by stenya** [comment]
v3.10.14 released
