### ISSUE TITLE
Unable to send diagnostic logs

### ISSUE THREAD

**Issue by stenya** [ivpn/desktop-app#221]
# Bug report

## Describe your environment

* IVPN app version: v3.9.43

## Describe the problem

Pressing the button "Send logs" does not start any action. 
As the result: logs were not sent.

**Comment by gorkapernas** [comment]
Verified fixed on beta 3.9.45, all platforms, it is possible again to send the diagnostic logs.

**Comment by stenya** [comment]
Released in v3.9.45
