### ISSUE TITLE
(Linux) Feature request: Detect 'insecure' WiFi networks 

### ISSUE THREAD

**Issue by stenya** [ivpn/desktop-app#222]
# Feature request

IVPN clients for macOS and Windows have the function 'Autoconnect when joining insecure WiFi networks.
The Linux version of the IVPN client is missing this function.

**Comment by stenya** [comment]
v3.9.51

**Comment by gorkapernas** [comment]
Verified on version 3.9.51, different Linux distributions, the option to autoconnect when joining insecure WIFI networks has been added and works as expected, this option can be found in the WIFI settings screen.

**Comment by stenya** [comment]
Released in [v3.10.0 Beta](https://github.com/ivpn/desktop-app/releases/tag/v3.10.0)
