### ISSUE TITLE
IPv6 inside WireGuard tunnel

### ISSUE THREAD

**Issue by gorkapernas** [ivpn/desktop-app#23]
Allow users access to the IPv6 internet after they connect to the WireGuard VPN.

In current clients, WireGuard `[Interface]` is only configured with IPv4 address.By adding IPv6 address in the client config, VPN tunnel will have IPv6 traffic as well, when connected to gateway which support IPv6.

Example client config:
```
[Interface]
Address = 192.0.2.0,2001:0db8:0:0::2001:0db8/64
ListenPort = 51820
PrivateKey = <PrivateKey>
DNS = 198.51.100.0

[Peer]
PublicKey = <PublicKey>
AllowedIPs = 0.0.0.0/0,::/0
Endpoint = 203.0.113.0:2049
PersistentKeepalive = 25
```

There should be an option in the app settings that enables IPv6 inside VPN tunnel, which is off by

**Comment by gorkapernas** [comment]
Verified on version 3.3.16-17 staging and production.
Platforms -> Windows 10, macOS Catalina 10.15.7/BigSur 11.4 M1 Chip, Linux Ubuntu 20.04, Fedora 32.

When enabling "IPv6 for WireGuard VPN", the VPN tunnel will also have IPv6 traffic when connecting to a server, tested with all servers which support IPv6.

There was an issue resolving IPv6 DNS addresses with certain macOS browsers (Firefox and Safari more precisely) which could not detect IPv6 when connected to the VPN, but this issue is resolved in the latest version, so now  I am able to access IPv6 hosts on all browsers AND platforms.

This only works with WireGuard, once the protocol is changed, only IPv4 traffic will be used.

Also tested WireGuard connectivity (along with different settings, custom DNS, AntiTracker etc) without encountering any obvious issue related to these changes.

**Comment by stenya** [comment]
v3.3.20 is released.
[Changelog](https://github.com/ivpn/desktop-app/blob/master/CHANGELOG.md)
