### ISSUE TITLE
Hi @Endless33

### ISSUE THREAD

**Issue by Endless33** [ivpn/desktop-app#230]
Hi @Endless33
So far, we have not received any feedback on issues related to Windows 11.

Anyway, we released a new IVPN app version (v3.9.32) which contains a potential fix for the issue you described. Can you, please, try it?

I will be gratеаul for any feedback from you. Does the issue still persist after the upgrade?

_Originally posted by @stenya in https://github.com/ivpn/desktop-app/issues/207#issuecomment-1263224432_

**Comment by Endless33** [comment]
Still not fix the problem with program, waste of $$$

**Comment by jurajhilje** [comment]
Duplicate of #207
