### ISSUE TITLE
[Feature Request] List of anti-trackers.

### ISSUE THREAD

**Issue by teksignal** [ivpn/desktop-app#238]
It would be nice to have a list of anti trackers to choose from to be more flexible in ad/trackers blocking. For now there is an only option with "OISD" running implicitly with the optional "hardcore" toggle.
It doesn't cover some edge cases, it's more like a general filter to satisfy the most people using it.
It would be 2x nicer to have a possibility to add own anti-tracker lists by url with some update interval.

**Comment by johnnyburnaway** [comment]
Improvements to our AntiTracker is on our roadmap for the next 6 months. Own lists might not happen, but more customisation options definitely will feature.

**Comment by stenya** [comment]
Functionality implemented in latest versions of IVPN Client.

https://www.ivpn.net/blog/better-tracker-blocking-controls-with-antitracker-plus/
