### ISSUE TITLE
Letting the installer add CLI to path wiped all other PATH entries

### ISSUE THREAD

**Issue by tate56** [ivpn/desktop-app#239]
The only entry left is the ivpn one. Super frustrating

**Comment by tate56** [comment]
If this happens to you, use Process Explorer to grab the path from a running application.

**Comment by stenya** [comment]
@tate56 could you share more information with us? The operating system you are using, the application version...etc.
The problem you reported is very strange. We have not received such complaints before.

**Comment by jordan-ivpn** [comment]
There have been two or three other reports of this issue.  The IVPN App's CLI PATH does not include `%system32%` and some malicious agent that might exist in a system seems to wipe out any PATH entry that refers to `%system32%`.  The IVPN App remains in the PATH, so an assumption is that the IVPN App is causing the issue, though it is not involved.

**Comment by stenya** [comment]
I will double-check the installer sources.

**Comment by stenya** [comment]
I did check the installer sources. No issues were found.
I believe it is not an IVPN App issue. There is no way for the installer to wipe out the PATH variable.

I am closing the ticket. Feel free to reopen it (if required).

**Comment by stenya** [comment]
The issue has been confirmed. I am currently working on a fix. Ticket: https://github.com/ivpn/desktop-app/issues/262
