### ISSUE TITLE
Show gateways without IPv6 support

### ISSUE THREAD

**Issue by gorkapernas** [ivpn/desktop-app#24]
This setting should be disabled (or hidden) and on by default.

When user enabled IPv6 for VPN tunnel, this setting should became visible. 

When both "Enable IPv4" and "Show gateways without IPv6 support" are enabled, on the servers list there should be "IPv6" label next to servers that support IPv6.

**Comment by gorkapernas** [comment]
Verified on version 3.3.13, all platforms, during my last testing round I noticed that the option was hidden, but OFF by default, however, according to the requirements, the option should be hidden (or disabled) + ON by default.

Please change this accordingly.

**Comment by stenya** [comment]
@gorkapernas beta version v3.3.14

**Comment by gorkapernas** [comment]
Verified on version 3.3.16-17 staging and production.
Platforms -> Windows 10, macOS Catalina 10.15.7/BigSur 11.4 M1 Chip, Linux Ubuntu 20.04, Fedora 32
The issue reported in my previous comment has been fixed.
Currently when enabling "show servers without IPv6 support", the label `ipv6` is shown next to the server that supports IPv6 in the list of servers. If the server doesn't support IPv6, the label is not shown. This only applies to WireGuard servers and when "IPv6 for WireGuard VPN" is also enabled.
