### ISSUE TITLE
[bug] (Linux) Changing "DNS -> Force management of DNS using resolve.conf" has no effect until reboot

### ISSUE THREAD

**Issue by stenya** [ivpn/desktop-app#240]
# Bug report

## Describe your environment

* OS name and version: Linux
* IVPN app version: 3.10.0

## Describe the problem

Changing the settings option "DNS -> Force management of DNS using resolve.conf" has no effect until reboot.
This is the regression of v3.10.0.
Related Issue: https://github.com/ivpn/desktop-app/issues/191

### Steps to reproduce:

1. Change the value "DNS -> Force management of DNS using resolve.conf" 
2. Connect VPN

### Observed Results:

Changing this option has no effect until the daemon restart.

### Expected Results:

Changing this option must affect the next VPN connection.

**Comment by stenya** [comment]
v3.10.5 is ready for testing

**Comment by gorkapernas** [comment]
Verified fixed on v3.10.5, different Linux platforms, the issue no longer occurs, enabling the option `Force management of DNS using resolve.conf` works when connecting to the VPN, there is no need to reboot the machine after the option is enabled.

**Comment by stenya** [comment]
v3.10.14 released
