### ISSUE TITLE
Why is Discord a dependency for ivpn?

### ISSUE THREAD

**Issue by SubGlitch1** [ivpn/desktop-app#241]
Its not a Bug more of a question.
Why is Discord a dependency for ivpn??
i am very confused as to why this would be a dependency.

* Architecture: x64_86  
* OS name and version:  Arch Linux 6.1.4
* IVPN app version: 3.10.0  

1. downloaded the .deb package for the latest version.
2. Tapped it with debtap to create a .zst and then installed it with pacman which stated discord as a dependency.
I also cannot uninstall discord now without ivpn breaking.

**Comment by stenya** [comment]
Hi @SubGlitch1  
there is no dependency on the package you mentioned.

```
$ dpkg -I ivpn_3.10.0_amd64.deb 
 new Debian package, version 2.0.
 size 10361004 bytes: control archive=3824 bytes.
     348 bytes,    13 lines      control              
    2401 bytes,    29 lines      md5sums              
    3705 bytes,   104 lines   *  postinst             #!/bin/sh
    2819 bytes,    84 lines   *  postrm               #!/bin/sh
    2027 bytes,    49 lines   *  preinst              #!/bin/sh
     846 bytes,    26 lines   *  prerm                #!/bin/sh
 Package: ivpn
 Version: 3.10.0
 License: GNU GPL3
 Vendor: Privatus Limited
 Architecture: amd64
 Maintainer: Privatus Limited
 Installed-Size: 24602
 Depends: openvpn
 Section: default
 Priority: extra
 Homepage: https://www.ivpn.net
 Description: Client for IVPN service (https://www.ivpn.net)
  Command line interface v3.10.0. Try 'ivpn' from command line.
```
```
$ dpkg -I ivpn-ui_3.10.0_amd64.deb 
 new Debian package, version 2.0.
 size 92345586 bytes: control archive=3826 bytes.
     319 bytes,    13 lines      control              
    5075 bytes,    77 lines      md5sums              
     494 bytes,    13 lines   *  postinst             #!/bin/sh
    2487 bytes,    74 lines   *  postrm               #!/bin/sh
      58 bytes,     3 lines   *  preinst              #!/bin/sh
      57 bytes,     3 lines   *  prerm                #!/bin/sh
 Package: ivpn-ui
 Version: 3.10.0
 License: GNU GPL3
 Vendor: Privatus Limited
 Architecture: amd64
 Maintainer: Privatus Limited
 Installed-Size: 230352
 Depends: ivpn
 Section: default
 Priority: extra
 Homepage: https://www.ivpn.net
 Description: UI client for IVPN service (https://www.ivpn.net)
  Graphical interface v3.10.0.
```
```
$ sha256sum *
cae1e13e04dfc8c721d2adcb9712d99db443701cede02cc9b44ba349c1559cbf  ivpn_3.10.0_amd64.deb
7acf5f2bf32d0fdf0d0bfdd92b700deb4e20af54d9caab571bef86172ae7a77e  ivpn-ui_3.10.0_amd64.deb
```

As you can see, our .deb packages have minimal dependencies:
- the base package (`ivpn_3.10.0_amd64.deb`) has only dependency on `openvpn`.
- GUI (`ivpn-ui_3.10.0_amd64.deb`) has only dependency on `ivpn` (the IVPN base package)

Please, ensure you downloaded the official binaries!!!
[ivpn_3.10.0_amd64.deb](https://repo.ivpn.net/stable/pool/ivpn_3.10.0_amd64.deb)
SHA256: cae1e13e04dfc8c721d2adcb9712d99db443701cede02cc9b44ba349c1559cbf
[ivpn-ui_3.10.0_amd64.deb](https://repo.ivpn.net/stable/pool/ivpn-ui_3.10.0_amd64.deb)
SHA256: 7acf5f2bf32d0fdf0d0bfdd92b700deb4e20af54d9caab571bef86172ae7a77e

**Comment by stenya** [comment]
Just FYI: the official IVPN packages are also available on AUR.
https://aur.archlinux.org/packages/ivpn-ui
https://aur.archlinux.org/packages/ivpn
