### ISSUE TITLE
(Linux) Build fails from AUR if servers.json cannot be retrived

### ISSUE THREAD

**Issue by jordan-ivpn** [ivpn/desktop-app#242]
# Bug report

## Describe your environment

* Device: _____  
* OS name and version: ___Arch, Manjaro__  
* IVPN app version: _____  

## Describe the problem

The build process from AUR retrieves the current `servers.json` file.  If a network restriction blocks access to api.ivpn.net, the build fails.

An improvement might be to bundle `servers.json` with the source just in case it cannot be retrieved over the network.

A different improvement might be to hardcode the api.ivpn.net IP addresses and failover in case `servers.json` is inaccessible using the hostname.

An alternative improvement might be to host `servers.json` on GitHub or on some other domain for when api.ivpn.net is not available, though this likely involves some backend or infrastructure support.

Thanks.

**Comment by stenya** [comment]
AUR updated:
https://aur.archlinux.org/cgit/aur.git/commit/?h=ivpn&id=822f3a09f0c4851718ce15f7879c4b48d21b72fe

The `servers.json` is already bundled into the GitHub repository. The bundled version will be used in case of failure to download the latest version of `servers.json`.

The change will start work after the next official ivpn version is released.

**Comment by stenya** [comment]
v3.10.14 released
