### ISSUE TITLE
UI: Client icon changes with different icon sizes

### ISSUE THREAD

**Issue by asdrubalejobs** [ivpn/desktop-app#245]
# Bug report

## Describe your environment

Windows 11, latest IVPN client stable release

## Describe the problem

On Windows, just set the icon size to small in a folder or on the desktop and the IVPN Client icon changes to a different one. This different icon is also different from the one shown in the taskbar when the client is running and makes the client look incoherent

### Steps to reproduce:

1. Put the IVPN Client shortcut in a folder
2. Change the icons' size to small

**Comment by stenya** [comment]
This is expected behavior because it is not possible to fit the original logo on small icons.
