### ISSUE TITLE
UI: "scroll" button does not shows/hide as expected when switching to/from Favorites

### ISSUE THREAD

**Issue by stenya** [ivpn/desktop-app#246]
# Bug report

## Describe your environment

![Screen Recording 2023-01-25 at 01 18 59 10 PM](https://user-images.githubusercontent.com/7881006/214550493-258fbbd6-8cb4-43f1-9034-983e1258facb.gif)

**Comment by stenya** [comment]
v3.10.8

**Comment by gorkapernas** [comment]
Verified fixed on v3.10.8, the issue with scroll button no longer occurs.

**Comment by stenya** [comment]
v3.10.14 released
