### ISSUE TITLE
(macOS) System still uses IVPN DNS when disconnecting from VPN while changing networks

### ISSUE THREAD

**Issue by gorkapernas** [ivpn/desktop-app#249]
### Description:
When changing networks, if the user disconnects manually from the VPN while the system is connecting to the new network, once the connection is established, the system will still use the IVPN DNS, even though the VPN is disconnected, and consequently internet browsing won't be possible.

### Expected result:
Regardless if the user is changing networks, every time the VPN is disconnected, the system should use the ISP DNS as expected.

### Steps to reproduce:
1. IVPN - connect with WireGuard
2. System - Change to another WIFI network
3. While the system is connecting to the new network, disconnect manually from IVPN
4. After the system connects to the new network, observe that the system still uses the IVPN DNS (`scutil --dns`), but the VPN is disconnected (FW is also disabled), consequently it isn't possible to browse

### Environment:
IVPN: Beta 3.10.10
Platform: macOS Catalina 10.15.7, Mojave 10.14

**Comment by stenya** [comment]
v3.10.11

**Comment by gorkapernas** [comment]
Verified fixed on v3.10.11, tested on different macOS versions, the issue no longer occurs.

**Comment by stenya** [comment]
v3.10.14 released
