### ISSUE TITLE
Switching from MultiHop to SingleHop, changes the port to UDP 53

### ISSUE THREAD

**Issue by gorkapernas** [ivpn/desktop-app#250]
### Description:
When connecting with MultiHop and afterwards when switching to SingleHop, the app will always change the selected port to UDP 53. The issue happens with both protocols, OpenVPN and WireGuard.

### Expected result:
The app should remember the port selected when switching from MultiHop to SingleHop.

### Steps to reproduce:
1. Install version 3.10.0 on any platform.
2. Login.
3. Observe that the default port is UDP 2049.
4. Select MultiHop and connect.
5. Disconnect and select SingleHop.
6. Observe that the port changed to UDP 53.

### Environment:
IVPN: 3.10.0
OS: All platforms

**Comment by stenya** [comment]
v3.10.12

**Comment by gorkapernas** [comment]
Verified fixed on v3.10.12, all platforms, the issue no longer occurs, the app remembers the port selected after switching from MultiHop to SingleHop.

**Comment by stenya** [comment]
v3.10.14 is released
