### ISSUE TITLE
(Linux) Resuming IVPN connection after briefly losing the system's connectivity will block the internet traffic

### ISSUE THREAD

**Issue by gorkapernas** [ivpn/desktop-app#251]
### Description:
With OpenVPN + AntiTracker (or custom DNS), when the IVPN connection is paused and the system briefly loses connectivity (turn off WIFI and turn it on after a minute), OpenVPN will detect that the connectivity loss and will try to reconnect, after the reconnecting the VPN successfully (at this moment the connection button disappears), the IVPN firewall will block the AntiTracker (or custom DNS) requests, consequently the internet traffic will be blocked.

### Actual result:
DNS requests (AntiTracker or custom DNS) are blocked by the VPN Firewall because it allows only 'default' IVPN DNS.

### Expected result:
 IVPN Firewall configured to allow AntiTracker or custom DNS requests.

### Steps to reproduce:
1. Connect: OpenVPN + AntiTracker (or custom DNS).
2. Pause the connection.
3. Disable the system connectivity (e.g. turn-off WiFi).
4. Wait 30-40 seconds... (OpenVPN will detect that connectivity is broken and will try to reconnect).
5. Enable connectivity (turn-on WiFi) and wait until OpenVPN finishes reconnection ('connecting' circle disappears in the UI).
6. Resume the connection.

### Environment:
IVPN: 3.10.0 and beta 3.10.11.
OS: Linux

**Comment by stenya** [comment]
v3.10.12

**Comment by gorkapernas** [comment]
Verified fixed on v3.10.12, different Linux distros, the issue no longer occurs.
AntiTracker and custom DNS requests are not blocked after briefly losing network connectivity, everything work as expected. This is good to go.

**Comment by stenya** [comment]
v3.10.14 is released

**Comment by zpeterg** [comment]
This appears to be an issue still on 3.10.15/daemon 3.10.14:

Solution that seems to work: Check-box the `Force management of DNS using resolv.conf` option.

**Comment by stenya** [comment]
@zpeterg Can you please provide us with information about a Linux distribution and its version, where you are observing the issue?
