### ISSUE TITLE
DNS-over-https under iVPN ( on windows ) not working, but working on macos

### ISSUE THREAD

**Issue by ajay-gh** [ivpn/desktop-app#253]
# Bug report

## Describe your environment

* Device: windows laptop
* OS name and version: win10, latest updates
* IVPN app version: 3.9.32 for windows

## Describe the problem

I've been testing the nextdns service (see nextdns.io)  together with iVPN (on a mac) and it works flawlessly (settings under  "custom dns"). Using exactly the same settings and account for nextdns with iVPN (on win10) does not work at all. All network connections are blocked without any error etc. In both cases I have ensured that the settings are identical AND that anti-tracker is OFF.

### Steps to reproduce:

1. setup a nextdns user account, 
2. try using it on a mac (with iVPN 3.9.45), confirm everything works as expected
3. try exactly the same settings in iVPN on a win10 device (my guess same results under win11)
4. confirm network access is fine when anti-tracker is ON (which bypasses the custom DNS)
5. next turn Anti-tracker OFF, iVPN should now perform DNS queries over https

### Observed Results:

* What happened? see above

### Expected Results:

* What did you expect to happen?  same results under win and under mac, if iVPN works as expected

### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by stenya** [comment]
@ajay-gh I do not see any issues with NextDNS DoH on Windows.
Using the official NextDNS parameters (45.90.28.0 + https://dns.nextdns.io/bb1bca) works correctly on Windows 10/11.
I have checked IVPN v3.9.32 and the latest version, v3.10.15.

I am closing the ticket.

If you still have problems with it, feel free to reopen it.
And, please, provide us with the application logs:
1. Enable logging (Settings -> General -> Allow logging)
2. Reproduce the issue (connect to VPN with configured DoH)
3. Disconnect + Send logs to us (Settings -> General -> Diagnostic logs ...)
