### ISSUE TITLE
(Linux) Split Tunneling issue on Fedora Silverblue

### ISSUE THREAD

**Issue by stenya** [ivpn/desktop-app#255]
@gorkapernas @stenya

One report of an error with *Sparrow Wallet*:
> trying to open an app with split tunneling and receiving the following error:
>
> "Failed to enable Split Tunneling: (exit status 2) Error: Egress device not specified."

https://www.sparrowwallet.com/download/

> Operating system: Fedora Silverblue 37
> IVPN UI Client version v3.10.14

I'll start downloading the Silverblue ISO, though it will likely take time to get up so speed with it.  If you have a test system ready to go, it might be easier.  Thanks!

_Originally posted by @jordan-ivpn in https://github.com/ivpn/desktop-app/issues/86#issuecomment-1445238676_

**Comment by jordan-ivpn** [comment]
This issue could not be replicated and the original reporter has indicated that everything is working as expected.

Issue can be **CLOSED**.
