### ISSUE TITLE
Upgrade subscription button unresponsive on device limit screen

### ISSUE THREAD

**Issue by gorkapernas** [ivpn/desktop-app#26]
### Description
In version 3.3.10 (or latest beta, 3.3.12), all platforms, when logging in with a Standard account and reaching the session limit, clicking on the button "Upgrade your subscription" doesn't do anything.

### Expected result:
Clicking on "Upgrade your subscription" should redirect the user to the website - client area.

### Steps to reproduce:
1. On any desktop platform, reach the device limit screen upon login with a Standard account.
2. Click on "Upgrade your subscription"
3. Observe the issue

### Environment:
IVPN: v3.3.10
OS: All Platforms

**Comment by stenya** [comment]
v3.3.20 is released.
[Changelog](https://github.com/ivpn/desktop-app/blob/master/CHANGELOG.md)
