### ISSUE TITLE
Adding IVPN cli to PATH delete all environment variables!!

### ISSUE THREAD

**Issue by m-primo** [ivpn/desktop-app#262]
# Bug report

## Describe your environment

* Device: _____  
* OS name and version: Windows 11 Pro 22H2
* IVPN app version: 3.10.14

## Describe the problem

When installing/updating IVPN desktop app and choosing "Add IVPN cli to PATH" it will remove all your current environment variables (system environment variables not user)

### Steps to reproduce:

1. Install IVPN.
2. Check "Add IVPN cli to PATH" box.
3. Check your system environment variables.. it's gone!!!

### Observed Results:

![Screenshot 2023-03-12 034721](https://user-images.githubusercontent.com/44984918/224519800-ef20190f-f976-4088-a135-83c64200e79f.png)

### Expected Results:

* What did you expect to happen?  

Nothing to be deleted!!

**Comment by stenya** [comment]
Similar issue: https://github.com/ivpn/desktop-app/issues/239

**Comment by m-primo** [comment]
> Similar closed issue: #239

It's not a solution, the issue still persist, and it's from IVPN itself, not "malicious agent".
If it's a "malicious agent" it wouldn't happen literally after the installation of the IVPN app!!

**Comment by stenya** [comment]
Hi @m-primo 
The linked ticket is just for reference, mainly for myself and other IVPN colleagues. 

In the meantime, could I ask for your help in determining the issue?:
1. Could you please confirm whether the issue occurs every time you install the IVPN app?
2. Would you be able to share the value of your PATH variable before installing the IVPN app?

**Comment by m-primo** [comment]
> 1. Could you please confirm whether the issue occurs every time you install the IVPN app?

I tried twice and it occurred, so yes.


> 2. Would you be able to share the value of your PATH variable before installing the IVPN app?

I have lots of variables so
![Untitled](https://user-images.githubusercontent.com/44984918/225153873-291b5e40-10f1-4d44-a195-3ccad651f04c.png)

**Comment by stenya** [comment]
The issue has been confirmed. To reproduce the issue, the PATH system variable must have a length of more than 1024 bytes. I am currently working on a fix.
@gorkapernas ^^^ FYI

**Comment by gorkapernas** [comment]
Verified fixed on beta 3.10.15, as Stenya mentioned, the installer framework does not allow variables with more than 1024 characters, so currently when installing IVPN and trying to add the CLI to the PATH under such conditions, the installer won't update the PATH and the user will be presented with the following message.
<img width="497" alt="variables issue_warning" src="https://user-images.githubusercontent.com/16647612/228279898-22b5cb13-783a-4ec3-8718-7a5c28305612.png">

**Comment by stenya** [comment]
v3.10.15 is released.

@m-primo Thank you for your help.
