### ISSUE TITLE
WireGuard: Detecting Successful Connection

### ISSUE THREAD

**Issue by stenya** [ivpn/desktop-app#266]
# Feature request

## Description

Currently, there is no detection of connectivity after a WireGuard (WG) connection is established. It immediately switches to a "connected" state after the WG interface is initialized.

**Expected behavior:**
The WG connection should remain in a "connecting" stage until full connectivity is established. After initializing the WG interface, the application should wait for the first WG handshake to ensure a successful connection. This behavior is consistent with OpenVPN, where the connection remains in a "connecting" state until established.

**Comment by stenya** [comment]
v3.10.16

**Comment by gorkapernas** [comment]
Verified on v3.10.16, all platforms, if attempting to connect with WireGuard while there isn't system connectivity, the app will remain on "connecting" state until the system recovers connectivity, after this the app connects to the VPN successfully.
This looks good to go.
