### ISSUE TITLE
[bug] (UI) OpenVPN: paused connection not resuming after defined timeout

### ISSUE THREAD

**Issue by stenya** [ivpn/desktop-app#269]
# Bug report

## Describe your environment

* OS name and version: issue was reproduced on Windows, but it is related to all platforms

### Steps to reproduce:

1. Connect OpenVPN
2. Pause for 5 minutes
3. Disable connectivity (turn off WiFi or enable OS sleep mode)
4. Wait 5+ min
5. Enable connectivity (turn on WiFi)

### Observed Results:

The connection is still paused. But the countdown counter is not visible.

### Expected Results:

Connection resumed.

**Comment by stenya** [comment]
v3.10.16

**Comment by stenya** [comment]
The spinning circle indicates that OpenVPN is in the reconnecting process due to a lack of connectivity being detected. (You can see the message `Connecting to..`" under the selected server.) 
The issue was that the reconnection timeout could take up to 5 minutes (starting from 5 seconds initially and extending to 5 minutes after multiple failed reconnection attempts). Therefore, when the app is in a reconnecting timeout state and connectivity is restored, it may remain in the "reconnecting state" for up to 5 minutes. 

I have updated the OpenVPN reconnection timeouts: the minimum reconnection timeout is now 2 seconds, while the maximum is 6 seconds.

> On a side note, should we also add the "connecting" and "disconnecting" labels to the status?
This is a UX/UI change that requires future discussion (with a designer?).

**Comment by gorkapernas** [comment]
@stenya thanks for the info, I noticed the app was reconnecting after I wrote my comment, so I edited it to point this out.
I'll check again the behavior in the new build and let you know how it goes.

**Comment by stenya** [comment]
v3.10.17

**Comment by gorkapernas** [comment]
Verified fixed on v3.10.17, all platforms, the app now resumes the connection to the VPN successfully after the system connectivity is restored.
