### ISSUE TITLE
Improve speed of server latency check

### ISSUE THREAD

**Issue by stenya** [ivpn/desktop-app#270]
# Feature request

## Description

At present, the latency check for all servers is slow. 
The app doesn't permit simultaneous ping requests, which was limited due to compatibility issues with certain third-party applications on Windows (Malwarebytes) and macOS (Little Snitch). 
However, it appears that the issue no longer persists. Therefore, we can enhance the speed of the latency check.

**Comment by stenya** [comment]
v3.10.16

**Comment by gorkapernas** [comment]
Verified on 3.10.16, all platforms, the application now performs simultaneous ping requests, so normally all latency values are present when the app makes the request i.e. when launching the IVPN UI, when disconnecting from the VPN etc.
The only instance where the latency values are not present in the list of servers is when the app auto-connects to a specific server or with MultiHop after a system boot. An improvement has been requested regarding this, ref -> https://github.com/ivpn/desktop-app/issues/273
