### ISSUE TITLE
(Linux) UI: fee up vertical space on Settings->General

### ISSUE THREAD

**Issue by stenya** [ivpn/desktop-app#271]
# Feature request

## Description
Currently, the description for "Minimize to tray" consumes vertical space. To free up this space, the description can be displayed by pressing the (?) button.

**Comment by stenya** [comment]
Commit:
https://github.com/ivpn/desktop-app/commit/04ad830a3b284971b9b7378de87b165d23e52076

**Comment by stenya** [comment]
@gorkapernas v3.10.16

**Comment by gorkapernas** [comment]
Verified on v3.10.16, different Linux distributions, light and dark mode, the tooltip "?" icon has been added next to the option "Minimize to tray", when clicking on the icon, the description appears correctly.
