### ISSUE TITLE
Split-Tunnel inverse option.

### ISSUE THREAD

**Issue by marknefedov** [ivpn/desktop-app#272]
# Feature request

## Description
It would be great to have option instead of opting-out applications from vpn, opt-in.
I have a certain set of applications that I want to use with vpn and most of the other system and work-related apps do not need vpn, it is very tedious and painful to find all possible executable files to exclude, especially when they spawn more child processes.

## Describe the solution you'd like

Allow to turn split tunneling to opt-in mode.
## Describe alternatives you've considered

Browsers can be mitigated with extensions and proxy, but not all apps I want to pass through support proxy.

**Comment by stenya** [comment]
v3.12.1006

**Comment by v4u6h4n** [comment]
Ah cool, excited for this feature.

**Comment by gorkapernas** [comment]
Inverse Split Tunnel has been tested internally and it should be released soon for Windows and Linux.
Note: It will initially be released as a beta feature.

**Comment by v4u6h4n** [comment]
@gorkapernas Thanks for the update. I don't mind waiting for the official release, but just wondering if there is a beta option for the Linux desktop app? Had a bit of a search and couldn't find it.

**Comment by stenya** [comment]
We do not have beta update channel for Linux app, so there is no option to receive notifications about beta versions.  
Inverse Split Tunneling will be included in the official release as beta functionality for Windows and Linux apps.

**Comment by v4u6h4n** [comment]
Okay, thanks for the heads up.

**Comment by stenya** [comment]
Inverse Split Tunnel mode is now available in the IVPN app v3.13.1 for Windows and Linux.
Please note that this functionality is still in beta.
