### ISSUE TITLE
Disable fastest server when switching to SingleHop

### ISSUE THREAD

**Issue by gorkapernas** [ivpn/desktop-app#273]
### Description:
Currently when connected with MultiHop and switching to SingleHop, if fastest server was selected before, the app will select the fastest server, however, there is an issue if latency values are not present when connected with MultiHop and switching to SingleHop, the app will connect randomly to the first server on the list.

In order to avoid this issue, when connected with MultiHop and switching to SingleHop, the fastest server option should be disabled automatically, so SingleHop connection will be established to the EntryServer used from the MultiHop connection.

**Comment by stenya** [comment]
Changed functionality of fastest server detection:

Now, the app looks for the server with the lowest latency (searching among active servers that have latency info).

However, if there is no latency info for any server:
- use the nearest server (if geolocation info is known)
- else: use the currently selected server (if applicable) **(THIS IS NEW)**
- else: use the first server in the list (as a fallback)

The "FastestServer" selection remains unchanged.

**Comment by gorkapernas** [comment]
@stenya there seems to be an scenario where the application always fallsback to the first server in the list, so far I reproduced it on Windows and Linux, could you please confirm if the following case is correct?

Windows 11 steps:
- Select fastest server
- Connect
- Enable MultiHop (app connects to fastest server as entry_server)
- Enable launch at login and autoconnect
- Reboot machine
- After reboot, observe that the app is connected, but latency values are not present
- Change to SingleHop
- Observe that the app connects to first server in the list (Vienna in my case)

**Comment by stenya** [comment]
@gorkapernas No, the server should remain unchanged.

I can reproduce the issue only when "Allow background daemon to manage autoconnect" is enabled. The issue doesn't occur when this option is disabled. Please confirm if you observe the same behavior.

I am working on a fix...

**Comment by stenya** [comment]
No, the server should remain unchanged.

Investigating ...

**Comment by stenya** [comment]
Fixed. v3.10.20
Good finding @gorkapernas 
Thank you!

**Comment by gorkapernas** [comment]
Verified fixed on v3.10.20 the last issue reported on https://github.com/ivpn/desktop-app/issues/273#issuecomment-1532713439, tested in all platforms, the app does not connect to the first server in the list when changing to SingleHop if the fastest_server is set as the entry_server during the MultiHop connection, it uses the currently selected entry_server for the SingleHop connection.
The new functionality works as described on https://github.com/ivpn/desktop-app/issues/273#issuecomment-1516230171
