### ISSUE TITLE
[Bug] - cutoff text in the fastest server configuration

### ISSUE THREAD

**Issue by gorkapernas** [ivpn/desktop-app#274]
### Description:
When the ISP info of the servers and the IPv6 tag are enabled for WireGuard, it is observed a cutoff text in the fastest server configuration. Some of the larger text strings of the ISP info appear cutoff behind the fastest server configuration toggles.

**Note:**
On macOS seems to be more cutoffs than in the other two OS.

### Expected result:
The text should be displayed correctly.

### Screenshot:
![cutoff issue](https://user-images.githubusercontent.com/16647612/231976847-ba897b62-45d4-486e-9545-f1466179f178.jpg)![cutoff_macOS](https://user-images.githubusercontent.com/16647612/231978609-1b9d616d-e6e6-44e1-9d3c-1cc44774d7d1.jpg)

### Environment:
IVPN: 3.10.15, beta 3.10.16
OS: All platforms

**Comment by stenya** [comment]
v3.10.17

**Comment by gorkapernas** [comment]
Verified fixed on v3.10.17, all platforms, the cutoff issue has been fixed by adding an ellipsis.
