### ISSUE TITLE
Inconsistent Daemon Logging Status After User Interface Restart

### ISSUE THREAD

**Issue by stenya** [ivpn/desktop-app#283]
# Bug report

### Steps to reproduce:

1. UI: disable logging
2. Close UI
3. CLI: `ivpn logging -on`
4. Start UI

### Observed Results:
Daemon logging is not active, logging option is disabled

### Expected Results:
Daemon logging is active, logging option is enabled

**Comment by stenya** [comment]
Commit: https://github.com/ivpn/desktop-app/commit/6773ce20fd93a20d2f4d20b4a9bf3dc940e48016

**Comment by stenya** [comment]
v3.10.24

**Comment by gorkapernas** [comment]
Verified fixed on v3.10.24, tested on all platforms, daemon logs are active and enabled as expected.

**Comment by stenya** [comment]
v3.11.5
