### ISSUE TITLE
[bug] WG: Switching servers from the GUI is not possible during the "initializing" state

### ISSUE THREAD

**Issue by stenya** [ivpn/desktop-app#284]
# Bug report

## Describe your environment

* IVPN app version: v3.10.23

### Steps to reproduce:

1. Disable connectivity (e.g. disable WiFi)
2. Initiate a WireGuard connection to server X -> UI displays "connecting..."
3. Change the server from the GUI (to server Y).
4. Enable connectivity (enable WiFi)

### Observed Results:

WireGuard connects to server X (the GUI did not send a "connect" request to the daemon on step 3).

### Expected Results:

WireGuard connects to server Y (the GUI should send a "connect" request to the daemon each time the user changes the server).

**Comment by stenya** [comment]
v3.10.24

**Comment by gorkapernas** [comment]
Verified fixed on v3.10.24, all platforms, the app connects to the last server selected before reestablishing the connectivity.

**Comment by stenya** [comment]
v3.11.5
