### ISSUE TITLE
(Linux) Debian 12 uses nftables and iptables is not installed by default

### ISSUE THREAD

**Issue by jordan-ivpn** [ivpn/desktop-app#286]
# Bug report

## Describe your environment

* Device: _____  
* OS name and version: __Debian 12___  
* IVPN app version: __3.10.23___  

## Describe the problem

Debian 12 uses `nftables` for firewalling.  The `ivpn` app uses `iptables` and the firewall fails:

> failed to change firewall state: failed to execute shell command: exit status 127

One option involves adding `iptables` as a dependency for the `ivpn` package.

The other option involves checking for `iptables`/`nftables` and applying the appropriate set of firewall rules based on which package is installed.

https://www.reddit.com/r/IVPN/comments/14a9t7g/failed_to_change_firewall_state_failed_to_execute/

Thanks.

**Comment by stenya** [comment]
v3.11.16
Updated DEB/RPM 'base' packages: added the strong dependency to 'iptables' package.

@gorkapernas The main danger is that we can not be sure that all Linux distributives have 'iptables' package (exact name) in their official repositories.
There should be no problems with popular distributives (like Ubuntu or Fedora). But it is necessary to test installation process on other distributives we support.

**Comment by stenya** [comment]
v3.12.0 released
