### ISSUE TITLE
Add a "Fastest server" option for multi-hop too

### ISSUE THREAD

**Issue by Thedinotamer** [ivpn/desktop-app#292]
# Feature request

## Description

Just like in Single-hop, there should be a "Fastest server" option so you don't need to check the latency and server load manually, and also like the single-hop equivalent you should be able to configure which servers it can choose from.

**Comment by stenya** [comment]
Hi @Thedinotamer 

The concept of a 'FastestServer' for Single-Hop is easily understandable. However, Multi-Hop involves the use of two servers, which complicates matters.

As such, it's challenging to define the requirements for this functionality. How do you envision the 'FastestServer' feature working for Multi-Hop? 

For instance:
- Should it identify the 'fastest' server for the Entry or the Exit point?
- If we're considering the Exit server, should we select the fastest server relative to your current location, or relative to the Entry server?

**Comment by Thedinotamer** [comment]
Hello @stenya 

> Should it identify the 'fastest' server for the Entry or the Exit point?

My thought was that it would be nice to have one for both the entry and exit servers, but if it's only possible to do one of them then maybe the entry server is the best candidate.

> If we're considering the Exit server, should we select the fastest server relative to your current location, or relative to the Entry server?

I don't know what the "Fastest Server" option in Single-hop bases it's decision on, but wouldn't it be possible to do a mix of both? My reasoning is that if i'm based in Sweden and it chooses based on my location, the "fastest server" will just choose a swedish server which I guess works but I don't think that would be good for privacy (correct me if i'm wrong about that). Instead it would be better if it chose maybe one of the neighbouring countries like Norway, Denmark or Finland.

**Comment by stenya** [comment]
I recently had a discussion with my colleagues. There are many ways to implement this functionality, but it would be challenging to meet every user's expectations regarding the 'FastestServer' behavior for Multi-Hop. Therefore, we don't plan to implement it for now.

However, we do plan to make some improvements concerning the default selection of the Exit server when switching from SingleHop to MultiHop.
