### ISSUE TITLE
(Linux) Split Tunneling error on Fedora Silverblue

### ISSUE THREAD

**Issue by GidCat** [ivpn/desktop-app#295]
# Bug report

## The environment

* Device: LENOVO ThinkPad T440p
* OS name and version: Fedora Linux 38.20230804.0 (Silverblue)  
* IVPN app version: v3.10.23  

### Steps to reproduce:

1. Install [Moonlight](https://moonlight-stream.org/) from [Software](https://wiki.gnome.org/Design/Apps/Software).
2. Launch IVPN
3. Go to _Settings_
4. _Split Tunnel_ tab
5. Check _Split Tunnel (Beta)_
6. Click _Launch application..._
7. Select Moonlight

### Observed Results:

* Disabling IVPN Firewall doesn't seem to change the result.

* Pop up error message upon trying to open Moonlight with the split Tunnel feature: "Failed to enable Split Tunneling: (exit status 2) Error: Egress device not specified." and Moonlight doesn't open.

* App diagnostic logs: `Service log (active session):

Aug  4 19:40:36.742 [log   ] Logging enabled
Aug  4 19:40:36.744 [servc ] (prefs 'enable_logging' changed) true
Aug  4 19:40:36.745 [prtcl ] [-->] 56386 SettingsResp [0] 
Aug  4 19:40:36.745 [prtcl ] [-->] 56386 EmptyResp [64] 
Aug  4 19:40:42.394 [prtcl ] [<--] 56386 GetInstalledApps [65]
Aug  4 19:40:42.524 [prtcl ] [-->] 56386 InstalledAppsResp [65] 
Aug  4 19:40:42.533 [prtcl ] [<--] 56386 SplitTunnelGetStatus [66]
Aug  4 19:40:42.533 [prtcl ] [-->] 56386 SplitTunnelStatus [66] 
Aug  4 19:40:46.249 [prtcl ] [<--] 56386 SplitTunnelAddApp [67]
Aug  4 19:40:46.567 [spltun] ERROR splittun_linux.go:134:(in github.com/ivpn/desktop-app/daemon/splittun.implApplyConfig): failed to enable Split Tunneling: (exit status 2) Error: Egress device not specified.
Aug  4 19:40:46.568 [prtcl ] [-->] 56386 SplitTunnelStatus [0] 
Aug  4 19:40:46.836 [spltun] ERROR splittun_linux.go:134:(in github.com/ivpn/desktop-app/daemon/splittun.implApplyConfig): failed to enable Split Tunneling: (exit status 2) Error: Egress device not specified.
Aug  4 19:40:46.836 [prtcl ] [-->] 56386 SplitTunnelStatus [0] 
Aug  4 19:40:46.836 [prtcl ] ERROR protocol_private.go:174:(in github.com/ivpn/desktop-app/daemon/protocol.(*Protocol).sendErrorResponse): 56386 Error processing request 'SplitTunnelAddApp': failed to enable Split Tunneling: (exit status 2) Error: Egress device not specified.
Aug  4 19:40:46.836 [prtcl ] [-->] 56386 ErrorResp [67] 
Aug  4 19:40:50.854 [prtcl ] [<--] 56386 GenerateDiagnostics [68]`  

### Expected Results:

* The Moonlight application is supposed to launch and not use the VPN.

**Comment by stenya** [comment]
The issue has been fixed in IVPN Client v3.12.0
Duplicate ticket: https://github.com/ivpn/desktop-app/issues/287
