### ISSUE TITLE
[BUG] Check for Updates Failed

### ISSUE THREAD

**Issue by barbiehunter** [ivpn/desktop-app#296]
# Bug report

## Describe your environment

* Device: PC
* OS name and version: _Windows Pro 10 (22H2)
* IVPN app version: 3.11.14

## Describe the problem
When checking IVPN for updates, the "Check for Updates" gives a Failed output.

### Steps to reproduce:

1. Right Click the Tray Icon
2. Click "Check for Updates"
3. Result

### Extra Data:

Screenshot:
![image](https://github.com/ivpn/desktop-app/assets/38357837/883ebd26-404c-4654-aab8-7fee8cb8c6dc)

Video Example:
[SiAkBuYfKM.webm](https://github.com/ivpn/desktop-app/assets/38357837/c748ed2a-8241-400e-8574-e64bc5913242)

### Expected Results:

* What did you expect to happen?  
Gives a message that you have the latest version, and if there is an update you might see the version with changelog
PS: I can't tell if the update check Actually works. When I wanted to update from the beta to today update I got the same error

**Comment by stenya** [comment]
Issue Info: The verification of application updates was disrupted due to missing libraries.

**Comment by stenya** [comment]
@barbiehunter Thank you for the bug report.
This critical issue has been addressed in v3.11.15.
Unfortunately, you'll need to manually update to this version because the update functionality doesn't work in the Windows client v3.11.14 due to the missing libraries.
