### ISSUE TITLE
Apple Silicon support

### ISSUE THREAD

**Issue by ftpmorph** [ivpn/desktop-app#3]
# Feature request

## Description

Native Apple Silicon (ARM) builds for the new M1 Macs and future Apple chips.

## Describe the solution you'd like

Native Apple Silicon builds for your macOS app.

## Describe alternatives you've considered

The app does currently work fine in Rosetta 2, but as Apple is rolling out their ARM chips across all Macs within the next two years max it's a good idea to have native support. A native app should use less power on the machine as well.

P.S. Keep up the good work!

**Comment by postprivee** [comment]
any updates on M1 support?

**Comment by stenya** [comment]
The M1 support is on our to-do list. 
But it is not prioritized yet (because of the low value of the change itself)

**Comment by gorkapernas** [comment]
An IVPN arm binary has been implemented and tested internally. 
A new Apple Sillicon version has been released and can be found in the IVPN website -> https://www.ivpn.net/apps-macos/

**Comment by stenya** [comment]
Released in v3.4.0
