### ISSUE TITLE
[bug] Not initialized Actions for "WiFi control" 

### ISSUE THREAD

**Issue by stenya** [ivpn/desktop-app#301]
# Bug report

## Describe your environment

* IVPN app version: v3.11.15  

## Describe the problem

All default Actions are disabled by default.

### Steps to reproduce:

1. Install the app (clean install) / or LogOut+Reset settings
2. Login

### Observed Results:

Settings -> WiFi control -> Actions: all actions are unchecked

### Expected Results:

Settings -> WiFi control -> Actions: all actions are checked

**Comment by stenya** [comment]
@gorkapernas v3.11.18

**Comment by gorkapernas** [comment]
Verified fixed on v3.11.18, the WIFI control actions are checked by default.

Please note that the fix only works on clean installations, if updating the IVPN version from 3.11.14, the actions will still be unchecked. 
//Cc @stenya

**Comment by stenya** [comment]
v3.12.0 released
