### ISSUE TITLE
GUI: macOS - Cutoff issue with certain servers when IPv6 is enabled and an individual host is selected

### ISSUE THREAD

**Issue by gorkapernas** [ivpn/desktop-app#303]
### Description:
Only on macOS and WireGuard, when IPV6 is enabled and the user selects certain individual hosts e.g. Atlanta -> `us-ga1`, the label of the host selected appears cutoff in the main UI.

### Expected result:
The cutoff issue should be avoided, maybe we can add `...` at the end of the text.

### Steps to reproduce:
1. Install IVPN v3.11.15 on macOS.
2. With WireGuard, enable IPV6.
3. Enable selection of individual servers.
4. Open the list of servers.
5. Select individual host: Atlanta -> `us-ga1`.
6. Observe the issue in the main UI.

Note that the issue happens with several other hosts which have longer text strings.

### Screenshot:
![cutoff](https://github.com/ivpn/desktop-app/assets/16647612/dd211033-340d-4d71-a9fd-1402825b45a9)

### Environment:
IVPN: 3.11.15
OS: macOS

**Comment by stenya** [comment]
@gorkapernas  beta version v3.12.1006 is ready for tests

**Comment by gorkapernas** [comment]
Verified fixed on v3.12.1006, macOS, the cutoff issue with the text of certain individual hosts no longer occurs. An ellipsis has been added for long text strings.

**Comment by stenya** [comment]
IVPN Client v3.13.1 has been released
