### ISSUE TITLE
Typo: MTU tooltip

### ISSUE THREAD

**Issue by jordan-ivpn** [ivpn/desktop-app#305]
https://github.com/ivpn/desktop-app/blob/cded28f428e8d805f7a410a202ce02b7b54e26c8/ui/src/components/settings/settings-connection.vue#L330C20-L330C20

... value ~make~ affect ...

... value **may** affect ...

**Comment by stenya** [comment]
@gorkapernas  beta version v3.12.1006 is ready for tests

**Comment by gorkapernas** [comment]
Verified fixed on v3.12.1006, the typo has been corrected.

**Comment by stenya** [comment]
IVPN Client v3.13.1 has been released
