### ISSUE TITLE
[Linux] Split tunneling does not work (missing '/etc/iproute2')

### ISSUE THREAD

**Issue by elvis-hrvat** [ivpn/desktop-app#309]
# Bug report

## Describe your environment

* Device: Desktop  
* OS name and version: Arch Linux
* IVPN app version: 3.12.0 (Daemon: 3.12.0.1)

### Steps to reproduce:

1. Check Split tunnel and launch the application from Launch application.
2. Errors are displayed: `Failed to enable Split Tunneling: (exit status 1) /opt/ivpn/etc/splittun.sh: line 238: /etc/iproute2/rt_tables: No such file or directory`

**Comment by elvis-hrvat** [comment]
https://www.reddit.com/r/PrivateInternetAccess/comments/16hnv9e/wireguard_is_broken_in_arch_linux_and_debian_sid/

**Comment by stenya** [comment]
Similar issue: https://github.com/ivpn/desktop-app/issues/281#issuecomment-1793448741

**Comment by stenya** [comment]
fix: https://github.com/ivpn/desktop-app/commit/ec1b8a044213f7175d3d5729accd04498d641e57

**Comment by stenya** [comment]
@gorkapernas beta v3.12.1013

**Comment by gorkapernas** [comment]
Verified on v3.12.1014, tested on different Linux systems including Arch Linux, I was able to reproduce the issue on v3.12.0 and I can confirm the fix in the latest beta, the folder `/etc/iproute2` is created and Split Tunnel works as expected.

**Comment by stenya** [comment]
IVPN Client v3.13.1 has been released
