### ISSUE TITLE
Settings are grayed out and custom MTU cannot be set.

### ISSUE THREAD

**Issue by elvis-hrvat** [ivpn/desktop-app#310]
# Bug report

## Describe your environment

* Device: Desktop (?)  
* OS name and version: Arch Linux
* IVPN app version: 3.12.0
* IVPN daemon version: 3.12.1

### Steps to reproduce:

1. Open the Connection tab of the IVPN application
2. Custom MTU is grayed out and cannot be changed

### Observed Results:

* What happened? This could be a description, log output, etc.  

### Expected Results:

* What did you expect to happen?  

### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

If it is grayed out for some reason, please describe it in the `man` or `info`. The current IVPN app does not have offline documentation.

**Comment by jordan-ivpn** [comment]
Disconnect the VPN to make changes to MTU and obfuscation settings.

**Comment by elvis-hrvat** [comment]
> Disconnect the VPN to make changes to MTU and obfuscation settings.

That is not explained anywhere. Documentation needs to be developed.

**Comment by stenya** [comment]
@gorkapernas  v3.13.2 is ready

Added tooltips to non-editable options while VPN is connected.

**Comment by gorkapernas** [comment]
Verified on v3.13.2, all platforms, the tooltip "Disconnect VPN to edit this option" is shown when hovering on the V2Ray and MTU fields which are not editable when the VPN is connected. See screenshot below for reference.

![hovering tooltip](https://github.com/ivpn/desktop-app/assets/16647612/5e7a7a34-0891-449e-857e-8bcfcf072edf)

**Comment by stenya** [comment]
v3.13.3 released
