### ISSUE TITLE
[Windows] IVPN Split Tunneling no longer works after reconnection

### ISSUE THREAD

**Issue by RoonMoonlight** [ivpn/desktop-app#311]
# Bug report

## Describe your environment

* Device: Desktop
* OS name and version: Windows 11 22H2 (Build 22621.2283)
* IVPN app version: v3.12.0

### Steps to reproduce:

1. Set up Split Tunneling on Settings - Add any browser app to Split Tunneling list
2. Check on IVPN official website; it should say 'Not connected to IVPN' as usual
3. Reconnect to VPN
4. Refresh IVPN Official Homepage
5. It says connected to IVPN, which shouldn't happen in the first place, and this issue will remain unless you modify split tunneling setting once again
![image](https://github.com/ivpn/desktop-app/assets/25527589/1d9eeb5a-d5f8-498d-9158-00d7b29916ae)
(Note: above image is the Microsoft Edge with Split Tunnel enabled.)

### Observed Results:

* Split Tunneling feature does not work after reconnection.

### Expected Results:

* IVPN should be able to split tunnel apps normally even reconnect occurs.

### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by RoonMoonlight** [comment]
UPDATE: This bug also started to happen on Chrome as well, so I will be updating description.

**Comment by RoonMoonlight** [comment]
Update N.3: After turning off IPv6, the result goes the same; at first setup, it works properly. But when you reconnect to VPN, the Split Tunnel will NOT work afterwards unless you modify the Split Tunnel settings. I will update this as well.

**Comment by stenya** [comment]
Hi @RoonMoonlight 
Have you tried reopening your browser after the VPN connection or changing the Split Tunnel settings?
There are known limitations of this functionality:
> ...
> The split tunnel feature has an impact on applications and connections that are launched after the split tunnel is activated and the VPN is connected. Applications and connections that were already active before the split tunnel is enabled may still use the VPN connection instead of bypassing it.
> ...

https://www.ivpn.net/knowledgebase/general/split-tunnel-uses-and-limitations

**Comment by RoonMoonlight** [comment]
Oh interesting, restarting an app just fixed it. Dunno why it has to happen like this

Thank you for info, closing this for now.
