### ISSUE TITLE
[GUI] (Windows) Show application main window on single-click on app tray icon

### ISSUE THREAD

**Issue by stenya** [ivpn/desktop-app#314]
# Feature request

## Description

With the current implementation, the IVPN Client app uses a "double-click" event on the tray icon to show the application.
This approach sometimes does not work due to specific "double-click" event detection issues by the Electron.

Necessary to change:
The application must be shown when the user does a single-click. We must skip using "double-click"

**Comment by stenya** [comment]
Single-click on the tray icon:
- Windows: shows the application window
- macOS/Linux: no changes; the menu opens

**Comment by stenya** [comment]
@gorkapernas  beta version v3.12.1006 is ready for tests

**Comment by gorkapernas** [comment]
Verified on v3.12.1006, Windows 10 and Windows 11, now it is possible to show the app by clicking once in the IVPN system tray icon, right click to open the menu still works as expected.

**Comment by stenya** [comment]
IVPN Client v3.13.1 has been released
