### ISSUE TITLE
Allow custom ports with V2Ray

### ISSUE THREAD

**Issue by gorkapernas** [ivpn/desktop-app#321]
### Description:
Currently, adding custom ports when V2Ray (Quick and TCP) is enabled is not possible, although the user can still use a custom port with V2Ray if it was added before enabling V2Ray.

As confirmed, the V2Ray service listens on its own IP address using the same ports as WireGuard and OpenVPN, on both TCP and UDP ports, so it seems like we should allow users to add and use custom ports for V2Ray connections, just as we normally do for WireGuard and OpenVPN.

**Comment by stenya** [comment]
commit: https://github.com/ivpn/desktop-app/commit/c2deb66307fca77ed1d58e8d898ea91de548ceb4

**Comment by stenya** [comment]
v3.12.1010

**Comment by stenya** [comment]
@gorkapernas You are right. We must allow users to define custom ports with MultiHop+V2Ray. Feel free to move this ticket to "To do"

**Comment by gorkapernas** [comment]
Verified on v3.12.1011, all platforms, now it is also possible to define custom ports with Multihop and V2Ray enabled.
This is good to go.

**Comment by stenya** [comment]
IVPN Client v3.13.1 has been released
