### ISSUE TITLE
Allow LAN traffic and multicast not working

### ISSUE THREAD

**Issue by MamaMia14SS88** [ivpn/desktop-app#322]
# Bug report

## Describe your environment

* Device: Desktop  
* OS name and version: Windows 11 22H2
* IVPN app version: 3.12.0

### Steps to reproduce:

1. Enable firewall
2. Enable Allow LAN traffic and multicast
3. You can close settings and domains like `192.168.1.1` do not work in the browser

### Observed Results:

Can't access local addresses

### Expected Results:

The browser should open local addresses like `192.168.1.1` to configure the router. Although everything works fine with the firewall turned off.

### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by stenya** [comment]
I haven't encountered such issues on my side. Local addresses, such as 192.168.0.0/16, are accessible when 'Allow LAN traffic ...' is enabled. 
@gorkapernas, could you please check it on your side?

@MamaMia14SS88 Can you check if these addresses are accessible using the ping tool? (`ping 192.168.1.1`)

**Comment by stenya** [comment]
@MamaMia14SS88  Was the VPN connected while you were trying to access this IP?

Could you please perform the following additional tests:
1) Disconnect the VPN (if connected).
2) Disable the IVPN firewall.
3) Run `tracert 192.168.1.1`
4) Activate 'Allow LAN traffic ...' and enable the IVPN Firewall.
5) Run `tracert 192.168.1.1`

**Comment by stenya** [comment]
@MamaMia14SS88 Just in case,
 please ensure that you do not use the WiFi control functionality (option 'WiFi control -> Trusted/Untrusted WiFi network control'). 
The 'Block LAN traffic' action will override the default behavior of the Firewall when you are connected to an Untrusted network.
