### ISSUE TITLE
IVPN Does not reconnect after Hibernation

### ISSUE THREAD

**Issue by ReclinesMC** [ivpn/desktop-app#325]
# Bug report

## Describe your environment

* Device:  Lenovo Laptop
* OS name and version: Windows 11 Pro
* IVPN app version: 3.12.0

## Describe the problem
When my laptop hibernates, my vpn does not reconnect automatically on startup

### Steps to reproduce:

1. Connect to IVPN
2. Hibernate in windows
3. Log back in

### Observed Results:

* IVPN shows that it is reconnecting, however you will notice that you do not have connection to the internet, and it never reconnects.

### Expected Results:

* I expected the VPN to reconnect without issue

**Comment by stenya** [comment]
@ReclinesMC  Could you please provide us with application logs for troubleshooting?

Here's what to do:
1. Enable logging (Go to Settings -> General -> Allow logging).
2. Reproduce the issue (Connect to the VPN, then Hibernate, and Log back in).
3. Disconnect the VPN to regain connectivity.
4. Send us the logs (Go to Settings -> General -> Diagnostic logs... -> Send logs). Before sending, please add the ticket number as a user comment ("Ticket #325").

Thank you in advance.

**Comment by ReclinesMC** [comment]
For some reason the issue is not happening right now, will try to reproduce tonight.

**Comment by ReclinesMC** [comment]
The issue is for some reason no longer happening. Must've been an error on my side.
