### ISSUE TITLE
Why should the close button end the vpn connection in the ui?

### ISSUE THREAD

**Issue by iiscosd3** [ivpn/desktop-app#334]
## Description
Well, everything is described in the title, its actually pointless to have a service and implement such a annoying button which is impossible to change the behavior of...
Like tell me how do i close the ui without ending the vpn connection? Maybe i just opened the ui to see some options and consume the buttons instead of cmd... 
![image](https://github.com/ivpn/desktop-app/assets/132331050/8246a81b-e3a7-490c-a775-60e87fd35c6c)

## Describe the solution you'd like
A switch of how the ui close button should behave like? Close the ui, close the ui and move in tray, close the ui and end the vpn connection?

I simply do not want to have it in my tray.

**Comment by iiscosd3** [comment]
idek what happens if you run just the ui,  i assume it still uses the cli' type'ish interface and just displays it hence it just should pass the running process in the background in case if it doesnt and it uses just a general interface then it should start the cli'ish thing and pass the current config to it idk

**Comment by stenya** [comment]
@iiscosd3  I believe such a configuration should meet your requirements  (Settings -> General):
- "On exit: Quit without confirmation when closing application" - ENABLED
- "On exit: Disconnect when closing application" - DISABLED

![image](https://github.com/ivpn/desktop-app/assets/7881006/da44c1cf-411f-4aa2-91a0-fbb023cd7fd9)

**Comment by stenya** [comment]
I am closing the ticket as there is no further implementation required.

**Comment by iiscosd3** [comment]
![image](https://github.com/ivpn/desktop-app/assets/132331050/250f6ab1-8602-435f-8083-26e058e7e3da)
Yeah... Never paid attention to those since its greyed out by default, ux...
