### ISSUE TITLE
[bug] (Windows) WireGuard fails to start with the error: 'The service cannot accept control messages at this time.'

### ISSUE THREAD

**Issue by stenya** [ivpn/desktop-app#336]
# Bug report

## Describe your environment

* OS name and version: Windows 

## Describe the problem

Sometimes WireGuard fails to start with the error: 'The service cannot accept control messages at this time.'
Error info: [ERROR_SERVICE_CANNOT_ACCEPT_CTRL](https://learn.microsoft.com/en-us/previous-versions/ms833805(v=msdn.10)?redirectedfrom=MSDN)

Currently, the IVPN client recognizes it as an error and stops the connection.
It has to be changed: The IVPN client has to ignore such an error and try to check the status again after some delay.

**Comment by stenya** [comment]
@gorkapernas  This issue occurs very rarely, making it challenging to reproduce.
Therefore, we can only conduct regression tests.

**Comment by stenya** [comment]
v3.13.2 is ready.

**Comment by gorkapernas** [comment]
Tested WireGuard connections with different settings on v3.13.2/v3.13.3 during the past few days and I haven't experienced any errors. This looks good to go.

**Comment by stenya** [comment]
v3.13.3 released
