### ISSUE TITLE
Uninstaller does not turn the IVPN Firewall off

### ISSUE THREAD

**Issue by gorkapernas** [ivpn/desktop-app#337]
### Description:
When uninstalling the app with the IVPN Firewall enabled, the uninstaller does not turn it off, consequently, the network connection will still be blocked after uninstalling the app, if the IVPN app is reinstalled again, it is observed that the Firewall is enabled after the installation.

**Note:**
I was able to reproduce the issue on macOS and Windows, I tried on Fedora 39, but the issue did not occur, so I'm not certain that the issue also happens on Linux.

### Expected result:
The Firewall should be disabled upon uninstalling the app.

### Steps to reproduce:
1. Install version 3.13.1 on e.g. Windows 11 (same happens on beta 3.13.2)
2. Login.
3. Enable FW Always-on and connect.
4. Reset settings on logout, but maintain the FW enabled.
5. Uninstall the app.
6. Observe the issue - no internet connection.  
7. Re-install the app.
8. Observe that the FW is enabled.

### Environment:
IVPN: 3.13.1 
Platforms: macOS and Windows

**Comment by stenya** [comment]
v3.13.3

**Comment by gorkapernas** [comment]
Verified fixed on v3.13.3, macOS and Windows, the issue no longer occurs, the uninstaller disables the firewall as expected.

**Comment by stenya** [comment]
v3.13.3 released
