### ISSUE TITLE
Add support for Device Management

### ISSUE THREAD

**Issue by jurajhilje** [ivpn/desktop-app#347]
## Description

There are few updates needed to support the Device Management feature:
* Display assigned device name in the Account screen after login
* Show ‘Visit Device Management’ or ‘Enable Device Management’ action when presenting force log out prompt

**Comment by stenya** [comment]
v3.13.10 (STAGING)

**Comment by stenya** [comment]
FYI: CLI command to check device name (when enabled Device Management): `ivpn account`

**Comment by gorkapernas** [comment]
@stenya the button "Upgrade your subscription" in the device limit screen is not working, missing link? You can reproduce it by reaching the device limit with a standard account. See screenshot below for reference.
![Image 2024-01-30 at 11 46 52 AM](https://github.com/ivpn/desktop-app/assets/16647612/1c25137d-d8c3-4919-af43-f0f579fe6584)

Also, there are some differences with the mobile apps, the mobile apps, in the device limit dialog ,the button "Visit Device Management" changes to "Enable Device Management" when the feature is disabled, and the option "Retry" is always presented in all device limit dialogs. Should we do the same on desktop or should we keep the current implementation? @johnnyburnaway  See screenshot above for reference.

**Comment by stenya** [comment]
It is expected that the "Upgrade your subscription" button is not working on staging. It will work only with "ivpn.net" links which are on production only.
I have added a warning dialog to avoid such confusion in future:
![image](https://github.com/ivpn/desktop-app/assets/7881006/943bd152-b5e3-4c24-9109-dee9f431e36a)

**Comment by gorkapernas** [comment]
@stenya there is another issue, when you reach the device limit with a legacy account, we display the "Visit Device Management" button. Legacy accounts are not supposed to be able to use Device Management, so any mention to this feature should be avoided. This implementation is already done on mobile apps.
Also the button "Upgrade your subscription" is missing for legacy standard accounts. 
And lastly, this button is called "Switch to IVPN Pro" in the official requirements, so not sure if we also need to change it.

**Comment by stenya** [comment]
> the option "Retry" is always presented in all device limit dialogs

I do not plan to add "Retry" button. There are too many buttons already. The "Go back" can be used in this case

**Comment by gorkapernas** [comment]
Verified on v3.13.11-STAGING, v3.13.12-STAGING, all platforms, the issue with the legacy accounts have been fixed.
Tested the device management feature with legacy and new accounts and no more issues have been found.
This is good to go.

**Comment by stenya** [comment]
v3.14.2 released
