### ISSUE TITLE
(Linux) Two IVPN icons in the system dock 

### ISSUE THREAD

**Issue by gorkapernas** [ivpn/desktop-app#35]
### Description:
On the latest linux beta version 3.3.10, any distribution, when adding IVPN to favourites and opening the app, two IVPN icons will be displayed in the system dock.

**Note:**
See attached screenshot for further details.

### Expected result:
Only one IVPN icon should be displayed in the system dock.

### Steps to rerproduce:
1. Install latest Linux version 3.0.12 (deb or rpm) on any system e.g. Ubuntu.
2. Click on Show Applications.
3. Right click in the IVPN icon.
4. Add IVPN to favourites.
5. Open the IVPN UI app.
6. Observe that two IVPN icons will be displayed in the dock.

### Environment
IVPN version: 3.3.10
System: Ubuntu 20.04, Fedora 31

### Screenshot;
![two icons](https://user-images.githubusercontent.com/16647612/118626108-dcc35e00-b7ca-11eb-8d86-fa0f1857b884.png)

**Comment by stenya** [comment]
@gorkapernas This is a very old ticket. 
I never saw this issue during this time.
![Screen Recording 2022-05-18 at 11 43 49 86 AM](https://user-images.githubusercontent.com/7881006/168997249-e0f0272f-0b48-47fb-b084-142938c870b1.gif)

I am closing the ticket. 
Please, feel free to reopen if it will be necessary.
