### ISSUE TITLE
Unable to connect after subscription expires and more time is added

### ISSUE THREAD

**Issue by TotallyMehis** [ivpn/desktop-app#352]
# Bug report

## Describe your environment

* Device: PC
* OS name and version: Windows 11 22631.3007
* IVPN app version: Daemon 3.13.4, UI: 3.13.4

## Describe the problem

I am unable to turn on the VPN after my subscription ends and I've added more time. UI just keeps loading. I have to log out and log back in to connect to VPN.

### Steps to reproduce:

1. Wait for your subscription to expire.
2. Add more time.
3. Start client and try turning VPN on.

### Expected Results:

I should be able to connect to VPN after adding more time without re-logging.

**Comment by gorkapernas** [comment]
Verified on the latest beta, the app checks the account status in the following scenarios:

- Every 1 hour
- Upon application start
- Upon login
- Upon accessing the Account screen

Every time one of the events above happen, the account status is checked and updated accordingly if there were to be new changes e.g. more time added to the account.

**Comment by stenya** [comment]
v3.14.2 released
