### ISSUE TITLE
[bug] The daemon does not start on macOS Sonoma sometimes

### ISSUE THREAD

**Issue by stenya** [ivpn/desktop-app#354]
# Bug report

## Describe your environment

* OS name and version: macOS 14 (Sonoma)

## Describe the problem
Some customers experience the issue when the UI is unable to connect to the IVPN daemon.

![image](https://github.com/ivpn/desktop-app/assets/7881006/2c0b5d40-a27f-40af-ba53-a78953da133a)

A full app reinstallation and OS restart usually resolve the problem. However, in some cases, it helps only for a single OS session, and the issue reoccurs upon the next OS restart.

**Comment by stenya** [comment]
The daemon does not start if the background daemon item Privatus Limited is disabled in macOS settings (General -> Login items).

Solution:
1) Enable Privatus Limited in OS settings (General -> Login items).
2) Restart the OS.

The upcoming release will have a few improvements:
1) The "Login item" name will be "IVPN" to not confuse users.
2) The UI app will notify extended text for the "Error connecting to daemon" error: which guides the user to check this configuration in system settings (for macOS users).

**Comment by stenya** [comment]
v3.13.12-STAGING

**Comment by gorkapernas** [comment]
Verified on v3.13.12-STAGING, on intel and arm based processors, the login item has been updated to IVPN and has an icon.
If a daemon error occurs, the description has been updated to describe the possible issue with the background IVPN item.
See screenshots below for reference:
![Image 2024-02-01 at 10 11 30 AM](https://github.com/ivpn/desktop-app/assets/16647612/91e52ad2-23b6-479b-adec-6b0901039bc7)
![Image 2024-02-01 at 12 36 07 PM](https://github.com/ivpn/desktop-app/assets/16647612/7f70891a-6599-4b3e-a7ae-9808a63f3184)
