### ISSUE TITLE
Use same fastest server configuration for OpenVPN and WireGuard

### ISSUE THREAD

**Issue by gorkapernas** [ivpn/desktop-app#36]
### Description:
Currently, each protocol can have a different fastest server configuration to be used as the fastest servers.

The fastest server configuration should be the same for all protocols, so even if the server lists differs, if user deselect one location, it should be saved for all protocols.

**Note:**
Already implemented on iOS.

### Environment:
IVPN:  3.3.10
Platforms: All

**Comment by stenya** [comment]
@gorkapernas v3.9.26

**Comment by gorkapernas** [comment]
Verified on version 3.9.26/3.9.27, all platforms, now both protocols share the same fastest server configuration.
Tested also the IVPN version update from an older version, and the configuration was updated on both protocols to reflect the current implementation.

**Comment by stenya** [comment]
Released in v3.9.32
