### ISSUE TITLE
Application launches from GUI in inverse split, but not from CLI

### ISSUE THREAD

**Issue by 5p4r74cu5** [ivpn/desktop-app#366]
# Bug report

## Describe your environment

* OS name and version: Arch, Hyprland
* IVPN app version: v3.14.2

## Describe the problem

I'm not sure if I'm using the wrong commands for the inverse split tunnel, are the commands for inverse split tunnel different than in the normal split tunnel, where one can use `exclude` to add applications? Before using the inverse split tunnel, I was able to exclude apps via command line easily.

### Steps to reproduce:

1. Launch applications, in my case, qBittorrent, via the GUI in inverse split tunnel mode.
2. Close application.
3. Copy the launch parametres shown in the GUI.
4. Execute `ivpn exclude <gui parametres>`; in my case: `ivpn exclude /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=qbittorrent --file-forwarding org.qbittorrent.qBittorrent @@u @@`

### Observed Results:

Output in terminal is:

```
Running command in Split Tunneling environment (pid:168804): /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=qbittorrent --file-forwarding org.qbittorrent.qBittorrent @@u @@
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.
```

### Expected Results:

To launch successfully as it does when executing the same application from the GUI.

**Comment by stenya** [comment]
The usage of the `exclude` command is the same for both normal split-tunnel and inverse split-tunnel modes. I would advise you to check if the command works correctly without split-tunneling. 
In your case, please check if `/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=qbittorrent --file-forwarding org.qbittorrent.qBittorrent @@u @@` works for you.

**Comment by 5p4r74cu5** [comment]
Okay yeah, strangely doesn't launch correctly when launched via command line. Switched to non-flatpak and it fixed the problem. Thanks for the help.
