### ISSUE TITLE
Create flatpak/snap packages of our app for Linux (ui, cli and daemon)

### ISSUE THREAD

**Issue by gorkapernas** [ivpn/desktop-app#37]
It may be a good idea for greater compatibility with distros we don't currently support, also no dependancies on system libraries, puts our app into a sandbox for better security etc.

**Comment by stenya** [comment]
IVPN client is available on Snap Store as a **beta** and ready for tests.
https://snapcraft.io/ivpn

Now the client can be installed on Linux in various ways:
- by installing from the command line terminal (snap install --beta ivpn)
- by clicking a button on the Snap Store page
- by using integrated UI software managers in distributive (e.g. "Ubuntu Software")

Instructions on how to install packages on different Linux distributives can be found on the Snap Store page (bottom)

**Comment by stenya** [comment]
@gorkapernas v3.8.26 is available

**Comment by gorkapernas** [comment]
Installed the new IVPN 3.8.26 snap package on different Linux distributions and it works as expected.
I confirm all different installation processes, also the issue mentioned last week about connection loss with OpenVPN + Custom DNS enabled is fixed - ref : https://github.com/ivpn/desktop-app/commit/8bc3b1a004c1aa5eb46cc1dbc0a80f36e6128daf

**Comment by kreaninw** [comment]
It would be great to add Flatpak support as Snap doesn't support everywhere, e.g., on an immutable OS like openSUSE MicroOS.
