### ISSUE TITLE
[Bug] Spell check enabled on "DoH URI template" setting

### ISSUE THREAD

**Issue by ghost** [ivpn/desktop-app#383]
# Bug report

## Describe your environment

* Device: HP Pavilion 14-dv2012nf
* OS name and version: Linux Mint 21.2 Cinnamon, kernel 5.15.0-107-generic
* IVPN app version: v3.14.14

## Describe the problem

Spell check is enabled on the "DoH URI template" option:
![ivpn_bug](https://github.com/ivpn/desktop-app/assets/172035971/6b12a175-d5e5-4ae1-a179-033e39b4a0c4)

### Steps to reproduce:

1. Open IVPN GUI App
2. Go to settings
3. Click "DNS"

### Observed Results:

* What happened? This could be a description, log output, etc.  
Spell check is enabled.

### Expected Results:

* What did you expect to happen?  
Spell check should not be enabled here.

### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by gorkapernas** [comment]
Verified fixed on v3.14.17, all platforms, the spellcheck has been disabled from the "DoH URI template" input field.
