### ISSUE TITLE
CLI Killswitch

### ISSUE THREAD

**Issue by iXialumy** [ivpn/desktop-app#39]
# Feature request

## Description

In my opinion the cli tool should be able to toggle killswitch capabilities.
At the moment the only way to have a killswtich set up in a pure command line environment is a fully manual configuration.

**Comment by stenya** [comment]
Sorry for the long delay with the answer.
The IVPN CLI is able to toggle ON/OFF killswitch by commands:
`ivpn firewall -on`
`ivpn firewall -off`

There are also other commands to control killswitch from CLI.
```
> ivpn firewall -h
Command usage:
firewall              Firewall management
  -status             - (default) Show info about current firewall status
  -ivpn_access_allow  - Allow access to IVPN servers when Firewall is enabled
  -ivpn_access_block  - Block access to IVPN servers when Firewall is enabled
  -lan_allow          - Set configuration: allow LAN communication (take effect when firewall enabled)
  -lan_block          - Set configuration: block LAN communication (take effect when firewall enabled)
  -off                - Switch-off firewall
  -on                 - Switch-on firewall
```

Use commands to get help:
`ivpn -h -full`
`ivpn firewall -h`

**Comment by stenya** [comment]
I am closing the ticket now. 
Feel free to reopen it if necessary.
