### ISSUE TITLE
(Linux) Sign RPM packages with SHA256 hash algorithm

### ISSUE THREAD

**Issue by jordan-ivpn** [ivpn/desktop-app#390]
# Bug report

## Describe your environment

* Device: _____  
* OS name and version: __AlmaLinux 9.4, Rocky Linux 9.4___  
* IVPN app version: __3.14.14-1___  

## Describe the problem

RHEL 9 drops support for SHA1 package signing:

https://www.redhat.com/en/blog/rhel-security-sha-1-package-signatures-distrusted-rhel-9

### Steps to reproduce:

1. `sudo dnf install epel-release`
2. `sudo dnf install openvpn`
3. `sudo dnf config-manager --add-repo https://repo.ivpn.net/stable/centos/generic/ivpn.repo`
4. `sudo dnf install ivpn` (or `ivpn-ui`)

### Observed Results:

![install-almalinux2-sha1-error](https://github.com/user-attachments/assets/ddee56af-5bdd-45ca-8194-b74cb5602e3b)

### Workaround:

```
sudo dnf install epel-release
sudo dnf install openvpn
sudo dnf config-manager --add-repo https://repo.ivpn.net/stable/centos/generic/ivpn.repo
sudo update-crypto-policies --set LEGACY
sudo dnf install ivpn
[sudo dnf install ivpn-ui]
sudo update-crypto-policies --set DEFAULT
sync
sudo reboot
```

### References:

https://mirrors.almalinux.org/isos.html
https://rockylinux.org/download

--

Thanks.

**Comment by stenya** [comment]
References:
https://www.redhat.com/en/blog/rhel-security-sha-1-package-signatures-distrusted-rhel-9

**Comment by stenya** [comment]
Prepared test repo with SHA256 hashes:
`https://repo.ivpn.net/stable_test/fedora/generic/ivpn_test.repo`

@gorkapernas I do not expect any issues with this change. 
Anyway, please, check compatibility with the most popular Linux distributions that use RPM repositories.

P.S. AlmaLinux-9.4 already installed on Proxmox (#117)

**Comment by gorkapernas** [comment]
Tested installation with the test repo on different RPM based distributions, Fedora, OpenSUSE, CentOS, Alma,  no issues found.

**Comment by pwn-all** [comment]
@gorkapernas 
> Tested installation with the test repo on different RPM based distributions, Fedora, OpenSUSE, CentOS, Alma, no issues found.

```
wget  https://repo.ivpn.net/stable_test/fedora/generic/ivpn_test.repo
ivpn_test.repo       100% [============================================================================================================>]     211     --.-KB/s
                          [Files: 1  Bytes: 211  [208 B/s] Redirects: 0  Todo: 0  Errors: 0                                             ]
root@root:/etc/yum.repos.d# rpm-ostree install ivpn-ui
Inactive requests:
  langpacks-en (already provided by langpacks-en-4.0-13.fc40.noarch)
Checking out tree fefc4b9... done
Enabled rpm-md repositories: fedora-cisco-openh264 updates fedora mullvad-stable ivpn-stable
Importing rpm-md... done
rpm-md repo 'fedora-cisco-openh264' (cached); generated: 2024-03-12T11:45:42Z solvables: 3
rpm-md repo 'updates' (cached); generated: 2024-09-17T02:53:06Z solvables: 26716
rpm-md repo 'fedora' (cached); generated: 2024-04-14T18:51:11Z solvables: 74881
rpm-md repo 'mullvad-stable' (cached); generated: 2024-09-05T15:31:49Z solvables: 2
rpm-md repo 'ivpn-stable' (cached); generated: 2024-06-03T13:27:17Z solvables: 60
Resolving dependencies... done
Will download: 1 package (25.8 MB)
Downloading from 'ivpn-stable'... done
error: Downloading from 'ivpn-stable': Cannot download pool/ivpn-3.14.14-1.x86_64.rpm: All mirrors were tried; Last error: Downloading successful, but checksum doesn't match. Calculated: af3d463310cfeaa5cd04ea88c0b37d73dff0fc485f96c9dda6baa4686a1d37a3(sha256)  Expected: e65c72e34f75dcac0e4113584fb0687c2852fa5bdea03bde287a0344147297e1(sha256) 
```

**Comment by stenya** [comment]
@pwn-all s this Fedora Silverblue? Could you provide more information about your OS and its version?

Are you sure you're not mixing the original and test repositories on your system?

**Comment by pwn-all** [comment]
@stenya Yes, this is Fedora Silverblue. No we don't use multiple repositories (we don't “mix”). We use: https://repo.ivpn.net/stable_test/fedora/generic/ivpn_test.repo

.repo hash:
`0f1235646f75ebd8c1444018f5b779a2638968d8e997845c1bfdf413ad1c994d  ivpn_test.repo`

**Comment by stenya** [comment]
Thanks.
We double-tested the repository on Fedora Silverblue, and no problems were observed.
I am afraid, it might be a local issue on your side.

**Comment by stenya** [comment]
The RPM repository now uses the SHA-256 hash algorithm.

**Comment by pwn-all** [comment]
@stenya with `https://repo.ivpn.net/stable/fedora/generic/ivpn.repo` everything works as it should.
```
Added:
  ivpn-3.14.17-1.x86_64
  ivpn-ui-3.14.17-1.x86_64
```

**Comment by jordan-ivpn** [comment]
Tested and confirmed to install successfully on Alma Linux 8.10.
