### ISSUE TITLE
(Linux) App installation creates redundant folder

### ISSUE THREAD

**Issue by edwardivpn** [ivpn/desktop-app#391]
# Bug report

## Describe your environment

* OS name and version: XUbuntu 22.04
* IVPN app version: 3.14.14

## Describe the problem

Installing the IVPN app creates an empty and unused directory in the `/servers.json` root folder.

**Comment by stenya** [comment]
Also reproducible on Ubuntu

**Comment by stenya** [comment]
v3.14.17
