### ISSUE TITLE
It is possible to create multiple sessions when pressing Enter multiple times when logging in

### ISSUE THREAD

**Issue by gorkapernas** [ivpn/desktop-app#392]
### Description:
If the user presses multiple times the Enter button to confirm the login action, the app creates multiple sessions.
It is even possible to reach the rate limit even before the user logs in.

### Steps to reproduce:
1. Install the latest IVPN app on any desktop platform.
2. Open the app and enter the account ID in the login form.
3. Press "Enter" multiple times in order to confirm the login.
4. Observe that the apps creates multiple sessions, even the rate limit error is displayed (if user presses 6 times the Enter button).

### Expected result:
The user should only be able to create one session when logging in.

### Environment:
IVPN: 2.14.14
OS: All platforms

**Comment by stenya** [comment]
v3.14.17

**Comment by gorkapernas** [comment]
Verified fixed on v3.14.17, all platforms, it is no longer possible to create multiple sessions when pressing enter repeatedly during the login process. Only one session is created as expected.
