### ISSUE TITLE
Support force log in when 2FA or Captcha is required

### ISSUE THREAD

**Issue by gorkapernas** [ivpn/desktop-app#40]
### Description
With the current app implementation, there is a case when it is not possible to force login when reaching session limit with 2FA or captcha enabled.

Apps need to handle the case like this:

- 2FA or captcha code is sent to /session/new API
- If API returns "Too many sessions" response and user starts /session/new with force: true, app needs to also include 2FA or captcha code from the previous API call

### Expected result
User should be able to force the login when reaching the session limit after entering the correct captcha or 2FA code.

### Steps to reproduce
1. Login with 2FA until reaching the session limit.
2. Tap on "Logout from all other devices".
3. Observe the issue.
4. Repeat the same steps, but this time by reaching the session limit after entering the captcha code.

**Comment by gorkapernas** [comment]
Verified on v3.3.12, macOS, Linux and Windows, logging in after reaching the session limit with 2FA and Captcha is now possible.

Please note that sometimes with Captcha, the API still throws an error when submitting a captcha request, preventing the user from logging in. This is a backend issue, so this ticket can be moved to deployable.

**Comment by stenya** [comment]
v3.3.20 is released.
[Changelog](https://github.com/ivpn/desktop-app/blob/master/CHANGELOG.md)
