### ISSUE TITLE
Linux Mint: Doesn't save Split Tunnel Apps

### ISSUE THREAD

**Issue by albotroz** [ivpn/desktop-app#401]
# Bug report

## Describe your environment

* Device: Lenovo ThinkPad T14  
* OS name and version: Linux Mint 22 Cinnamon 6.2.9  
* IVPN app version: 3.14.17  

## Describe the problem

After each start from sleep mode, energy-saving mode or after a restart, all previously saved/added programs in the split tunnel list are deleted.

### Steps to reproduce:

Add program to Split Tunnel list, shut off/ restart OS or wake up OS after sleep mode. The programs are gone.

### Expected Results:

The added or saved programs in the Split Tunnel list should continue to exist after restarting the operating system or after waking up from sleep mode - as is the case with the iVPN version of Windows.

**Comment by stenya** [comment]
This is how Split-Tunneling works on Linux. To start an app in the Split Tunnel environment, it must be manually launched from the IVPN app. 
In the Split-Tunneling settings (on Linux), you can see a list of active (running) application instances that are operating in Split-Tunneling mode. As soon as an application is closed, it disappears from the list.
