### ISSUE TITLE
App does not connect at launch on macOS Sequoia 15.0 

### ISSUE THREAD

**Issue by gorkapernas** [ivpn/desktop-app#403]
### Description:
On macOS Sequoia 15.0, when the app uses WG and V2ray, the app doesn't connect at launch even if the settings "launch at login" and " autoconnect on launch" are enabled.
The issue doesn't happen on older macOS versions.

### Steps to reproduce:
1. Install IVPN 3.14.17 macOS Sequoia 15.
2. Login.
3. Enable "launch at login" and " autoconnect on launch".
4. Select WireGuard + V2ray.
5. Make sure "Allow background daemon to manage autoconnect"  is disabled.
6. Reboot the machine (or relaunch the app).
7. Observe that the app does not connect at launch.

### Expected result:
The app should connect at launch.

### Environment:
IVPN: 3.14.17
OS: macOS Sequoia 15.

**Comment by stenya** [comment]
v3.14.23

**Comment by gorkapernas** [comment]
Verified fixed on v3.14.23, macOS Sequoia, the app connects at launch as expected.
