### ISSUE TITLE
(Linux) Long start time for Firefox/Thunderbird when connected to server via IVPN tool

### ISSUE THREAD

**Issue by mstolin** [ivpn/desktop-app#405]
# Bug report

## Describe your environment

* Device: Lenovo Thinkpad X1  
* OS name and version: Fedora Linux 40 (Workstation Edition) 
* IVPN app version: 3.14.17 x64  (installed via dnf as described at https://www.ivpn.net/en/apps-linux/#fedora)
* Firefox: 131.0.3 (64 bit)
* Thunderbird: 128.2.0esr (64-bit)
* LibreWolf: 131.0.3-1

## Describe the problem

When connected to a VPN server via IVPN (Linux application, running in background), starting a new Firefox or Thunderbird process takes > 2min (LibreWolf took around 4min). If not connected to a VPN server (but IVPN is still running in the background), Firefox and Thunderbird start immediately as expected.

Other (non-firefox) browsers, e.g. Brave don't have this issue.

### Steps to reproduce:

1. Start IVPN
2. Connect to a server
3. Start new Firefox/Thunderbird Process/Window

### Observed Results:

* Way too long starting time

### Expected Results:

* Process should start as expected, in a shorter time

**Comment by stenya** [comment]
Duplicate: https://github.com/ivpn/desktop-app/issues/259
