### ISSUE TITLE
Firewall deactivated when "Always-on" is still enabled after forcing logout

### ISSUE THREAD

**Issue by gorkapernas** [ivpn/desktop-app#41]
### Description:
On Windows, Linux and macOS, when Device A has enabled "Always-on", but device B forces logout on Device A, when Device A logs back in, the firewall will be deactivated, but the option "Always-on" will still be enabled.

### Expected result:
"Always-on" should be disabled after being forced logout e.g. due to reaching session limit on a different device.

### Steps to reproduce:
1. DEVICE A: Install version 3.3.10 e.g. Windows 10.
2. DEVICE A: Login.
3. DEVICE A: Enable "Always-on" firewall and connect.
4. DEVICE B: Reach the session limit and force the logout on DEVICE A.
5. DEVICE A: Observe that the app logs the user out.
6. DEVICE A: Login and observe that the firewall is disabled, but the option "Always-on" is still enabled.

### Environment:
IVPN: v3.3.10
Platforms: All platforms

**Comment by gorkapernas** [comment]
On macOS, it seems that the Firewall still remains enabled even after forcing the logout on a different device. 
![firewall_logged out](https://user-images.githubusercontent.com/16647612/119105978-25268a00-ba1e-11eb-8c4d-651cfdfcbcd9.png)

**Comment by gorkapernas** [comment]
Verified on 3.3.52, all platforms, the expected result has been changed according to the new requirements described here: https://github.com/ivpn/desktop-app/issues/87#issuecomment-941098089

Current behaviour:
- When a user forces logout on a device X which has Always-on enabled, when the device X logs out, the Firewall is not disabled. The Firewall state is kept and therefore, the internet traffic is blocked.

**Comment by stenya** [comment]
Released in v3.4.0
