### ISSUE TITLE
"Undefined" error when failing to manually generate WG keys

### ISSUE THREAD

**Issue by gorkapernas** [ivpn/desktop-app#42]
### Description:
On version 3.3.10, all platforms, when failing to manually generate WG keys e.g. due to no internet connection, the app shows the following error.

![image](https://user-images.githubusercontent.com/16647612/119106337-8baba800-ba1e-11eb-92f5-a4288871051d.png)

### Expected result:
The error presented to the user should describe the problem accurately. 

### Steps to reproduce:
1. Install version 3.3.10
2. Login.
3. Turn off WIFI.
4. Attempt to generate manually a WG key.
5. Observe the error.

### Environment:
IVPN: v3.3.10
Platforms:  All

**Comment by stenya** [comment]
v3.3.20 is released.
[Changelog](https://github.com/ivpn/desktop-app/blob/master/CHANGELOG.md)
