### ISSUE TITLE
CLI: Add IPv6 support to the CLI

### ISSUE THREAD

**Issue by stenya** [ivpn/desktop-app#44]

**Comment by stenya** [comment]
The `servers` command output extended by additional column `IPv? tunnel`
The 'connected' command extended by additional option:
```
-ipv6tunnel           - Enable IPv6 in VPN tunnel (WireGuard connections only)
                        (IPv6 addresses are preferred when a host has a dual stack IPv6/IPv4; IPv4-only hosts are unaffected)
```

**Comment by stenya** [comment]
@gorkapernas beta version v3.3.14

**Comment by gorkapernas** [comment]
Verified on version 3.3.14, all platforms, now it is possible to connect through an IPv6 tunnel with the CLI (only WireGuard), by adding the following extension `-ipv6tunnel` to the `connect` command + WireGuard server.

@stenya Can't we show the IPv6 IP address in the connection output? we need to show some sort of proofs when using IPv6. Currently we only show the IPv4 connection info, so ideally we should show both IPv4/IPv6 connection info when IPv6 for WireGuard is in use.

**Comment by stenya** [comment]
Good point

**Comment by stenya** [comment]
@gorkapernas v3.3.15

**Comment by gorkapernas** [comment]
Verified on version 3.3.15, now the local IPv6 can be seen in the connection output when using IPv6 when connecting with WireGuard to IVPN.

**Comment by stenya** [comment]
v3.3.20 is released.
[Changelog](https://github.com/ivpn/desktop-app/blob/master/CHANGELOG.md)
