### ISSUE TITLE
Unable to connect to Wireguard servers on Windows 7 (64 bit)

### ISSUE THREAD

**Issue by GentlemansKiller** [ivpn/desktop-app#46]
![ivpn-wireguard](https://user-images.githubusercontent.com/30847729/120871293-d5d57300-c560-11eb-871a-ff34dd790153.JPG)

When I go into the settings and change to Wireguard and try to connect, I get the above. Here are some relevant logs:

```
Jun  5 18:08:50.660 [wg    ] Installing service...
Jun  5 18:08:50.809 [wg    ] Waiting for service install...
Jun  5 18:08:50.809 [wg    ] Service installed
Jun  5 18:08:50.809 [wg    ] Waiting for service start...
Jun  5 18:08:51.119 [wg    ] Failed to install service. Uninstalling...
Jun  5 18:08:51.119 [wg    ] Disconnecting...
Jun  5 18:08:51.119 [wg    ] Uninstalling service...
Jun  5 18:08:51.137 [wg    ] Service uninstalled
Jun  5 18:08:51.137 [wg    ] Connection stopped
Jun  5 18:08:51.137 [servc ] ERROR service.go:712:(in github.com/ivpn/desktop-app-daemon/service.(*Service).connect): connection error: failed to install windows service: service start error: The service has not been started.
Jun  5 18:08:51.137 [servc ] Route change receiver stopped
Jun  5 18:08:51.137 [servc ] State: {DISCONNECTED failed to install windows service: service start error: The service has not been started. WireGuard 1622934531 false <nil> 0 <nil> 0  false false }
Jun  5 18:08:51.137 [prtcl ] [-->] VpnStateResp
Jun  5 18:08:51.137 [servc ] VPN state forwarder stopped
Jun  5 18:08:51.137 [servc ] VPN process stopped
Jun  5 18:08:51.137 [servc ] ERROR service.go:408:(in github.com/ivpn/desktop-app-daemon/service.(*Service).keepConnection): Connection error: connection error: failed to install windows service: service start error: The service has not been started.
```

I am also sending you guys the logs directly through the IVPN UI

**Comment by GentlemansKiller** [comment]
![ivpn-wireguard2](https://user-images.githubusercontent.com/30847729/120871455-47152600-c561-11eb-8616-5c64221249ea.JPG)

**Comment by stenya** [comment]
@GentlemansKiller Thank you for the report.

I just did tests on our side with Win7 x64. No issues found, WireGuard works as expected.
We will keep the eyes on this issue. 

Anyway, can you, please, ensure that you have all updates for Win7 x64 installed? 
Additionally, you can try to check if the official WireGuard client works for you (https://www.wireguard.com/install/)

**Comment by GentlemansKiller** [comment]
I got it to work :D 

I'll outline what i did, for anyone else who may have the problem:

I went to the wireguard site and downloaded and installed the windows program

During the installation, it told me that I needed to download and install Windows Update Hotfix KB2921916
https://download.wireguard.com/windows-toolchain/distfiles/Windows6.1-KB2921916-x64.msu

Here is a good article to show how to install an msu file:
https://winaero.com/how-to-install-cab-and-msu-updates-in-windows-10/
(Works on windows 7 as well)

Also make sure the service "Windows Update" is started or else the command will not execute properly.

I restarted my computer, and after that, Wireguard worked fine :)

**Comment by stenya** [comment]
I am glad to hear it :)

**Comment by GentlemansKiller** [comment]
I know this is closed but I wanted to add something else since I am rebuilding my Windows 7 lately.
In order to install KB2921916 you will need to run Zeffy's WUFUC tool to get past the soft block on Windows 7 where it doesnt allow certain updates to be installed if you're using super modern Ryzen gear but still running Windows 7 (Yes, I am doing that because i hate Win10)
https://www.winhelponline.com/blog/windows-update-error-80240037-windows-7-8/
https://github.com/zeffy/wufuc

Just forgot about it before...
(if someone is in need of a pre-build MSI lmk)
