### ISSUE TITLE
(Win) Icons created in %temp% each time app is launched

### ISSUE THREAD

**Issue by jordan-ivpn** [ivpn/desktop-app#47]
# Bug report

## Describe your environment

* Device: Windows 10 Pro
* OS name and version: _____  
* IVPN app version: 3.3.10  

## Describe the problem

Icon files are created in the user's %temp% folder each time the app is launched and they are not removed.  These icons are for the connection status in the system tray.

### Steps to reproduce:

1. Launch the IVPN App one or more times.
2. Open Windows Explorer and go to %temp%
3. Confirm that 4 new icon files are created.

### Observed Results:

![tmp-icons1](https://user-images.githubusercontent.com/74565577/120911611-fc210e80-c645-11eb-89b4-93f743789261.png)
![tmp-icons2](https://user-images.githubusercontent.com/74565577/120911616-fd523b80-c645-11eb-8dfc-cc6759fa9b0f.png)

### Expected Results:

Icons should either be removed or only one set should be created or not created at all.

**Comment by stenya** [comment]
Beta v3.3.52 is ready for tests

**Comment by gorkapernas** [comment]
Verified on v3.3.52, Windows 10 and Windows 11, after a fresh installation and launching the app, the set of icons are NOT created in the %temp% folder, neither when launching the app every time after.
Please note that you might need to remove the set of icons from previous versions before verifying this.

**Comment by stenya** [comment]
Released in v3.4.0
