### ISSUE TITLE
(Windows) UI: Contrast tray icon color 

### ISSUE THREAD

**Issue by stenya** [ivpn/desktop-app#48]
Implement different colors for tray icon according to windows color scheme (dark\light):
- black icon for the light theme 
- white icon for the dark theme

**Comment by stenya** [comment]
There are few limitations:
1) It is not possible to detect Windows theme change on a fly. So, the tray IVPN icon will stay with unchanged color if the user will switch the Windows theme (until the next app launch).
2) All these changes not related to Windows 7. Due to the lack of required API for Windows 7, this version of Windows will keep the implementation as it was before (white icons will be in use).

**Comment by stenya** [comment]
@gorkapernas  v3.3.16

**Comment by gorkapernas** [comment]
Verified on v3.3.16, Windows 10, the new colors for the system tray icon have been implemented as per requirements in the ticket.

@stenya There is one scenario where the color of the system tray icon does not change according o the system theme. There is a custom option on Windows 10 where the user can select a theme for Windows and another one for the app mode, see screenshot below
![Windows 10 custom theme](https://user-images.githubusercontent.com/16647612/123120532-af5e7580-d444-11eb-8db2-cfb53cacd45a.png)

If the user sets the default Windows mode to Dark and the default app mode to Light, IVPN system tray icon will use the dark color over the Windows dark task bar, see screenshot below
![win dark+app light](https://user-images.githubusercontent.com/16647612/123120821-ecc30300-d444-11eb-881d-668f7fd3b2a1.png)

On the contrary, if the user sets the default Windows mode to Light and the default app mode to Dark, IVPN system tray icon will use the light color over the Windows light task bar, see screenshot below
![win light+app dark](https://user-images.githubusercontent.com/16647612/123120973-10864900-d445-11eb-8d34-a7d1a78c9d6d.png)

I'm not sure if there is anything we can do about this or it is simply design to work like this. @stenya please let me know your thoughts.

**Comment by stenya** [comment]
We can do nothing with it for now.

**Comment by gorkapernas** [comment]
@stenya Understood, let's move this to deployable, if we have problems with this in the future we can always create a new ticket.

**Comment by stenya** [comment]
v3.3.20 is released.
[Changelog](https://github.com/ivpn/desktop-app/blob/master/CHANGELOG.md)
