### ISSUE TITLE
Obfsproxy binary path

### ISSUE THREAD

**Issue by tommytran732** [ivpn/desktop-app#5]
# Bug report

## Describe your environment

* Device: Desktop
* OS name and version: Fedora Workstation 33
* IVPN app version: Client v.3.2.3, Daemon v2.12.16
### Steps to reproduce:

1. Install obfsproxy using `sudo pip install obfsproxy`
2. Set IVPN to use obfsproxy
3. Try to connect to a VPN server

### Observed Results:

* What happened? This could be a description, log output, etc.  
IVPN will only look for the obfsproxy binary at /usr/bin/obfsproxy, while pip will actually install it it at /usr/local/bin/obfsproxy. Of course, if obfsproxy is installed as a user app, it will be at another location as well.

### Expected Results:
IVPN should attempt to look for the obfsproxy binary at other common places (such as /usr/local/bin/obfsproxy) instead of the 1 path it is doing right now. In fact, as of now, I don't know of a way to make it work with obfsproxy yet.

**Comment by stenya** [comment]
Beta v3.3.47 is ready for testing

**Comment by gorkapernas** [comment]
Verified on Beta v3.3.47, Fedora 33, the obfsproxy binary v4 has been integrated into the app, so it works immediately after installing IVPN. The binary can also be found on `/usr/local/bin/obfsproxy`.
Tested after upgrading IVPN and on fresh installation, and the app connects successfully with obfsproxy on both cases.

@tommytran732 let us know if you still encounter any problems once we release the new IVPN version for Linux.

**Comment by stenya** [comment]
Released in v3.4.0
