### ISSUE TITLE
(Windows) WireGuard interface has an ever-increasing number

### ISSUE THREAD

**Issue by jordan-ivpn** [ivpn/desktop-app#50]
# Bug report

## Describe your environment

* Device: _____  
* OS name and version: Windows 10  
* IVPN app version: 3.3.10  

## Describe the problem

Hover the mouse cursor over the Windows network icon in the system tray after the VPN is connected and the WireGuard interface has a number on it.  This number is incremented with each connection and persists through a reboot.

![win-wg-tun-counter1](https://user-images.githubusercontent.com/74565577/122988561-1dc90800-d35f-11eb-85f1-d51695aaa4de.png)

### Steps to reproduce:

1. Connect via WireGuard.
2. Check the Network icon in the system tray.
3. Disconnect, reconnect, and check the Network icon again.

### Observed Results:

The counter increases with each connection and this could be seen as "annoying".

### Expected Results:

Use a consistent and non-changing interface name for the WireGuard connection's interface.

**Comment by stenya** [comment]
This behavior is related to WireGurd+Wintun internal implementation.

The current beta version of the IVPN client (v3.3.48) is using the latest version of WireGuard.
It has different behavior now: the interface number not increasing constantly anymore. But it takes a number from a small diapason.

I have nothing to do here. I am closing the ticket.
@jordan-ivpn @gorkapernas  Feel free to reopen the ticket if needed.
