### ISSUE TITLE
(Windows) Map's position out of place when going to settings while connecting

### ISSUE THREAD

**Issue by gorkapernas** [ivpn/desktop-app#51]
### Description
On latest beta 3.3.16, Windows 10, when the user connects with WireGuard and goes to the Settings, once the user goes back to the main screen, the map locations will be out of place instead of focusing in the location the user is connected to.

**Note:**
The issue ONLY happens on Windows AND with WireGuard.

### Expected result
The map should always focus in the location the user is connected to.

### Steps to reproduce
1. Install version 3.3.16.
2. Login.
3. With WireGuard, connect.
4. While the app is establishing connection, go to Settings.
5. Go back to the main screen, map.
6. Observe the issue.

**Comment by stenya** [comment]
@gorkapernas v3.3.20

**Comment by gorkapernas** [comment]
Verified on v3.3.20, Windows 10, the issue no longer occurs, the map always focuses in the location the user is connected to.

**Comment by stenya** [comment]
v3.3.20 is released.
[Changelog](https://github.com/ivpn/desktop-app/blob/master/CHANGELOG.md)
