### ISSUE TITLE
(Windows 11) IVPN CLI not working after installing Windows 11

### ISSUE THREAD

**Issue by gorkapernas** [ivpn/desktop-app#53]
### Description:
After installing Windows 11, the CLI client stopped working. However, once I fresh installed IVPN and enabled the CLI during the installation, the CLI client worked again. Something related to the new OS installation?

### Expected result:
IVPN CLI client should work after updating the OS to Windows 11.

### Steps to reproduce:
1. On Windows 10, install IVPN 3.3.20 (enable the CLI).
2. Login.
3. Update the Windows OS to Windows 11.
4. After the OS installation is finished, check if the IVPN CLI works

### Environment:
IVPN: v3.3.20
Platforms: Windows 11

**Comment by stenya** [comment]
@gorkapernas 
There is no issue here.
It looks like Windows11 erased the system `%PATH%` variable.

So the system does not know the location of `ivpn.exe` anymore.
There are two options to make it work:
opt1) update `%PATH%` manually (add `C:\Program Files\IVPN Client\cli` to it) 
opt2) OR reinstall IVPN Client (do not forget to enable `Add IVPN CLI binary to the path` in the installer)

**Comment by gorkapernas** [comment]
@stenya got it, I think we can safely close this ticket.
