### ISSUE TITLE
(Windows 11) IVPN update mechanism not working

### ISSUE THREAD

**Issue by gorkapernas** [ivpn/desktop-app#54]
### Description:
After installing Windows 11, I tried to update IVPN from version 3.3.10 to  version 3.3.20, but the app failed to install the update with the following error - `Update failed (Failed to run update binary)`

### Expected result:
The update mechanism should work on Windows 11.

### Steps to reproduce:
1. On Windows 11, install version 3.3.10.
2. Run "Check for updates",
3. When the update screen appears, try to install the new version.
4. Observe the error.

### Environment:
IVPN: v3.3.10, v3.3.20
Platforms: Windows 11

### Screenshot:
![update_error_Windows 11](https://user-images.githubusercontent.com/16647612/124104547-ada73a00-da62-11eb-990c-a326166e309a.png)

**Comment by stenya** [comment]
@gorkapernas Tested on "Windows 11 Insider Preview 22000".
Update from 3.3.10 to 3.3.30 -> No issues found. Update success.
Update from 3.3.20 to 3.3.30 -> No issues found. Update success.

Can you, please, provide more detailed info about your test environment? (Win11 build version?)

**Comment by gorkapernas** [comment]
@stenya I can't reproduce the issue anymore, I also was able to install the update from 3.3.10 to 3.3.30 and from 3.3.20 to 3.3.30 without issues. Maybe the issue only occurs right after installing the Windows 11 OS? Anyways, I'll move this to QA and run a few more tests.

**Comment by stenya** [comment]
@gorkapernas  I just can guess:
The current live build v3.3.30 is signed by a new certificate (extended validation certificate). 
Microsoft trusts him more than the certificate we used for the previous versions (up to 3.3.20).

So, probably, when you tried to upgrade to 3.3.20 the fail was because Windows blocked binary with was signed by the old certificate.

**Comment by gorkapernas** [comment]
@stenya I'm not able to reproduce the issue, so it might have been caused by what you mention.
I think it's safe to close the ticket.
