### ISSUE TITLE
Update Win & macOS sha256 checksums on CHANGELOG.md

### ISSUE THREAD

**Issue by jordan-ivpn** [ivpn/desktop-app#55]
# Bug report

## Describe the problem

The checksum entries for v3.3.20 on the changelog page for both Windows and macOS seem to be copied from the 3.3.10 release.

3.3.20: https://github.com/ivpn/desktop-app/blob/39001a546a6c59bb66f56e39c36a48826ade31ac/CHANGELOG.md
3.3.10: https://github.com/ivpn/desktop-app-ui2/blob/c83197d4c3dcedf934961fffa167f0bfd9e3f357/CHANGELOG.md

The `ivpn.net/apps-* ` pages list the correct checksums for the new 3.3.20 releases for Windows and macOS.

Thanks.

**Comment by stenya** [comment]
Fixed.
https://github.com/ivpn/desktop-app/commit/a962ed65cb5234a5f846e11c9bf06e20d0bbe19e#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed
