### ISSUE TITLE
(Linux) Add wiregurad-tools as the required dependency on installation

### ISSUE THREAD

**Issue by sith-on-mars** [ivpn/desktop-app#6]
# Bug report

## Describe your environment

* Device: _____  
* OS name and version: OpenSUSE Tumbleweed Gnome  
* IVPN app version: both daemon and apps are latest  

## Describe the problem

When installing the daemon, it doesn't ask you to install wiregurad-tools. If one doesn't manually install wiregurad-tools, WireGuard protocol won't work. I think the installation package should include wiregurad-tools as a required dependency to avoid this confusion.

**Comment by stenya** [comment]
https://github.com/ivpn/desktop-app/issues/69#issuecomment-920082389

**Comment by gorkapernas** [comment]
This is not ready yet, further work is needed.
Ref: https://github.com/ivpn/desktop-app/issues/69

**Comment by gorkapernas** [comment]
This is has been tested on v3.3.68 on several Linux OS, the wireguard-tools package has been integrated correctly into the IVPN base package. Please see https://github.com/ivpn/desktop-app/issues/69 for further details.

**Comment by stenya** [comment]
Released in v3.4.0
