### ISSUE TITLE
IVPN service won't start (Windows Server 2019 Standard)

### ISSUE THREAD

**Issue by rogergh** [ivpn/desktop-app#61]
The IVPN-service won't start, so the client fails with "Error connecting to IVPN Daemon". The service instantly fails if I try to start it manually from services.msc.
This only happens on the new app (3.3.20).
Legacy 2.12.17 works fine.

The only log I can find contains multiple of these entries:

> [error] DAEMON CONNECTION ERROR: Unable to obtain IVPN daemon connection parameters: Error: ENOENT: no such file or directory, open 'C:\Program Files\IVPN Client\etc\port.txt'

I can confirm there is no "port.txt" at that location, if that is relevant to this issue.

EDIT:
Fixed typo in version number (3.3.2.0 -> 3.3.20)

**Comment by stenya** [comment]
@rogergh Hi. Are you speaking about version 3.3.**20**?

**Comment by rogergh** [comment]
> @rogergh Hi. Are you speaking about version 3.3.**20**?

Yes, I meant 3.3.20. I will edit the issue with correct version number.

**Comment by stenya** [comment]
Analysis result: 
The service is unable to start due to the error "wlanapi.dll is missing". 
Seems, this library is missing on Windows Server.

Fixing plans:
It is necessary to skip using CGO compilation in service implementation.

**Comment by stenya** [comment]
Beta v3.3.38 is ready for test

**Comment by gorkapernas** [comment]
Verified on latest beta 3.3.48, Windows 10, the IVPN starts and runs as expected in such cases as described in the ticket.
Tested by removing the WIFI support from the windows configuration.

@rogergh please let us know if you still have problems with the latest IVPN version on Windows after we release it.

**Comment by rogergh** [comment]
> Verified on latest beta 3.3.48, Windows 10, the IVPN starts and runs as expected in such cases as described in the ticket. Tested by removing the WIFI support from the windows configuration.
> 
> @rogergh please let us know if you still have problems with the latest IVPN version on Windows after we release it.

Great, thanks! I will try it as soon as you release the version.

**Comment by stenya** [comment]
Released in v3.4.0
