### ISSUE TITLE
Server selection order incorrect when sorted by country

### ISSUE THREAD

**Issue by cipheromega** [ivpn/desktop-app#65]
# Bug report

## Describe the problem

Servers are sorted alphabetically according to their ISO 3166-1 alpha-2 code. e.g. CH, GB. and not by country name.

### Steps to reproduce:

1. Open server selection screen
2. Sort by country

### Observed Results:

Canada
Switzerland
Czech
...
France
United Kingdom
Hong Kong

### Expected Results:

Servers are sorted by country alphabetically.

Canada
Czech
...
France
Hong Kong
...
Switzerland
...
United Kingdom

**Comment by stenya** [comment]
@gorkapernas  v3.3.30

**Comment by gorkapernas** [comment]
Verified fixed on v3.3.30, tested on macOS, Windows and Linux, when the list of servers is sorted by Country, the servers are displayed alphabetically by country name as expected.

**Comment by stenya** [comment]
Released in v3.3.30
