### ISSUE TITLE
(Windows) Add IVPN to winget-pkgs

### ISSUE THREAD

**Issue by nnothstine** [ivpn/desktop-app#66]
# Feature request

## Description
Add IVPN to winget-pkgs

## Describe the solution you'd like
Hey! I was wondering if it'd be possible to add IVPN to Winget -- would love to be able to deploy it on Windows via the native package manager.

## Describe alternatives you've considered
I can manually install it just fine, but I've recently moved over from macOS, and IVPN worked on Homebrew there. Not seeing it on either Chocolatey or Scoop.

**Comment by quhxl** [comment]
Someone has already tried it. (microsoft/winget-pkgs#19005) However, it was rejected because winget only allows silent installs and this window does not allow exactly that.

![grafik](https://user-images.githubusercontent.com/69106310/129639151-f5ae3958-57f0-47f5-b9be-534074769316.png)

**Comment by nnothstine** [comment]
Ah, understood. Thank you very much.

**Comment by stenya** [comment]
Hi. 
This task is not prioritized yet. But I will keep it on my to-do list for the investigation.

**Comment by gorkapernas** [comment]
Verified on Windows 10 and Windows 11, IVPN has been added to winget-pkgs, currently the latest IVPN version 3.4.1 can be installed successfully with winget by simply running the following command -> `winget install ivpn`.
