### ISSUE TITLE
(Linux) Add required WireGuard packages as a dependency to IVPN base package

### ISSUE THREAD

**Issue by stenya** [ivpn/desktop-app#69]
Necessary to find a solution to integrate dependency to the WireGuard package from the IVPN base package.
The WG has to be installed automatically together with the IVPN base package.

Ideally, the dependency has to be soft and the IVPN installation should not fail in case of WG install failed.
As idea: If the soft dependency is not possible - necessary to extend the text notification for users with detailed instructions on how to install WG manually.

**Comment by stenya** [comment]
https://github.com/ivpn/desktop-app/issues/6

**Comment by stenya** [comment]
IVPN client is using binaries from `wireguard-tools` package to manage WireGuard connection.
Most popular Linux distributives have `wireguard-tools` package in their repositories (literally same name).
I added a strict dependency to `wireguard-tools` into IVPN base packages (deb and rpm).

NOTE! If a Linux distributive does not have that package in its repository, the installation will fail.

**Comment by stenya** [comment]
@gorkapernas v3.3.43 is ready for testing

**Comment by gorkapernas** [comment]
Verified on v3.3.43, WG package installation failed on Debian OS, see screenshot below.

![Image 2021-09-21 at 6 40 46 PM](https://user-images.githubusercontent.com/16647612/134305876-6047d66c-29e7-49e4-8439-6613ac21df2a.png)

Currently checking RPM packages.

**Comment by gorkapernas** [comment]
Verified on v3.3.68, tested on several Linux OS, the wireguard package has been integrated into the IVPN base package correctly, therefore wireguard tools are installed correctly along with IVPN in all linux distributions.
I also confirmed connectivity with WireGuard after installation and the IVPN app connected successfully. 
This is good go.

**Comment by stenya** [comment]
Released in v3.4.0
