### ISSUE TITLE
Blur QR code as default

### ISSUE THREAD

**Issue by mucke5** [ivpn/desktop-app#7]
Add a button with Show (Anzeigen) and Hide (Verbergen)
![image](https://user-images.githubusercontent.com/13103826/115969663-58204f80-a53e-11eb-9d66-c8e22f0a0142.png)

**Comment by stenya** [comment]
v3.14.17

**Comment by gorkapernas** [comment]
Verified on version 3.14.17 across all platforms, the QR code and account ID are hidden by default. They are revealed only when the user clicks on the 'crossed eye' icon. If the user navigates away from the account screen and then returns, the QR code and account ID will be hidden again.
