### ISSUE TITLE
Multiple UI instances

### ISSUE THREAD

**Issue by gorkapernas** [ivpn/desktop-app#71]
### Description:
On Windows 10 and 11, it is possible to open multiple UI instances when running the IVPN client through the Windows Start menu. This is possible when performing the following steps.

### Steps to reproduce:
1. Install the latest Windows client 3.3.30.
2. Make sure the IVPN client is closed.
3. Open the Windows Start menu.
4. Type 'IVPN'
5. Press the 'Enter' key twice or more.
6. Observe that two UI instances are opened.

### Expected result:
Only one UI instance should be opened when running IVPN through the Windows Start menu.

### Environment:
IVPN: 3.3.30
OS: Windows 10, Windows 11

**Comment by stenya** [comment]
The issue related to all platforms (not only to Windows)

**Comment by gorkapernas** [comment]
Verified fixed on v3.3.52, all platforms, only one UI instance is opened every time.

**Comment by stenya** [comment]
Released in v3.4.0
