### ISSUE TITLE
linux: light/dark options for system tray icon

### ISSUE THREAD

**Issue by lsm5** [ivpn/desktop-app#73]
# Feature request

## Description

I use a light background status bar, so the system tray icon is really hard to see. 

## Describe the solution you'd like

It would be really nice to be able to configure the system tray icon colour for easy visibility. Maybe in the `View` section, there could be an additional option for it.

**Comment by stenya** [comment]
@gorkapernas v3.9.52
(Linux) Added a new settings option `General -> View -> Tray icon`:
- Light
- Dark

**Comment by gorkapernas** [comment]
Verified on beta 3.9.53, tested on different Linux distributions where the system tray icon is available, the option to change the tray icon color has been implemented and works as expected agains different backgrounds.

@stenya do we need to display this option on Linux distributions where the system tray icon is not available? e.g. Fedora, on this distro, the option is useless, should we hide it or keep it anyways?

**Comment by Amolith** [comment]
Is the icon coloured or simply dark/light?

In many situations (mine included), a user might have things set up to automatically swap between light and dark themes based on the time of day. If the app can auto-detect the system theme and change the icon accordingly, that would be perfectly fine. Otherwise, it might be good to have a coloured variant that would be visible against both light and dark backgrounds.

**Comment by stenya** [comment]
Hi @gorkapernas 

> do we need to display this option on Linux distributions where the system tray icon is not available? e.g. Fedora, on this distro, the option is useless, should we hide it or keep it anyways?

Unfortunately, there is no good enough mechanism to detect if the tray icon is able to be shown on Linux.
So, I plan to permanently show the 'Tray icon' option in the app settings.

Just FYI:  [some info](https://github.com/ivpn/desktop-app/issues/85) on how to enable tray icons in Gnome.

**Comment by stenya** [comment]
Released in [v3.10.0 Beta](https://github.com/ivpn/desktop-app/releases/tag/v3.10.0)
