### ISSUE TITLE
Fastest server settings are ignored when using WireGuard

### ISSUE THREAD

**Issue by edwardivpn** [ivpn/desktop-app#76]
# Bug report

## Describe your environment

* Device: Macbook Pro
* OS name and version: 11.5.1
* IVPN app version: 3.3.20

## Describe the problem

Fastest server settings are ignored when using WireGuard

### Steps to reproduce:

1. Set VPN protocol to WireGuard
2. Navigate to the Fastest Server Settings area and deselect all servers but one, e.g. the farthest from your physical location
3. Connect to the Fastest Server

### Observed Results:

The app ignores Fastest servers settings and connects to the server with the lowest latency

### Expected Results:

The Fastest Server feature should determine the fastest server only from non-deselected servers

**Comment by stenya** [comment]
The issue happens when the selected server(s) from the Fastest Server Settings are do not have latency info (e.g. app is just started and latency is still calculating).

**Comment by stenya** [comment]
Beta v3.3.47 is ready for testing

**Comment by gorkapernas** [comment]
Verified fixed on v3.3.47, the issue no longer occurs, the VPN always connects to the servers set in the fastest server configuration, even when the latency calculation is not fully done yet, for instance, when connecting at launch.
When there is only one server set to be the fastest server, the app will always connect to this server as fastest.
This should be good to go.

**Comment by stenya** [comment]
Released in v3.4.0
