### ISSUE TITLE
Add option to change server/IP within the same city

### ISSUE THREAD

**Issue by MFTabriz** [ivpn/desktop-app#78]
# Feature request

## Description

Sometime there is a problem with one of the servers or the server's IP is in some black list. It would be nice to have an option to manually select different servers in the same city.

## Describe the solution you'd like

Automatically do the load balancing and connect to the fastest server but show a list of available servers in a city for users to choose from [if they wish].

## Describe alternatives you've considered

Disconnecting and connecting again and again and praying to the FSM to get a different server: not a reliable solution!

**Comment by eldervamp** [comment]
A few years back I had emailed this same issue to there support. Certain Data-centers provide me better connections then others. Was forced to use the openvpn / wireguard native apps in the mean time. Guess they still haven't implemented that feature into there apps yet  :(.

**Comment by stenya** [comment]
This feature is implemented in CLI since v3.4.0.
Examples:

>> ivpn servers -hosts
>> ivpn connect nl6.gw.ivpn.net
>> ivpn connect -exit_svr ch01.wg.ivpn.net us-ny2.wg.ivpn.net
