### ISSUE TITLE
Update Electron in the binary package due to the glibc update

### ISSUE THREAD

**Issue by sith-on-mars** [ivpn/desktop-app#79]
# Bug report

## Describe your environment

* Device: _____  
* OS name and version: OpenSUSE Tumbleweed Gnome
* IVPN app version: 3.3.30 

## Describe the problem
I'm using the binary version of the package. A recent snapshot OpenSUSE Tumbleweed updates glibc to version 2.34, which caused some Electron apps unable to function properly. As for IVPN, the UI app seemed to be able to run in the background, but it showed a blank page once you tried to open the settings.

There are some discussions on the [forum](https://forums.opensuse.org/showthread.php/560226-Electron-apps-fail-to-launch-FATAL-gpu_data_manager_impl_private-cc(415)-GPU-process-isn-t-usable). Seems this issue is fixed on Electron 14 and Electron is trying to backport the fix in Electron 12 and 13.

Can you please consider update the Electron version, like to 14 maybe? Many thanks!

**Comment by stenya** [comment]
Hi @sith-on-mars 
The active beta version we working on is using Electron v13.

Unfortunately, we facing some problems with Electron v14 on Windows.
We will switch to Electron 14 (or 15) as soon as we will solve all problems with this version.

**Comment by sith-on-mars** [comment]
Thanks! Electron just released [v13.5](https://github.com/electron/electron/releases/tag/v13.5.0) which fixes the crash issue with glibc 2.34.

**Comment by stenya** [comment]
Electron updated to v14.0.1

**Beta** versions (v3.3.49) are ready for testing:

RPM
Base: https://repo.ivpn.net/beta/ivpn-3.3.49-1.x86_64.rpm
UI: https://repo.ivpn.net/beta/ivpn-ui-3.3.49-1.x86_64.rpm

DEB
Base: https://repo.ivpn.net/beta/ivpn_3.3.49_amd64.deb
UI: https://repo.ivpn.net/beta/ivpn-ui_3.3.49_amd64.deb

**Comment by gorkapernas** [comment]
Verified on v3.3.49,  OpenSUSE Tumbleweed Gnome, IVPN GUI works as expected with the updated electron v14.0.1, tested  the app after fresh installation and on upgrade from 3.3.30.

@sith-on-mars please let us know if the latest IVPN beta 3.3.49 also fixes the problem for you. Thanks 
Beta versions: https://github.com/ivpn/desktop-app/issues/79#issuecomment-931433456

**Comment by sith-on-mars** [comment]
Many thanks for the fix! It works on my system!

**Comment by stenya** [comment]
Released in v3.4.0
