### ISSUE TITLE
Split tunneling doesnt seem to work

### ISSUE THREAD

**Issue by TimmyBoi155** [ivpn/desktop-app#80]
# Bug report

## Describe your environment

* Device: _____  
* OS name and version: Arch Linux (linux-firmware 20210818.c46b8c3-1)
* IVPN app version: master branch

## Describe the problem

Today i compiled the master branch (daemon and cli) so I could try out the new split tunneling feature.

I decided to try it out with a vanilla firefox install:
```
ivpn splittun -on
Split Tunnel : Enabled

ivpn splittun -appadd /usr/lib/firefox/firefox

ivpn splittun -status
Split Tunnel      : Enabled
Split Tunnel apps : /usr/lib/firefox/firefox

```

I made sure that firefox was not running whatsoever. But i tested out my IP on browserleaks and another whatismyip sort of site, and it still showed the same IP address of the VPN server instead of my real IP address.

If you need anymore info please let me know and i will get it to you right away

**Comment by stenya** [comment]
Hello @TimmyBoi155 

The Split Tunneling feature is not implemented for Linux yet. 

Anyway, thank you for the report.
I will update the master branch: will remove the command 'splittun' from the CLI for the platforms which do not support this feature yet.

P.S. The last official version for Linux is v3.3.30 (https://github.com/ivpn/desktop-app/releases/tag/v3.3.30)
