### ISSUE TITLE
(macOS) LAN traffic blocked in latest version

### ISSUE THREAD

**Issue by ajay-gh** [ivpn/desktop-app#82]
# Bug report

## Describe your environment

* Device: Mac
* OS name and version: 10.14.6
* IVPN app version: 3.3.20

## Describe the problem
regardless of settings under "LAN settings" the latest version of the client does not permit access to local devices when IVPN is connected and the firewall is turned ON. A similar problem was noted with earlier versions of IVPN, but turning the "allow LAN traffic" flag OFF and ON again did solve the problem. Now the firewall has to be disabled.

### Steps to reproduce:

1. obvious
2. _____
3. _____

### Observed Results:
all connections time-out

**Comment by stenya** [comment]
@ajay-gh Hi

Do you enable "Allow LAN traffic when IVPN Firewall is enabled" in settings?

If it is enabled:
To analyze your problem we need to understand your local network configuration.
Therefore, such information will be very helpful:
- the network mask you connected to
- the IP addresses of devices you are trying to connect to

**Comment by ajay-gh** [comment]
Yes, I did use the flag many times in the last years. I think my second sentence indicates this.
Network mask: 255.255.255.0
IP address (example) : 192.168.0.1
(this way I access my router, this worked definitely with version v2.X, and I think it worked with version v.3.3.10, but not entirely sure)

**Comment by CryptoGrampy** [comment]
I just want to add that I'm having this same problem on Linux/ PopOS.  With 'allow LAN traffic' when iVPN firewall is enabled' flag checked in the app, on reboot, LAN traffic is blocked.  I have to uncheck and check this box in the app and LAN traffic seems to immediately start working again.

**Comment by stenya** [comment]
@ajay-gh Can you, please, confirm that you still observing this issue with the latest app version (v3.4.0)?

**Comment by ajay-gh** [comment]
Sorry, I didn't see this request when published.
Yes, as far as I can tell the problem is gone.
