### ISSUE TITLE
(Linux) "Allow LAN traffic" does not persist after a restart on Fedora 34

### ISSUE THREAD

**Issue by jordan-ivpn** [ivpn/desktop-app#84]
# Bug report

## Describe your environment

* Device: _____  
* OS name and version: Fedora 34 and Fedora 35 beta, updated to 2021-09-29
* IVPN app version: 3.3.30 ivpn and ivpn-ui  

Fedora-Workstation-Live-x86_64-34-1.2.iso

firewalld-0.9.4-1.fc34.src.rpm
gnome-desktop3-40.4-1.fc34.src.rpm
iptables-1.8.7-3.fc34.src.rpm
ivpn-3.3.30-1.src.rpm
ivpn-ui-3.3.30-1.src.rpm
systemd-248.7-1.fc34.src.rpm

## Describe the problem

"Allow LAN traffic" and "Allow Multicast" are checked in the UI and LAN traffic is permitted when these are first activated, but after a reboot, LAN traffic is blocked.  Both options are still checked in the UI.  Running `ivpn firewall -lan_allow` after a restart resolves the issue.

Issue was reported to occur on Fedora 34 and Fedore 35 beta.  Issue is verified on Fedora 34, but UI will not fully open on Fedora 35 beta; sometimes, there is a white window for the UI, but no contents are displayed and other times, the UI never opens.

### Steps to reproduce:

1. Check both LAN options in the UI
2. Check options to launch at login and autoconnect on launch
3. Connect the VPN (OpenVPN or WG, both were tested)
4. Verify LAN access to device on same subnet
5. Restart the computer system
6. Test LAN access, like ping

### Observed Results:

Traffic is blocked until explicitly allowing it via the command line.  Traffic is likely permitted after toggling the two LAN options in the UI.

### Expected Results:

LAN traffic to devices on the same subnet should be permitted after a restart.

**Comment by jordan-ivpn** [comment]
Fedora 35 beta white window issue is resolved with #79 [comment](https://github.com/ivpn/desktop-app/issues/79#issuecomment-931433456).  Firewall persistence issue to access LAN clients is still present in 35 beta.

**Comment by stenya** [comment]
@jordan-ivpn Can you, please, share the IVPN logs with me?

**Comment by stenya** [comment]
@jordan-ivpn @gorkapernas 
Fix available in the base package v3.3.51 (beta).
The issue was related to Linux in general (not only to Fedora). 

@jordan-ivpn Can you, please, check if it is fixed for you.

**Comment by jordan-ivpn** [comment]
@stenya 
Issue is resolved with 3.3.51 on both Fedora 34 and 35 beta.  Thanks!

**Comment by stenya** [comment]
Released in v3.4.0
