### ISSUE TITLE
(Linux) Tray icon missing in Fedora 34 and 35 beta

### ISSUE THREAD

**Issue by jordan-ivpn** [ivpn/desktop-app#85]
# Bug report

## Describe your environment

* Device: _____  
* OS name and version: Fedora 34 and Fedora 35 beta, default install updated to 2021-09-29  
* IVPN app version: 3.3.30 ivpn and ivpn-ui

Fedora-Workstation-Live-x86_64-34-1.2.iso

gnome-desktop3-40.4-1.fc34.src.rpm
ivpn-3.3.30-1.src.rpm
ivpn-ui-3.3.30-1.src.rpm
systemd-248.7-1.fc34.src.rpm

Fedora-Workstation-Live-x86_64-35_Beta-1.2.iso

## Describe the problem

An issue was reported where the IVPN App's tray icon would not appear on Fedora 35 beta with Gnome 41 desktop environment.  I reproduced the issue with no tray icon on Fedora 34 with Gnome 40, but UI will not fully open on Fedora 35 beta; sometimes, there is a white window for the UI, but no contents are displayed and other times, the UI never opens.

### Steps to reproduce:

1. Install the App
2. Launch the App
3. UI opens, Activity icon, name, and context menu are on the left side of the menu along the top of the screen, but no icon is visible in the system tray; audio, network, and power tray icons are present.

### Observed Results:

There is no tray icon.

### Expected Results:

There is a tray icon.

**Comment by tommytran732** [comment]
You need both of the appindicator extension for gnome and the libappindicator-gtk3 for it to show up

**Comment by jordan-ivpn** [comment]
```
gnome-shell-extension-appindicator.noarch
libappindicator-gtk3.x86_64
```

Installed (plus dependencies), but still no tray icon in a default Fedora 34 install.  Rebooted after installing.

Fedora 35 beta had the same two packages installed (plus dependencies), but the app still does not open.

**Comment by stenya** [comment]
@jordan-ivpn can you, please, check if the latest beta v3.3.49 is working fine on Fedora 35. (links are here: https://github.com/ivpn/desktop-app/issues/79#issuecomment-931433456 )
I guess, it can be similar issue.

**Comment by jordan-ivpn** [comment]
@stenya 
The IVPN App opens after upgrading base and UI packages to v3.3.49.  Still no tray icons in Gnome.

**Comment by tommytran732** [comment]
Have you tried the AppIndicator app from Gnome Extensions and not from the Fedora's repo?

**Comment by stenya** [comment]
Discussion on Reddit: https://www.reddit.com/r/Fedora/comments/mkfxp7/no_tray_icons_extension_on_fedora_34_gnome_40/

**Comment by stenya** [comment]
Additional info:
https://fostips.com/mac-os-bartender-system-tray-icons-gnome-40/

**Comment by stenya** [comment]
I did manage it by installing Gnome shell extensions and enabling KStatusNotifierItem.

![Screen Recording 2021-10-01 at 12 45 33 PM](https://user-images.githubusercontent.com/7881006/135600544-46585264-f65b-4d10-a930-1bdd34b577e4.gif)

@jordan-ivpn 
It looks like not an issue but as design for "Gnome 40". I am going to close this ticket if you do not mind.

**Comment by jordan-ivpn** [comment]
Thanks.
