### ISSUE TITLE
Fedora Silverblue support

### ISSUE THREAD

**Issue by tommytran732** [ivpn/desktop-app#86]
# Bug report

## Describe your environment

* Device: Laptop
* OS name and version: Fedora Silverblue 34
* IVPN app version: v3.3.30

## Describe the problem
IVPN does not work properly on Fedora Silverblue

### Steps to reproduce:

1. Install IVPN on Fedora Silverblue
2. Reboot
3. Launch the ivpn-ui

### Observed Results:

The UI says that it cannot contact the daemon.

### Expected Results:

The UI connects to the daemon and IVPN works normally.

**Comment by stenya** [comment]
Hi @tommytran732 ,
To analyze this issue, it would be helpful to know the way you installed IVPN software Fedora Silverblue 34.
Did you use IVPN repo or did manual installation? Did you use any additional operation to make containerized IVPN package?

**Comment by tommytran732** [comment]
> Hi @tommytran732 , To analyze this issue, it would be helpful to know the way you installed IVPN software Fedora Silverblue 34. Did you use IVPN repo or did manual installation? Did you use any additional operation to make containerized IVPN package?

I am using the IVPN repo and overlayed the package using rpm-ostree. No sandboxing was attempted.

**Comment by tommytran732** [comment]
I just want to give an update that this is reproducible in Fedora Silverblue 35 as well.

**Comment by stenya** [comment]
Hi @tommytran732 ,
we currently do not support Fedora Silverblue due to the specifics of this Linux distribution. 
But I keep this requirement on my to-do list.
We will discuss prioritization for this ticket with our team shortly.

**Comment by TrashPandaCodingGarbage** [comment]
Hey there IVPN Team,

Any progress with that? The only thing I'm missing on my Silverblue is IVPN Support.

**Comment by jordan-bravo** [comment]
+1 for support for Fedora Silverblue.

I am on Fedora Silverblue 37 and I had the exact same issue as OP.

**Comment by stenya** [comment]
Commands to install ivpn client on Fedora Silverblue:
```
# install IVPN client
rpm-ostree install ivpn-3.10.7-1.x86_64.rpm
# install UI for IVPN client (if required)
rpm-ostree install ivpn-ui-3.10.7-1.x86_64.rpm

# reboot system
systemctl reboot

# enable IVPN service to start automatically
systemctl enable ivpn-service
# start IVPN stervice
systemctl start ivpn-service
```

**Comment by stenya** [comment]
@gorkapernas v3.10.7 is ready for tests

**Comment by gorkapernas** [comment]
Verified on latest beta, v3.10.9, the IVPN app runs correctly and works for the most part, however we have a problem with Split Tunnel, see following screenshot for further details,
![split tunnel error](https://user-images.githubusercontent.com/16647612/216558852-5fefebe4-ce5b-45a6-b2e1-d3c8d2fb4bd6.jpg)

Please note that this issue might be related to https://github.com/ivpn/desktop-app/issues/151

Also, it seems that I can't fully uninstall the application (or maybe I don't know how to), I usually run `rpm-ostree uninstall ivpn` which deletes the app, but when I install the new version, I still have the settings from the old one.

**Comment by stenya** [comment]
```Also, it seems that I can't fully uninstall the application (or maybe I don't know how to), I usually run rpm-ostree uninstall ivpn which deletes the app, but when I install the new version, I still have the settings from the old one.```

The `rpm-ostree uninstall ...` command does not trigger 'removal' scriptlets for some reason.
To correctly uninstall 'ivpn' package on Fedora Silverblue, extra steps should be performed manually:
```
# logout from ivpn account 
ivpn logout

# uninstall IVPN client
rpm-ostree uninstall ivpn

# stop and disable IVPN service
sudo systemctl stop ivpn-service
sudo systemctl disable ivpn-service

# manualy remove leftovers
sudo rm -fr /etc/opt/ivpn
sudo rm -fr /var/log/ivpn
```

**Comment by gorkapernas** [comment]
Verified on v3.10.10, the issue with the Split Tunnel feature has been fixed.
Also the uninstalling steps provided in the comment above removes the IVPN packages, however there are still some IVPN files present in the system after the uninstalling the packages. It could be cache since installing a new version overwrites those files (further investigation might be needed).

@stenya there is one issue when enabling " "Force management of DNS..." and connecting with OpenVPN, when doing so, the internet traffic is blocked. This issue doesn't seem to happen in other Linux distros.

**Comment by stenya** [comment]
@gorkapernas fixed in daemon v3.10.11
Fix details (fix related to the Linux platform in general):

Option "DNS -> Force management of DNS using resolve.conf" did not work properly with OpenVPN connections.
The 'resolvectl' was used always in OpenVPN 'up' script (independently from the option value).
It was a reason for DNS misconfiguration:  the '/etc/resolve.conf' was configured properly (to use IVPN AntiTracker), but active DNS settings were configured by 'resolvectl' to use 'default IVPN DNS server' and IVPN Firewall blocked all non-Antitracker requests.

STR: OpenVPN + "Force ... resolve.conf" + FirewallON + AntiTracker(or custom DNS)

**Comment by gorkapernas** [comment]
Verified on latest beta versions, last one being 3.10.14, all the issues reported for Linux distributions have been fixed.
I've also run IVPN on Fedora Silverblue for the past few days and it seems to be working as expected.

**Comment by jordan-ivpn** [comment]
@gorkapernas @stenya

One report of an error with *Sparrow Wallet*:
> trying to open an app with split tunneling and receiving the following error:
>
> "Failed to enable Split Tunneling: (exit status 2) Error: Egress device not specified."

https://www.sparrowwallet.com/download/

> Operating system: Fedora Silverblue 37
> IVPN UI Client version v3.10.14

I'll start downloading the Silverblue ISO, though it will likely take time to get up so speed with it.  If you have a test system ready to go, it might be easier.  Thanks!

**Comment by stenya** [comment]
Just a guess: probably it can be related to IPv6 configuration. We need to test it on the system where both protocols are configured (IPv4 and IPv6).

**Comment by stenya** [comment]
_I created a separate ticket for the specific Split Tunneling issue described in the previous comments._

v3.10.14 is released. 
IVPN client can be installed on Fedora Silverblue using rpm-ostree.

Commands to install ivpn client on Fedora Silverblue (example):
```
# install IVPN client
rpm-ostree install ivpn-3.10.14-1.x86_64.rpm
# install UI for IVPN client (if required)
rpm-ostree install ivpn-ui-3.10.14-1.x86_64.rpm

# reboot system
systemctl reboot

# enable IVPN service to start automatically
sudo systemctl enable ivpn-service
# start IVPN stervice
sudo systemctl start ivpn-service
```

To correctly uninstall 'ivpn' package on Fedora Silverblue, extra steps should be performed manually  (example):
```
# logout from ivpn account 
ivpn logout

# uninstall IVPN client
rpm-ostree uninstall ivpn
# uninstall IVPN User Interface (if installed)
rpm-ostree uninstall ivpn-ui

# stop and disable IVPN service
sudo systemctl stop ivpn-service
sudo systemctl disable ivpn-service

# manualy remove leftovers
sudo rm -fr /etc/opt/ivpn
sudo rm -fr /var/log/ivpn

# reboot system
systemctl reboot
```
