### ISSUE TITLE
[Feature Request] See an estimate of how many people are connected to a server

### ISSUE THREAD

**Issue by TimmyBoi155** [ivpn/desktop-app#88]
# Feature request

## Description

Currently there is no way to see how many people are connected to a specific IVPN server. So therefore it is difficult to be able to choose a server with a high anonymity set in order to increase your anonymity.

## Describe the solution you'd like

Would be nice to be able to have a button that makes a request to see approximately how many people are connected to any particular server. For example, "1000-2000", "5000-6000", etc

**Comment by stenya** [comment]
Hi @TimmyBoi155 ,
I am afraid, we are not collecting the info about the amount of connected clients to a server. 
There is only possible to see a [server load](https://www.ivpn.net/status/) on our website.
