### ISSUE TITLE
GPG Signed binaries?

### ISSUE THREAD

**Issue by jonathancross** [ivpn/desktop-app#9]
# Please offer a gpg signature of binaries

## Description

GitHub / website hosting infrastructure, certificate authorities, (or anyone with access to these) may try to post fake VPN binaries and try to trick users into installing them.  While this may be remote, such a risk is dramatically reduced or eliminated through the use of OpenPGP digital signatures.  Ideally signing keys should be kept on hardware smartcard such as Yubikey, Nitrokey, etc.

## Describe the solution you'd like

In order to reduce trust on GitHub / website hosting infrastructure, certificate authorities, etc -- please make gpg signatures available for each binary.  Another option is to sha256 hash all binaries and sign that list once.

## Describe alternatives you've considered

The sha256 hash on the website is inadequate when trying to verify authenticity -- both are hosted on the same platform, so an attacker should just replace the hash with their own.

**Comment by stenya** [comment]
Hi @jonathancross 
we have implemented the possibility to verify binaries. It works for versions starting from v3.0.0.

Next steps should be performed, to verify the signature (we did not update this info on the website yet):
1.  Download ‘installer' and it's signature. 
The signature file has the same name as binary with the `.sign.sha256.base64` at the end.
macOS (example):
`https://repo.ivpn.net/macos/bin/IVPN-3.3.20.dmg` and `https://repo.ivpn.net/macos/bin/IVPN-3.3.20.dmg.sign.sha256.base64`
Windows (example):
`https://repo.ivpn.net/windows/bin/IVPN-Client-v3.3.20.exe` and `https://repo.ivpn.net/windows/bin/IVPN-Client-v3.3.20.exe.sign.sha256.base64`

2.  Download OpenSSL public key for verification 
macOS: `https://repo.ivpn.net/macos/keys/public.pem`
Windows: `https://repo.ivpn.net/windows/keys/public.pem`

3.  Verification commands 
macOS (example):
```
    # Decode base64:
    $ openssl base64 -d -in IVPN-3.3.20.dmg.sign.sha256.base64 -out IVPN-3.3.20.dmg.sign.sha256
    # Check signature:
    $ openssl dgst -sha256 -verify public.pem -signature IVPN-3.3.20.dmg.sign.sha256 IVPN-3.3.20.dmg
```
Windows (example):
```
    # Decode base64:
    $ openssl base64 -d -in IVPN-Client-v3.3.20.exe.sign.sha256.base64 -out IVPN-Client-v3.3.20.exe.sign.sha256
    # Check signature:
    $ openssl dgst -sha256 -verify public.pem -signature IVPN-Client-v3.3.20.exe.sign.sha256 IVPN-Client-v3.3.20.exe
```

**Comment by jonathancross** [comment]
Hi @stenya  I appreciate you making some effort here, but this is not the same as a GPG signature.
With GPG/PGP we have a "web of trust" -- a way to establish trust (out of band) that the key used to sign is **_authentic_**.
With your suggested replacement, we are left to trust whatever certificate is returned at the above URL.

**Comment by jordan-ivpn** [comment]
Another request for key verefication.

Example: https://docs.wasabiwallet.io/using-wasabi/InstallPackage.html#debian-and-ubuntu
