### ISSUE TITLE
Force automatic WireGuard key regeneration if the rotation interval has passed

### ISSUE THREAD

**Issue by jordan-ivpn** [ivpn/desktop-app#90]
# Bug report

## Describe your environment

* Device: notebook  
* OS name and version: Windows & macOS  
* IVPN app version: 3.3.30  

## Describe the problem

If a computer system is powered off when the WireGuard key rotation is scheduled to occur, rotation is impossible.  After powering the system on, the IVPN App will display a `Will be automatically rotated` date in the past.  Manually regenerating the key seems to be required.

### Steps to reproduce:

1. Set rotation interval to one day
2. Power a system off for two days
3. Power the system on and check `automatically rotated` date

### Observed Results:

The key does not automatically rotate immediately at the earliest available opportunity.

### Expected Results:

The IVPN App forces a key rotation at the earliest opportunity if the `automatically rotated` date is in the past.

Thanks.

**Comment by gorkapernas** [comment]
Verified on version 3.3.73 which has shorter time intervals (1 day -> 10 minutes) and the app always generates a new key when required after awaking the machine.
`Will be automatically rotated` date is never displayed in the past.

I'll test this during the weekend with the regular version 3.3.72 which has normal rotation intervals.

**Comment by stenya** [comment]
Released in v3.4.0
