### ISSUE TITLE
[feature] Keep unchanged the app configuration on logout

### ISSUE THREAD

**Issue by stenya** [ivpn/desktop-app#91]
# Feature request

Currently, the IVPN Client erasing application configuration when a user logs out.

This has to be changed:
1. keep unchanged the app configuration on logout by default (with an option to clear it in the app)
2. when FW is enabled then there should be a warning on the logout page that FW is enabled and all network access will be blocked (the same functionality have to be implemented in CLI)
3. Necessary to implement the possibility to control the Firewall state even when the user is logged out: Add a switcher at the bottom of the login UI which shows the current firewall state. IF the 'always-on' firewall is enabled then when the user attempts to switch the firewall off we show a dialog box saying `The always-on firewall is enabled. If you disable the firewall the 'always-on' feature will be disabled.` [Disable Always-on firewall] / [Cancel].

Additionally, implement the possibility to control Firewall "Always-on" state from CLI

**Comment by stenya** [comment]
v3.3.61

**Comment by gorkapernas** [comment]
Verified on v3.3.64, all platforms, the last requested change about keeping the Always-on FW enabled on logout has been implemented correctly.
All the other requirements work as expected.

**Comment by stenya** [comment]
Released in v3.4.0
