### ISSUE TITLE
Spelling in AntiTracker description

### ISSUE THREAD

**Issue by jordan-ivpn** [ivpn/desktop-app#92]
https://github.com/ivpn/desktop-app/blob/4b0e4e639cdfdf7fec16f021a60b7942f979023d/ui/src/components/settings/settings-antitracker.vue#L24

surveilance --> surveillance

**Comment by gorkapernas** [comment]
Verified on v3.3.64, the spelling mistake has been fixed.

**Comment by stenya** [comment]
Released in v3.4.0
