### ISSUE TITLE
[bug] UI: System tray menu shows "Random Server" when connected with MultiHop

### ISSUE THREAD

**Issue by gorkapernas** [ivpn/desktop-app#94]
### Description:
With OpenVPN and WireGuard, when connected with MultiHop using "Random Server" as the exit server, the system tray menu shows "Random Server in the connection info instead of the location name.

### Expected result:
The app should always show the location the user is connected to in the system tray menu.

### Steps to reproduce:
1. Install version 3.4.0.
2. Login.
3. Connect with MultiHop, entry server -> any, exit server -> random server
4. Open the system tray menu.
5. Observe that the connection info shows the correct entry server and "random server" as the exit server.

### Environment:
IVPN: 3.4.0
OS: All Platforms

### Screenshot:
![random server_system tray](https://user-images.githubusercontent.com/16647612/140774791-bd67ab14-9c11-415d-8236-08bc52a01b42.png)

**Comment by stenya** [comment]
@gorkapernas  v3.8.10 is ready for testing

**Comment by gorkapernas** [comment]
Verified fixed on v3.8.10, all platforms, the expected exit location is shown in the system tray menu when the app is connected to the VPN.

**Comment by stenya** [comment]
v3.8.20 released
