### ISSUE TITLE
(Linux) Split Tunneling

### ISSUE THREAD

**Issue by stenya** [ivpn/desktop-app#95]
# Feature request

## Description
Allow users to specify which apps don't send traffic through the VPN connection.

**Comment by stenya** [comment]
v3.4.10 is ready for testing

**Comment by stenya** [comment]
v3.4.11

**Comment by stenya** [comment]
@gorkapernas v3.4.20

**Comment by stenya** [comment]
@gorkapernas 
v3.4.22

**Comment by trymeouteh** [comment]
Please add the ability to add EXE files from Wine or Proton as exceptions in split tunnelling.

**Comment by gorkapernas** [comment]
This has been tested on latest beta versions during the past few weeks and it's ready to go live.
