### ISSUE TITLE
(macOS) UI/CLI: Possibility to see the architecture for which the application compiled (e.g. x86_64, arm64)

### ISSUE THREAD

**Issue by stenya** [ivpn/desktop-app#96]
# Feature request

## Description

Currently, there is no way to see which version of the IVPN app (intel or m1) you are running right now.
It is necessary to show this information in UI/CLI.

**Comment by stenya** [comment]
CLI: `ivpn -v`
UI: mouse click on the application version in Settings

**Comment by stenya** [comment]
@gorkapernas  v3.8.10 is ready for testing

**Comment by gorkapernas** [comment]
Verified on v3.8.10, this has been implemented in all platforms, not only macOS, as described in the ticket. Now it is possible to see the architecture of the the app.

Ref: https://github.com/ivpn/desktop-app/issues/96#issuecomment-1129965628
